### ISSUE TITLE
Support for algpseudocode

### ISSUE THREAD

**Issue by koppor** [cmhughes/latexindent.pl#100]
Input:

```
\If{$a\in\mathcal{A}_\mathit{basic}$}
  \State \Call{HandleBasicActivity}{$a$,$v_e$}
\ElsIf{$a\in\mathcal{A}_\mathit{flow}$}
  \State \Call{HandleFlow}{$a$,$v_e$}
\ElsIf{$a = \mathsf{process}$} \Comment Directly handle the contained activity
  \State \Call{HandleActivity}{$a'$,$v_e$}, $(a,\bot,a') \in \mathsf{HR}$
  \State $\mathsf{writes}_\bullet(a) \gets \mathsf{writes}_\bullet(a')$
\EndIf
```

Output:

```
\If{$a\in\mathcal{A}_\mathit{basic}$}
\State \Call{HandleBasicActivity}{$a$,$v_e$}
\ElsIf{$a\in\mathcal{A}_\mathit{flow}$}
\State \Call{HandleFlow}{$a$,$v_e$}
\ElsIf{$a = \mathsf{process}$} \Comment Directly handle the contained activity
\State \Call{HandleActivity}{$a'$,$v_e$}, $(a,\bot,a') \in \mathsf{HR}$
\State $\mathsf{writes}_\bullet(a) \gets \mathsf{writes}_\bullet(a')$
\EndIf
```

It would be nice if the commands of algpseudocode (of the [algorithmicx](https://ctan.org/pkg/algorithmicx)) package were supported

**Comment by cmhughes** [comment]
How about treating them as headings, such as
## localSettings.yaml
```
defaultIndent: '  '
indentAfterHeadings:
    If:
       indentAfterThisHeading: 1
       level: 1
    ElsIf:
       indentAfterThisHeading: 1
       level: 1
    EndIf:
       indentAfterThisHeading: 1
       level: 1
```

and then 
```
latexindent.pl -l myfile.tex
```
gives
```
\If{$a\in\mathcal{A}_\mathit{basic}$}
  \State \Call{HandleBasicActivity}{$a$,$v_e$}
\ElsIf{$a\in\mathcal{A}_\mathit{flow}$}
  \State \Call{HandleFlow}{$a$,$v_e$}
\ElsIf{$a = \mathsf{process}$} \Comment Directly handle the contained activity
  \State \Call{HandleActivity}{$a'$,$v_e$}, $(a,\bot,a') \in \mathsf{HR}$
  \State $\mathsf{writes}_\bullet(a) \gets \mathsf{writes}_\bullet(a')$
\EndIf
```

**Comment by koppor** [comment]
Yeah, this is a good start. I should have posted the full demo:

```
\begin{algorithm}
\caption{Euclid’s algorithm}\label{euclid}
\begin{algorithmic}[1]
\Procedure{Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
\State $r\gets a\bmod b$
\While{$r\not=0$}\Comment{We have the answer if r is 0}
\State $a\gets b$
\State $b\gets r$
\State $r\gets a\bmod b$
\EndWhile\label{euclidendwhile}
\State \textbf{return} $b$\Comment{The gcd is b}
\EndProcedure
\end{algorithmic}
\end{algorithm}
```

I set all possible to 1.

<details>

```
indentAfterHeadings:
    For:
       indentAfterThisHeading: 1
       level: 1
    EndFor:
       indentAfterThisHeading: 1
       level: 1
    ForAll:
       indentAfterThisHeading: 1
       level: 1
    While:
       indentAfterThisHeading: 1
       level: 1
    EndWhile:
       indentAfterThisHeading: 1
       level: 1
    Repeat:
       indentAfterThisHeading: 1
       level: 1
    Until:
       indentAfterThisHeading: 1
       level: 1
    If:
       indentAfterThisHeading: 1
       level: 1
    ElsIf:
       indentAfterThisHeading: 1
       level: 1
    Else:
       indentAfterThisHeading: 1
       level: 1
    EndIf:
       indentAfterThisHeading: 1
       level: 1
    Procedure:
       indentAfterThisHeading: 1
       level: 1
    EndProcedure:
       indentAfterThisHeading: 1
       level: 1
    Function:
       indentAfterThisHeading: 1
       level: 1
    EndFunction:
       indentAfterThisHeading: 1
       level: 1
    Loop:
       indentAfterThisHeading: 1
       level: 1
    EndLoop:
       indentAfterThisHeading: 1
       level: 1
```

</details>

Then I get following result

```
\begin{algorithm}
  \caption{Euclid’s algorithm}\label{euclid}
  \begin{algorithmic}[1]
    \Procedure{Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
      \State $r\gets a\bmod b$
    \While{$r\not=0$}\Comment{We have the answer if r is 0}
      \State $a\gets b$
      \State $b\gets r$
      \State $r\gets a\bmod b$
    \EndWhile\label{euclidendwhile}
      \State \textbf{return} $b$\Comment{The gcd is b}
    \EndProcedure
  \end{algorithmic}
\end{algorithm}
```

The correct result, however, would be:

```
\begin{algorithm}
  \caption{Euclid’s algorithm}\label{euclid}
  \begin{algorithmic}[1]
    \Procedure{Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
      \State $r\gets a\bmod b$
      \While{$r\not=0$}\Comment{We have the answer if r is 0}
        \State $a\gets b$
        \State $b\gets r$
        \State $r\gets a\bmod b$
      \EndWhile\label{euclidendwhile}
      \State \textbf{return} $b$\Comment{The gcd is b}
    \EndProcedure
  \end{algorithmic}
\end{algorithm}
```

Similar to nested environments in latex. If I nest an `\iftrue` inside `\begin{figure}`, the `\iftrue` is indented one more level than `\begin{figure} `.

**Comment by koppor** [comment]
The code seems to do a prefix matching of the keywords:

```
\newcommand{\executeiffilenewer}[3]{%
  \IfFileExists{#2}
```

gets

```
\newcommand{\executeiffilenewer}[3]{%
\IfFileExists{#2}
```

However, I did not configure `IfFileExists` in the above configuration.

**Comment by cmhughes** [comment]
Try the following `YAML` on your algorithmic code:
```
defaultIndent: '  '
indentAfterHeadings:
    For:
       indentAfterThisHeading: 1
       level: 1
    EndFor:
       indentAfterThisHeading: 1
       level: 1
    ForAll:
       indentAfterThisHeading: 1
       level: 1
    While:
       indentAfterThisHeading: 1
       level: 2
    EndWhile:
       indentAfterThisHeading: 1
       level: 2
    Repeat:
       indentAfterThisHeading: 1
       level: 1
    Until:
       indentAfterThisHeading: 1
       level: 1
    If:
       indentAfterThisHeading: 1
       level: 1
    ElsIf:
       indentAfterThisHeading: 1
       level: 1
    Else:
       indentAfterThisHeading: 1
       level: 1
    EndIf:
       indentAfterThisHeading: 1
       level: 1
    Procedure:
       indentAfterThisHeading: 1
       level: 1
    EndProcedure:
       indentAfterThisHeading: 1
       level: 1
    Function:
       indentAfterThisHeading: 1
       level: 1
    EndFunction:
       indentAfterThisHeading: 1
       level: 1
    Loop:
       indentAfterThisHeading: 1
       level: 1
    EndLoop:
       indentAfterThisHeading: 1
       level: 1
noAdditionalIndent:
    EndWhile:
        afterHeading: 1
```
then the output is:
```
\begin{algorithm}
  \caption{Euclid’s algorithm}\label{euclid}
  \begin{algorithmic}[1]
    \Procedure{Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
      \State $r\gets a\bmod b$
      \While{$r\not=0$}\Comment{We have the answer if r is 0}
        \State $a\gets b$
        \State $b\gets r$
        \State $r\gets a\bmod b$
      \EndWhile\label{euclidendwhile}
      \State \textbf{return} $b$\Comment{The gcd is b}
    \EndProcedure
  \end{algorithmic}
\end{algorithm}
```

**Comment by cmhughes** [comment]
In your `IfFileExists` example, you don't have a complete set of matching braces :)

**Comment by koppor** [comment]
Is it possible to get it to work with nested similar statements? E.g., If nested in another If?

```
\begin{Algorithmus}
  \begin{algorithmic}
    \If{cond1}
      \If{cond2}
        \While{cond3}
          \If{cond4}
            \State state1
          \EndIf
        \EndWhile
      \EndIf
    \EndIf
  \end{algorithmic}
\end{Algorithmus}
```

```
\begin{Algorithmus}
  \begin{algorithmic}
    \If{cond1}
    \If{cond2}
      \While{cond3}
    \If{cond4}
      \State state1
    \EndIf
      \EndWhile
    \EndIf
    \EndIf
  \end{algorithmic}
\end{Algorithmus}
```

**Comment by koppor** [comment]
Yeah, this is is a good direction. Thank you for the pointer!

It seems to be difficult to have different possible endings for `\If` and `\ElsIf`. Both can be closed by `\ElsIf` or `\EndIf`.

```
specialBeginEnd:
    specialBeforeCommand: 1
    For:
        begin: '\\For'
        end: '\\EndFor'
        lookForThis: 1
    While:
        begin: '\\While\{'
        end: '\\EndWhile'
        lookForThis: 1
    If:
        begin: '\\If\{'
        end: '(\\EndIf|\\ElsIf)'
        lookForThis: 1
    ElsIf:
        begin: '\\ElsIf\{'
        end: '(\\EndIf|\\ElsIf)'
        lookForThis: 1
    Procedure:
        begin: '\\Procedure\{'
        end: '\\EndProcedure'
        lookForThis: 1
```

When applying that to following example, I get duplicated commands:

```
\begin{Algorithmus}
  \begin{algorithmic}
    \If{cond1}
      \If{cond2}
        \While{cond3}
          \If{cond4}
            \State state1
          \EndIf
        \EndWhile
      \ElsIf{cond5}
        \State something1
      \ElsIf{cond6}
        \State something2
      \ElsIf{cond6}
        \State something3
      \EndIf
    \EndIf
  \end{algorithmic}
\end{Algorithmus}
```

```
\begin{Algorithmus}
  \begin{algorithmic}
    \If{cond1}
      \If{cond2}
        \While{cond3}
          \If{cond4}
            \State state1
          \EndIf\EndIf
        \EndWhile
        \ElsIf{cond5}
          \State something1
        \ElsIf\ElsIf{cond6}
          \State something2
          \ElsIf{cond6}
            \State something3
          \EndIf\EndIf\EndIf\EndIf\EndIf
    \EndIf
  \end{algorithmic}
\end{Algorithmus}
```

Removing the support for `ElsIf` partially solves that:

<details>

```
specialBeginEnd:
    specialBeforeCommand: 1
    For:
        begin: '\\For'
        end: '\\EndFor'
        lookForThis: 1
    While:
        begin: '\\While\{'
        end: '\\EndWhile'
        lookForThis: 1
    If:
        begin: '\\If\{'
        end: '\\EndIf'
        lookForThis: 1
    Procedure:
        begin: '\\Procedure\{'
        end: '\\EndProcedure'
        lookForThis: 1
```

</details>

```
\begin{Algorithmus}
  \begin{algorithmic}
    \If{cond1}
      \If{cond2}
        \While{cond3}
          \If{cond4}
            \State state1
          \EndIf
        \EndWhile
        \ElsIf{cond5}
        \State something1
        \ElsIf{cond6}
        \State something2
        \ElsIf{cond6}
        \State something3
      \EndIf
    \EndIf
  \end{algorithmic}
\end{Algorithmus}
```

Can I someone configure: 

```
patchIndent:
  ElsIf:
    pattern: '\\ElsIf'
    patch: -2
```

Whenever ElsIf is encountered, its indent is patched by "-2" without setting another state 😇 .

**Comment by cmhughes** [comment]
I think that we need something like
```
specialBeginEnd:
    specialBeforeCommand: 1
    If:
        begin: '\\If'
        middle: '\\ElsIf'
        end: '\\EndIf'
        lookForThis: 1
```
I should be able to implement this. I'll label it as an enhancement, although I'm afraid I can't make any promises as to the timeline of it. I tend to try to release newly-implemented features every 3 to 4 months, but will keep you updated. 

Thanks again, watch this space :)

**Comment by cmhughes** [comment]
Some thoughts on implementation: it would be good to customise the Else.pm module to allow this middle feature.

Care will be needed for the associated polyswitches.

**Comment by cmhughes** [comment]
First steps towards implementation of this feature as of https://github.com/cmhughes/latexindent.pl/commit/a280f23dbdbc8b0813c83cbc0f22588051e10870 Hopeful that the work in this commit will help. More to follow.

**Comment by cmhughes** [comment]
@koppor are able to clone branches from this repository? If so, you can take a look at the development of this feature on https://github.com/cmhughes/latexindent.pl/tree/feature/special-middle 

The syntax is as described above; you'll see in `koppor.yaml`
```
specialBeginEnd:
    specialBeforeCommand: 1
    While:
        begin: '\\While'
        end: '\\EndWhile'
        lookForThis: 1
    If:
        begin: '\\If'
        middle: '\\ElsIf'
        end: '\\EndIf'
        lookForThis: 1
```
and the associated first test case is
```
% https://github.com/cmhughes/latexindent.pl/issues/100
\begin{Algorithmus}
  \begin{algorithmic}
    \If{cond1}
      \If{cond2}
        \While{cond3}
          \If{cond4}
            \State state1
          \EndIf
        \EndWhile
        \ElsIf{cond5}
        \State something1
        \ElsIf{cond6}
        \State something2
        \ElsIf{cond6}
        \State something3
      \EndIf
    \EndIf
  \end{algorithmic}
\end{Algorithmus}
```
which, when run with `latexindent.pl -l=koppor.yaml` gives
```
% https://github.com/cmhughes/latexindent.pl/issues/100
\begin{Algorithmus}
	\begin{algorithmic}
		\If{cond1}
			\If{cond2}
				\While{cond3}
					\If{cond4}
						\State state1
					\EndIf
				\EndWhile
			\ElsIf{cond5}
				\State something1
			\ElsIf{cond6}
				\State something2
			\ElsIf{cond6}
				\State something3
			\EndIf
		\EndIf
	\end{algorithmic}
\end{Algorithmus}
```

I've got a bit more development to do before merging it into `develop`; for my own reference:

- `polyswitch` testing
- `middle` should be allowed to specified as a hash or scalar; if hash, the regexp needs to be connected together 
- documentation, including any necessary updates `documentation-default-settings-update.pl`

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/872f0d97b53f1c9aeab642c7ea143102ba633b57 this feature is available on `develop`. If you'd like to test it, please feel free. It will be part of the next release. 

Thanks again for suggesting it!

**Comment by cmhughes** [comment]
This is part of 3.4.2, which I'll get uploaded to ctan tonight. Thanks!

**Comment by beantowel** [comment]
Hello, I'm using latexindent from texlive
```
>>> latexindent --version
3.8, 2020-03-21
>>> which latexindent
/usr/local/texlive/2020/bin/x86_64-linux/latexindent
```
But it seems failed to indent the algpseudocode commands.
[test.txt](https://github.com/cmhughes/latexindent.pl/files/5554185/test.txt)
The output is
```
>>> latexindent test.txt                                                                                  beantowel@beantowel-Latitude
\documentclass{article}
% General document formatting
\usepackage[margin=0.7in]{geometry}
\usepackage[parfill]{parskip}
\usepackage[utf8]{inputenc}

% Related to math
\usepackage{amsmath,amssymb,amsfonts,amsthm}
% algorithm
\usepackage{algorithm,algpseudocode}

\begin{document}
\begin{algorithm}
	\caption{test indent}
	\begin{algorithmic}
		\If{True}
		\State This should have indentation
		\EndIf
	\end{algorithmic}
\end{algorithm}
\end{document}% 
```
I wonder if there is anything wrong or should I use some custom settings?

**Comment by cmhughes** [comment]
Hello, thanks for this.

Please post what your desired/expected output is....

I assume that you want it to indent between the If and End statement...? If so, please see https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-special2 and see if that helps :)

**Comment by beantowel** [comment]
Thanks!

Yes, i would like the _\\State_ line indent. I tried to use a local setting file  [.indentconfig.txt](https://github.com/cmhughes/latexindent.pl/files/5554500/default.indentconfig.txt) and use the command `latexindent test.txt  -l=.indentconfig.yaml`, but the output doesn't change.

Also, I wonder why this was not the default behavior instead of using a custom configuration?

**Comment by cmhughes** [comment]
Apologies for the delay.

How about the following
```yaml
specialBeginEnd:
    If:
        begin: '\\If'
        middle: '\\ElsIf'
        end: '\\EndIf'
        lookForThis: 1
    specialBeforeCommand: 1
```
from your file, this gives me
```tex
\documentclass{article}
% General document formatting
\usepackage[margin=0.7in]{geometry}
\usepackage[parfill]{parskip}
\usepackage[utf8]{inputenc}

% Related to math
\usepackage{amsmath,amssymb,amsfonts,amsthm}
% algorithm
\usepackage{algorithm,algpseudocode}

\begin{document}
\begin{algorithm}
	\caption{test indent}
	\begin{algorithmic}
		\If{True}
			\State This should have indentation
		\EndIf
	\end{algorithmic}
\end{algorithm}
\end{document}
```
