### ISSUE TITLE
fineTuning

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#113]
I wonder if it's worth exploring a field called (something like) `fineTuning` which would allow users to specify all the different constructions in the various different reg exps. 

For example, it might look something like
```
fineTuning:
      environmentName:
           - [a-z]
           - [A-Z]
           ...
      UnnamedBracesBracketsFollow:
          - ','
         - '\{'
     ...
```
Perhaps each one of these should have an 'amalgamate' field?...

**Comment by cmhughes** [comment]
Part of this should be customization of `betterFullStop`.

**Comment by cmhughes** [comment]
The double back slash regex should be included in this: https://github.com/cmhughes/latexindent.pl/issues/106, unless there's another way to have it customised somehwhere else....

**Comment by cmhughes** [comment]
Stuff between arguments in `Command.pm` should be part of this.

**Comment by cmhughes** [comment]
verbatim environments and filecontents

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/d27ef47df121ded91ba30b547c05b74a7e2e5927 this feature is implemented and documented. Explicitly, this has introduced the following to `defaultSettings.yaml`:

```
# fineTuning allows you to tweak the internal pattern matching that 
# is central to latexindent.pl
fineTuning:
    environments:
      name: '[a-zA-Z@\*0-9_\\]+' 
    ifElseFi:
      name: '@?if[a-zA-Z@]*?' 
    commands:
      name: '[+a-zA-Z@\*0-9_\:]+?'
    keyEqualsValuesBracesBrackets:
      name: '[a-zA-Z@\*0-9_\/.\h\{\}:\#-]+?'
      follow: '(?:(?<!\\)\{)|,|(?:(?<!\\)\[)'
    NamedGroupingBracesBrackets:
      name: '[0-9\.a-zA-Z@\*><]+?'
      follow: '\h|\R|\{|\[|\$|\)|\('
    UnNamedGroupingBracesBrackets: 
      follow: '\{|\[|,|&|\)|\(|\$'
    arguments:
      before: '(?:#\d\h*;?,?\/?)+|\<.*?\>'
      between: '_|\^|\*'
    modifyLineBreaks:
      betterFullStop: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
      doubleBackSlash: '\\\\(?:\h*\[\h*\d+\h*[a-zA-Z]+\h*\])?'
      comma: ','
```
