### ISSUE TITLE
paragraphsStopAt for verbatim

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#125]
I think this field needs updating to account for `verbatim` code blocks; something like:
```
paragraphsStopAt:
            environments: 1
            verbatim: 1
            commands: 0
            ifElseFi: 0
            items: 0
            specialBeginEnd: 0
            heading: 0
            filecontents: 0
            comments: 0
```
See the documentation folder for demonstrations of this, particularly with reference to `commandshell`.
