### ISSUE TITLE
Sentence indent settings from listing 269: incorrect new placement of %

### ISSUE THREAD

**Issue by kiryph** [cmhughes/latexindent.pl#129]
Consider following latex file
```tex
Xx xxxxxxxx, xxx xxxxxxxx xxxxxxxxxx, xxxxxxxxxx xxxxxxxxxxx xxxxxxxx xx x
  xxxxxxxx xx xxxx xx xxxxxxx \enquote{xxxxxx xxxx xxxxxxxxx}%
\cite{XxxxxXxXx:xxxx}.
Xxxx x xxxxxxxx xx xxxxxx \emph{xxxxxxx} \cite{XxxxxXxXx:xxxx} xxx xx
  xxxxxxxx xxxxxxxxxxxxx xx x xxxxxxxx \emp{Xxxxxxx'x xxxxx}.
```

```
❯ latexindent --version
3.5, 2018-08-13

❯ cat localSettings-lst269.yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: "  "
    textWrapOptions:
        columns: 78
```

### Current Output
```
❯ latexindent demo.tex -m -l=localSettings-lst269.yaml -w
```
```tex
Xx xxxxxxxx, xxx xxxxxxxx xxxxxxxxxx, xxxxxxxxxx xxxxxxxxxxx xxxxxxxx xx x
  xxxxxxxx xx xxxx xx xxxxxxx \enquote{xxxxxx xxxx xxxxxxxxx}
\cite{XxxxxXxXx:xxxx}.
%
Xxxx x xxxxxxxx xx xxxxxx \emph{xxxxxxx} \cite{XxxxxXxXx:xxxx} xxx xx
  xxxxxxxx xxxxxxxxxxxxx xx x xxxxxxxx \emp{Xxxxxxx'x xxxxx}.
```
As you can see the comment character has been moved which should not happen by default.
Also `\cite{XxxxxXxXx:xxxx}.` should be indented by two spaces. See expected output

### Expected Output
```tex
Xx xxxxxxxx, xxx xxxxxxxx xxxxxxxxxx, xxxxxxxxxx xxxxxxxxxxx xxxxxxxx xx x
  xxxxxxxx xx xxxx xx xxxxxxx \enquote{xxxxxx xxxx xxxxxxxxx}%
  \cite{XxxxxXxXx:xxxx}.
Xxxx x xxxxxxxx xx xxxxxx \emph{xxxxxxx} \cite{XxxxxXxXx:xxxx} xxx xx
  xxxxxxxx xxxxxxxxxxxxx xx x xxxxxxxx \emp{Xxxxxxx'x xxxxx}.
```

The documentation describes probably this behavior in Listings 209 and 210 (v3.5).
However, this actually changes the way this document is typeset.
Is there a switch to keep the comment at the end of a line?

Grepping the default file did not really help:
```
❯ cat /usr/local/texlive/2018/texmf-dist/scripts/latexindent/defaultSettings.yaml | grep -v '^#' | grep -B 9 comment

noAdditionalIndent:
    myexample: 1
    mydefinition: 1
    problem: 1
    exercises: 1
    mysolution: 1
    foreach: 0
    widepage: 1
    comment: 1
--
        textWrapSentences: 0
        sentenceIndent: ""
        sentencesFollow:
            par: 1
            blankLine: 1
            fullStop: 1
            exclamationMark: 1
            questionMark: 1
            rightBrace: 1
            commentOnPreviousLine: 1
--
        paragraphsStopAt:
            environments: 1
            verbatim: 1
            commands: 0
            ifElseFi: 0
            items: 0
            specialBeginEnd: 0
            heading: 0
            filecontents: 0
            comments: 0
```

The settings `noAdditionalIndent: comment:1`, `sentencesFollow:commentOnPreviousLine: 1`, and `paragraphsStopAt:comments: 0` do not seem to be the right ones.
