### ISSUE TITLE
Sentence indent settings from listing 269: display math within or at the end of a sentence

### ISSUE THREAD

**Issue by kiryph** [cmhughes/latexindent.pl#131]
Equations are part of sentences. For example, see this screenshot from Feller on Probability Theory:

![screen shot 2018-08-27 at 15 19 23](https://user-images.githubusercontent.com/371756/44663761-b43f1880-aa11-11e8-8cd5-4e4c86d01e84.png)

This is true for all books, articles, ... which use equations.

### Expected Format of LaTeX Code
 ```tex
Thus
   \begin{equation*}
     P\{A_1 \cup A_2\} = \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
   \end{equation*}

The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
   least one among $n$ events can be computed by a formula analogous to (7.4),
   derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
   terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
   \begin{equation}
     P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
   \end{equation}
   holds.
In the special case where the events $A_1, A_2, \ldots$ are mutually
```

### Current Behavior
```tex
❯ latexindent demo3.tex -m -l=localSettings-lst269.yaml -w
Thus \begin{equation*} P\{A_1 \cup A_2\} =
	  \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
\end{equation*}

The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
  least one among $n$ events can be computed by a formula analogous to (7.4),
  derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
  terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
\begin{equation} P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
	  \end{equation} holds.
```
Is it possible to configure latexindent to handle this?

**Comment by kiryph** [comment]
I have extended the configuration in the yaml file
```yaml
❯ cat localSettings-display-math-in-sentence.yaml
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
        equation*:
            BeginStartsOnOwnLine: 1
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 1
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: "  "
    textWrapOptions:
        columns: 78
```

```tex
❯ latexindent demo.tex -m -l=localSettings-display-math-in-sentence.yaml -w
Thus
\begin{equation*}
	P\{A_1 \cup A_2\} =
	  \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
\end{equation*}
The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
  least one among $n$ events can be computed by a formula analogous to (7.4),
  derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
  terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
\begin{equation}
	P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
\end{equation}
holds.
```

However, the indentation is missing.

**Comment by cmhughes** [comment]
Have you tried setting removeSentenceLineBreaks to 0?

**Comment by kiryph** [comment]
I tried now. The result looks 
```tex
Thus
  \begin{equation*}
	  P\{A_1 \cup A_2\} =
	  \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
\end{equation*}

  The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
  least one among $n$ events can be computed by a formula analogous to (7.4),
  derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
  terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
\begin{equation}
	  P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
\end{equation}
  holds.
```

So, no it does not do what I want.

Also the documentation sounds like that I want to keep this enabled

> When operating upon sentences latexindent.pl will, by default, remove internal linebreaks as `removeSentenceLineBreaks` is set to 1. Setting this switch to 0 instructs latexindent.pl not to do so.

This is illustrated in Listing 234 (v3.5).

**Comment by cmhughes** [comment]
I think you'll need to adjust the sentenceEndsWith field. I'll hope to give
some details.soon.

**Comment by cmhughes** [comment]
This is interesting, thanks a lot!

If I start with

`myfile.tex`
-
```
Thus
  \begin{equation*}
   P\{A_1 \cup A_2\} =
   \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
   \end{equation*}

The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
  least one among $n$ events can be computed by a formula analogous to (7.4),
  derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
  terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
\begin{equation}
   P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
   \end{equation}
  holds.
```
and 

`localSettings.yaml`
-
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 0
        textWrapSentences: 1
        sentenceIndent: "  "
        sentencesEndWith:
            betterFullStop: 0
            other: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?:\h*\R*(?:\\end\{equation\*\})?)(?!(?:[a-z]|[A-Z]|\-|\,|[0-9]))'
    textWrapOptions:
        columns: 78
```

and run 
```
latexindent -m -w -l myfile.tex
```
then I receive
```
Thus
  \begin{equation*}
   P\{A_1 \cup A_2\} =
   \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
   \end{equation*}

The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
  least one among $n$ events can be computed by a formula analogous to (7.4),
  derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
  terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
\begin{equation}
   P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
   \end{equation}
  holds.
```

The expected output would indent the `equation*` and `equation` environment and body correctly.

The reason for this is that the sentence objects do not search for child objects. 

I hadn't considered that anyone would use this feature like this, but it's clearly not working as expected in this circumstance. 

I think I need to label this as a bug, and re-work some of the internals. Let me think about it, and I'll return to it soon.
