### ISSUE TITLE
verbatim environments with* are not recognized

### ISSUE THREAD

**Issue by dzklaim** [cmhughes/latexindent.pl#138]
adding environments with a star like equation* to **verbatimEnvironments** does not work.

Is it possible to use regular expressions to define verbatimEnvironments?

**Comment by cmhughes** [comment]
Thanks for this; definitely a bug. 

The following
```
before text \begin{equation*}
  first line
        second line
     third line
   \end{equation*} 
   after text
```
with the yaml
```
verbatimEnvironments:
    equation*: 1
```
should mean that `equation*` would be treated as verbatim. Currently this isn't true.

Workaround
===
For the above example, you can use:
```
specialBeginEnd:
    displayMath:
        begin: '\\begin\{equation\*\}'
        end: '\\end\{equation\*\}'
        lookForThis: verbatim
```
