### ISSUE TITLE
Add blank line before every section marker?

### ISSUE THREAD

**Issue by alok** [cmhughes/latexindent.pl#146]
I want something like 

```
\section
...
```
to always have a blank line inserted between if there isn't one already. I looked at the `modifyLineBreaks` settings but wasn't able to figure it out.

**Comment by cmhughes** [comment]
Please provide examples of what your code looks like *before* and what you would like it to look like *after*.

**Comment by cmhughes** [comment]
This is not possible with the current implementation of `latexindent`. 

If you started with 
```
\section{introduction} a sentence
```
then we could produce
```
\section{introduction}

a sentence
```
using 
```
modifyLineBreaks:
    mandatoryArguments:
        RCuBFinishesWithLineBreak: 3
```

I'm not in a position to say that I can take this on. It would mean the full development of a new `polyswitch`; furthermore, every single one of the core regular expressions would need overhauling, which would represent an absolutely massive task. Sorry about this.

**Comment by cmhughes** [comment]
A work around is to run `latexindent` twice, as follows:

`alok1.yaml`
-
```
modifyLineBreaks:
    mandatoryArguments:
        section:
            RCuBFinishesWithLineBreak: -1

```
and

`alok2.yaml`
-
```
modifyLineBreaks:
    mandatoryArguments:
        section:
            RCuBFinishesWithLineBreak: 3

```
and then run
```
latexindent -m -o=+-mod1 -l=alok1.yaml myfile.tex
latexindent -m -l=alok2.yaml myfile-mod1.tex
```
and you'll receive your desired output.
