### ISSUE TITLE
one sentence per line, sentences beginning with {\it Word} doesn't get marked as a sentence

### ISSUE THREAD

**Issue by goretkin** [cmhughes/latexindent.pl#151]
I have not played around with the options very much yet, so this might already be the case, but perhaps there should be a list of environments that are allowed to begin a sentence. For example `{\it`, or `$`, for sentences like `{\it John} did it, not me` or `$x$ becomes small`.

**Comment by goretkin** [comment]
Before:

```
{\it Coverage} problems are one kind.  {\it Exploration} problems are another kind.
```

desired after

```
{\it Coverage} problems are one kind.
{\it Exploration} problems are another kind.
```

given the following yaml config

```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 0
        sentenceIndent: ""
        sentencesFollow:
            par: 1
            blankLine: 1
            fullStop: 1
            exclamationMark: 1
            questionMark: 1
            rightBrace: 1
            commentOnPreviousLine: 1
            other: 0
        sentencesBeginWith:
            A-Z: 1
            a-z: 0
            other: 0
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 1
            exclamationMark: 1
            questionMark: 1
            other: 0
```

**Comment by cmhughes** [comment]
Thanks for this. I haven't tested it yet, but how about using the following within `
sentencesBeginWith`

```
other: '\{\\it\h*[A-Z]'
```

**Comment by goretkin** [comment]
Thanks,  I will give it a try. I  actually did not realize that `other` took in a regex, I thought it was 0 or 1.

Do you think there may be a more general solution, that would also have sentences starting in math mode be detected as sentences? For example

```
The variable $x$ is four. $x+1$ is more.
```

**Comment by cmhughes** [comment]
Yes, that should be ok; you can use | to represent 'or'. Give it a go and
let me know if you can't get it working :)

**Comment by cmhughes** [comment]
When I start with

`tmp.tex`
-

```
{\it Coverage} problems are one kind.  {\it Exploration} problems are
another kind. \emph{Navigation} is yet another kind. $x+1$ is more.
```

and the `YAML`:

```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            A-Z: 1
            a-z: 0
            other: '\{\\it\h*[A-Z]|\\emph\{|\$'
indentRules:
   kind.: ""
```
and run
```
latexindent.pl -l=goretkin.yaml -m tmp.tex
```
then I receive the following
```
{\it Coverage} problems are one kind.
{\it Exploration} problems are another kind.
\emph{Navigation} is yet another kind.
$x+1$ is more.
```
I hope this is as you wish :)
