### ISSUE TITLE
environments not being indented

### ISSUE THREAD

**Issue by goretkin** [cmhughes/latexindent.pl#152]
```
\begin{figure} \begin{center}
  \subfloat[] { \includegraphics[width=0.20\textwidth]{figs/mockup_wide_turn.png} } \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } \end{center}

	\caption{(a) Testing one. Two three. Four five. }

\end{figure}
```

I think I am missing some configuration, but at least by default the above source does not get indented as I expected. (It mostly stays the same, except for two tab characters before the first `\subfloat`

**Comment by cmhughes** [comment]
Could you post what you expect?

**Comment by goretkin** [comment]
I don't expect anything exactly, but I did expect the \subfloat environment to be indented:

```
\begin{figure}
    \begin{center}
        \subfloat[] { \includegraphics[width=0.20\textwidth]{figs/mockup_wide_turn.png} }
        \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } 
        \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } 
        \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
    \end{center}
    \caption{(a) Testing one. Two three. Four five. }
\end{figure}
```

**Comment by cmhughes** [comment]
Take a look at

BeginStartsOnOwnLine
And

CommandStartsOnOwnLine

See
https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#poly-switches-for-other-code-blocks

**Comment by cmhughes** [comment]
When I start with 

`tmp.tex`
-
```
\begin{figure} \begin{center}
  \subfloat[] { \includegraphics[width=0.20\textwidth]{figs/mockup_wide_turn.png} } \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } \subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} } \end{center}

	\caption{(a) Testing one. Two three. Four five. }

\end{figure}
```

and the following `YAML`:

`goretkin.yaml`
-
```
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
    commands:
        CommandStartsOnOwnLine: 1
```
and run the command:
```
latexindent.pl -l=goretkin.yaml -m tmp.tex -o=+-mod1
```
then I receive 

`tmp-mod1.tex`
-

```
\begin{figure}
	\begin{center}
		\subfloat[] {
			\includegraphics[width=0.20\textwidth]{figs/mockup_wide_turn.png} }
		\subfloat[] {
			\includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
		\subfloat[] {
			\includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
		\subfloat[] {
			\includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
	\end{center}

	\caption{(a) Testing one. Two three. Four five. }

\end{figure}
```
If you use the `YAML`

`goretkin1.yaml`
-

```
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
    commands:
        subfloat:
            CommandStartsOnOwnLine: 1
commandCodeBlocks:
    stringsAllowedBetweenArguments:
      - 
        amalgamate: 0
```
and run the following command
```
latexindent.pl -l=goretkin1.yaml -m tmp.tex -o=+-mod2
```
then I receive:

`tmp-mod2.tex`
-

```
\begin{figure}
	\begin{center}
		\subfloat[] { \includegraphics[width=0.20\textwidth]{figs/mockup_wide_turn.png} }
		\subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
		\subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
		\subfloat[] { \includegraphics[width=0.25\textwidth]{figs/mockup_wide_turn.png} }
	\end{center}

	\caption{(a) Testing one. Two three. Four five. }

\end{figure}
```

I hope this helps :)
