### ISSUE TITLE
Abbreviation dot and non-breaking space

### ISSUE THREAD

**Issue by mlep** [cmhughes/latexindent.pl#153]
I noticed that
`(Fig.~\ref{dummy18})`
is transformed into
`(Fig.`
`~\ref{dummy18})`.
I expect the line to stay untouched (`(Fig.~\ref{dummy18})`) as the  dot after `Fig` is not the end of a sentence.

Compared to the default file of Latexindent v 3.5, 2018-08-13, I changed one line (see attached file):
`manipulateSentences: 1
`
[defaultSettings-Fig.yaml.txt](https://github.com/cmhughes/latexindent.pl/files/2595810/defaultSettings-Fig.yaml.txt)

**Comment by mlep** [comment]
I am not sure to understand...
By "all of the settings", do your mean more than the Yaml file (included in my initial post)? What more?

**Comment by cmhughes** [comment]
I guess I was thinking of the settings you've changed.

 I'll take a look at your file and see if I can strip it down to a mwe.

**Comment by mlep** [comment]
In the settings, I changed only one line from
`manipulateSentences: 0`
to
`manipulateSentences: 1`

**Comment by cmhughes** [comment]
Thanks for this, and sorry for the delay.

When I start with `myfile.tex`
```
Here is a sentence (Fig.~\ref{dummy18})
```
and the following `YAML` file, `mlep.yaml`
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            betterFullStop: 0
            other: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|\,|[0-9]|~))/'
```
and run 
```
latexindent.pl -l=mlep.yaml -m myfile.tex
```
then I receive
```
Here is a sentence (Fig.~\ref{dummy18})
```

I appreciate that this isn't at all obvious! :) I took the above regexp from `Sentence.pm` and it's the default part of `betterFullStop` and appended with `|~`.

One of the goals of https://github.com/cmhughes/latexindent.pl/issues/113 is to make this kind of thing a little easier. 

I think there's a perl module that puts reg exps into slightly more human readable format, which might be part of the development of that issue. 

I hope this helps, let me know! :)

**Comment by mlep** [comment]
Sorry for being so long in replying, and thank you for considering my case.
Indeed, with `mlep.yaml`,
````Here is a sentence (Fig.~\ref{dummy18})````
remains identical.

However, when considering my context (I want to get one sentence per line), this is not the case anymore.
Considering the input
````
Here is a sentence (Fig.~\ref{dummy18}). Here is another sentence (Fig.~\ref{dummy19}).
````
 I would like to get the output
````
Here is a sentence (Fig.~\ref{dummy18}).
Here is another sentence (Fig.~\ref{dummy19}).
````
Using the `mlep.yaml` file, the output is identical to the input (i.e. the two sentences remain on the same line).
It looks like the `mlep.yaml` file breaks the behavior of `betterFullStop`, but I cannot figure out why...

**Comment by cmhughes** [comment]
I've made a small change to `mlep.yaml` in the below
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            betterFullStop: 0
            other: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```
Starting with 

mwe.tex
-
```
Here is a sentence (Fig.~\ref{dummy18}). Here is another sentence (Fig.~\ref{dummy19}).
```
and running
```
latexindent.pl -l=mlep -m mwe.tex -o=mwe-output.tex
```
then I receive

mwe-output.tex
-
```
Here is a sentence (Fig.~\ref{dummy18}).
Here is another sentence (Fig.~\ref{dummy19}).
```
Is this as you would like?
