### ISSUE TITLE
replacement mode switch: replace strings/regex using

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#155]
I'd like to explore a switch that would employ replacement strings/regular expressions. 

Possible YAML interface:
```
replacements:
 -
    before: '\\arraycolsep=\d+pt'
    after: ''
    type: regex
  -
    before: '\\begin\{figure\}\h*(?!\[)'
    after: '\begin{figure}[!htpb] '
-
    before: '_\mathbb{R}'
    after: '_{\mathbb{R}}'
  -
    before: '\item[\phantom{Distributivity}]\quad'
    after: '\item '
  -
    before: '\quad(\text{'
    after: '\quad\text{('
```

and within the `perl`:
```

sub particular_body_substitutions{
	return unless $masterSettings{particularBodySubs};
	my @particularSubs = @{$masterSettings{particularBodySubs}};

	foreach ( @particularSubs ){
	   my $before = qq{${$_}{before}};
	   my $after = qq{${$_}{after}};
	   my $index_match = index($body, $before);
	   while ( $index_match != -1 ) {
	         substr ($body, $index_match, length($before), $after ); 
	   	 $index_match = index($body, $before);
	   }
	}
}

sub regexp_body_substitutions{
	return unless $masterSettings{regExpBodySubs};
	my @regExpSubs = @{$masterSettings{regExpBodySubs}};

	foreach ( @regExpSubs ){
 	   $body =~ s/${$_}{before}/${$_}{after}/sg;
	}
}

```
