### ISSUE TITLE
Tabular and Array should be consistent by default

### ISSUE THREAD

**Issue by rommeswi** [cmhughes/latexindent.pl#161]
Structurally, arrays and tabular environments are similar and should be treated similarly. I expected the default behavior to be like in a config as this:

lookForAlignDelims:
   tabular: 
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 1
      multiColumnGrouping: 0
      alignRowsWithoutMaxDelims: 1
      spacesBeforeAmpersand: 1
      spacesAfterAmpersand: 1
      justification: "left"
   array: 
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 1
      multiColumnGrouping: 0
      alignRowsWithoutMaxDelims: 1
      spacesBeforeAmpersand: 1
      spacesAfterAmpersand: 1
      justification: "left"
 
The same should be true for matrices, tabularx etc.

**Comment by cmhughes** [comment]
Hello!
Thanks for this. 

Referencing Section 5 and the discussion just after Listing 28 of the documentation (https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html) the settings for `tabular`, `array`, `tabularx`, etc as given in `defaultSettings.yaml` are equivalent:

```
lookForAlignDelims:
   tabular: 
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 1
      multiColumnGrouping: 0
      alignRowsWithoutMaxDelims: 1
      spacesBeforeAmpersand: 1
      spacesAfterAmpersand: 1
      justification: "left"
   tabularx:
      delims: 1
   longtable: 1
   tabu: 1
   array: 1
```

It's important that `defaultSettings.yaml` serves a teaching purpose, as well as a functional purpose; this is why I've demonstrated the different formats that it can take. 

The above is equivalent to, but it does not demonstrate the flexibility of the fields available. 

```
lookForAlignDelims:
   tabular: 1
   tabularx: 1
   longtable: 1
   tabu: 1
   array: 1
```

I encourage you to make your own settings! Perhaps you could copy the above settings into, for example, `rommeswi.yaml` and then call
```
latexindent.pl -l=rommeswi.yaml myfile.tex
```

I hope this helps!
Chris
