### ISSUE TITLE
Sentence ending with an abbreviation

### ISSUE THREAD

**Issue by goretkin** [cmhughes/latexindent.pl#164]
Thanks to https://github.com/cmhughes/latexindent.pl/issues/153, the one-sentence-per-line can respect `~`, and not introduce a newline. I wonder if the opposite version of this would help in the case below: don't remove a newline after a ".", even if it looks like it belongs to an abbreviation.

```
This is a phrase e.g. a sentence.
Common abbreviations like e.g., i.e., etc. etc. are recognized.
But what about an abreviation at the end of a sentence?
An example will follow. It's hard to handle everything etc.
Thanks for listening.
```

turns into

```
This is a phrase e.g. a sentence.
Common abbreviations like e.g., i.e., etc. etc. are recognized.
But what about an abreviation at the end of a sentence?
An example will follow.
It's hard to handle everything etc. Thanks for listening.
```

and
<img width="503" alt="image" src="https://user-images.githubusercontent.com/581043/58928929-929e5a80-8722-11e9-8e7c-de40f7c0e3af.png">

turns into

<img width="339" alt="image" src="https://user-images.githubusercontent.com/581043/58928922-887c5c00-8722-11e9-9171-0a385610c8a8.png">

(the red indicates a trailing space).

using this configuration file
```
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
    commands:
        CommandStartsOnOwnLine: 0
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 0
        sentenceIndent: ""
        sentencesFollow:
            par: 1
            blankLine: 1
            fullStop: 1
            exclamationMark: 1
            questionMark: 1
            rightBrace: 1
            commentOnPreviousLine: 1
            other: 0
        sentencesBeginWith:
            A-Z: 1
            a-z: 0
            other: '\{\\it\h*[A-Z]|\\emph\{|\$'
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 1
            exclamationMark: 1
            questionMark: 1
            other: 0
```
