### ISSUE TITLE
textWrapOptions and equation enviroment

### ISSUE THREAD

**Issue by technic** [cmhughes/latexindent.pl#177]
```
modifyLineBreaks:
    textWrapOptions:    
        columns: 100
```
Does it supposed to work together? In my case commands inside equation environments often got split into two lines and latex gets invalid.

**Comment by technic** [comment]
Thanks for quick answer
I run with `latexindent test.tex -m -l=config.yaml -o out.tex`

config.yaml
```yaml
noAdditionalIndent:
    equation: 1
    multiline: 1

modifyLineBreaks:
    textWrapOptions:    
        columns: 50
        preserveBlankLines: 1
        perCodeBlockBasis: 1
        environments:
            document: 1
            equation: 1
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 0
```

test.tex
```latex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}

\begin{document}

\begin{equation}
    \left[\hat{\mathcal{C+B+A}},\hat{H}_\mathrm{ABC}+\hat{U}\right]=x+y+z
\end{equation}

\begin{equation}
    \left\{\hat{\mathcal{C+B+A}},\hat{H}_\mathrm{ABC}+\hat{U}\right\}=x+y+z
\end{equation}

\end{document}
```

out.tex
```latex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}

\begin{document}

\begin{equation}
\left[\hat{\mathcal{C+B+A}},\hat{H}_\mathrm{ABC}+\hat{U}\right]=x+y+z
\end{equation}

\begin{equation}
\left\{\hat{\mathcal{C+B+A}},\hat{H}_\mathrm{ABC}+\hat{U}\r
ight\}=x+y+z
\end{equation}

\end{document}
```

In the output file there is a problem: `\right\{` command is split in the middle between two lines, I would expect it to split at places where it is safe, i.e. before or after command.

Also I've noticed that it only happened with the second equation, and I do not understand why. 

*Version*
latexindent -v: 3.7.1, 2019-09-07
