### ISSUE TITLE
modifyLineBreaks: Missing period moves commends to the end of next sentence

### ISSUE THREAD

**Issue by Sh3Rm4n** [cmhughes/latexindent.pl#183]
I've noticed, when I am missing a period, the comments on the following paragraph will be moved to the end of the first section.

If I add the missing period, the comments will stay at the end of the sentence.

I know this is not the intended way to use this, as I've not ended my sentence.
However, it is a minor inconvenience.

<details><summary>latex example</summary>
<p>

```tex
Here is some text \textbf{not} ending without a period

% 'test'
% 'test'
% 'test'
% 'test'
Here is a paragraph, some text to make it longer longer longer longer longer
longer longer longer longer longer. Starting with a new sentence. And another one.

And here is a sentence, which will show another use case.
% Here is comment between to sentences in a paragraph
And the last sentence, which is again a little longer longer longer longer longer longer longer longer longer longer.
```

</p>
</details>

<details><summary>config</summary>
<p>

```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: "    "
        sentencesFollow:
            blankLine: 1
            commentOnPreviousLine: 1
    textWrapOptions:
        columns: 79
```

</p>
</details>

command
```console
latexinden -m -l indent-config.yaml
```
This is the generated output using the config and commend from above.

<details><summary>output</summary>
<p>

```tex
Here is some text \textbf{not} ending without a period

    Here is a paragraph, some text to make it longer longer longer longer longer
    longer longer longer longer longer.% 'test'% 'test'% 'test'% 'test'
Starting with a new sentence.
And another one.

And here is a sentence, which will show another use case.
% Here is comment between to sentences in a paragraph
And the last sentence, which is again a little longer longer longer longer
    longer longer longer longer longer longer.
```

</p>
</details>

And here I've added the missing period on the previously formatted text, and run
`latexindent` again.

I did this mostly, because I was curious, if the comments are moved again. But
certainly, this was not what I was expecting. From the point of view of the
previously formatted text, this worked as I would expect.

<details><summary>output with period</summary>
<p>

```tex
Here is some text \textbf{not} ending without a period.

Here is a paragraph, some text to make it longer longer longer longer longer
    longer longer longer longer longer.% 'test'% 'test'% 'test'% 'test'
Starting with a new sentence.
And another one.

And here is a sentence, which will show another use case.
% Here is comment between to sentences in a paragraph
And the last sentence, which is again a little longer longer longer longer
    longer longer longer longer longer longer.
```

</p>
</details>

**Comment by cmhughes** [comment]
Thanks a lot, I'll take a look soon and get back to you.

**Comment by Sh3Rm4n** [comment]
To specify the problem, the "output with period" format was created with the
previously formatted text (see "output") and not the original one.

**Comment by cmhughes** [comment]
Great. So is everything contained in the original post? If not, feel free to edit :)

**Comment by Sh3Rm4n** [comment]
I've edited the post to make it more clear how I generated the examples.

**Comment by cmhughes** [comment]
Thanks for this, and sorry for the delayed response. 

I'm not sure that I completely understand the question, for which I apologise. If I can try to clarify some points that occur to me:

- `Here is some text \textbf{not} ending without a period` from the point of view of `latexindent.pl` is *not* a sentence
- in your example, from the point of view of `latexindent.pl`, the whole of
```
Here is some text \textbf{not} ending without a period

% 'test'
% 'test'
% 'test'
% 'test'
Here is a paragraph, some text to make it longer longer longer longer longer
longer longer longer longer longer. 
``` 
is *one* sentence, which is why the comments get moved to the end of it.

If you'd like to change the behaviour of the sentence routine, then you might like to look at, for example, `sentencesEndWith`, as detailed in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#sentencesendwith

**Comment by Sh3Rm4n** [comment]
Yeah, you are right. This is not a sentence, or worded another way, the whole example is only one sentence. So latexindent formats the example as expected. I was only surprised about the way the comments were moved. As they are now appended as one line at the end of the sentence. But I really have no suggestion in mind to handle that in another way. 

But to rephrase the original issue in another way:

Is it possible to configure latexindent in a way, so it does join both paragraphs into one sentence, even though they are not two separate sentences delimited by a period. 

 The reason for this is, that latex itself treats both sentences as separate paragraphs, because of the empty line following the first line. This would simplify my workflow, as I use this tool regularly while writing text. While writing and breaking the undo/revert chain this is quite tedious to revert to the original state. 

However, it is usable as is. I just have to remember putting a period to the end of the unfinished sentence before formatting :)

**Comment by cmhughes** [comment]
Can you try setting `preserveBlankLines: 0 `in your configuration and re-run it?

**Comment by Sh3Rm4n** [comment]
Does not make a difference :(

**Comment by cmhughes** [comment]
I can confirm that setting `preserveBlankLines: 0 ` does not make a difference, which is not desirable. It **should** have fixed this.

It looks like the text wrap routine switches `preserveBlankLines: 1 ` and I can't remember why this was necessary at the moment. It feels to me that this is a bug. 

The desired behaviour would be that setting `preserveBlankLines: 0 ` would change the output from
```
modifyLineBreaks:
    preserveBlankLines: 0
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: "    "
        sentencesFollow:
            blankLine: 1
            commentOnPreviousLine: 1
    textWrapOptions:
        columns: 79
```
and 
```
Here is some text \textbf{not} ending without a period

% 'test'
% 'test'
% 'test'
% 'test'
Here is a paragraph, some text to make it longer longer longer longer longer
longer longer longer longer longer.
```
into 
```
Here is some text \textbf{not} ending without a period Here is a paragraph, 
some text to make it longer longer longer longer longer longer longer longer longer longer. % 'test' % 'test' % 'test' % 'test'
Here is a paragraph, some text to make it longer longer longer longer longer
longer longer longer longer longer.
```

I'll return to this after trying to resolve some of the issues ahead of it.

**Comment by cmhughes** [comment]
My apologies for the delay.

As of https://github.com/cmhughes/latexindent.pl/commit/ab13f34db6ed23de890df84a79b901ffe017c73c if I start with

```tex
Here is some text \textbf{not} ending without a period

% 'test'
% 'test'
% 'test'
% 'test'
Here is a paragraph, some text to make it longer longer longer longer longer
longer longer longer longer longer.
```
and the settings
```YAML
modifyLineBreaks:
    preserveBlankLines: 0
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
    textWrapOptions:
        columns: 79
```
then the output is
```tex
Here is some text \textbf{not} ending without a period	    Here is a
paragraph, some text to make it longer longer longer longer longer longer
longer longer longer longer.
% 'test'% 'test'% 'test'% 'test'
```
I hope that this is as desired. 

https://github.com/cmhughes/latexindent.pl/commit/ab13f34db6ed23de890df84a79b901ffe017c73c will be part of the next release, which I hope will be fairly soon.
