### ISSUE TITLE
modifyLineBreak: Breaks line in the middle of a command

### ISSUE THREAD

**Issue by Sh3Rm4n** [cmhughes/latexindent.pl#184]
If I format a file, which contains a command, which itself is long enough
to exceed the maximum column width, `latexindent` will break the command
in the middle of a word.

This is a problem, as now, this document can't be compiled anymore.

**Latex Example**:

```tex
\begin{figure}[H]
    \centering
    \includegraphics[width=0.8\linewidth]{a/real/long/path_to/an-image/i/want/to/include.png}
\end{figure}
```

**Formatted Output**:

```tex
\begin{figure}[H]
        \centering

        \includegraphics[width=0.8\linewidth]{a/real/long/path_to/an-image/i/want/to/i
                nclude.png}
\end{figure}
```

In addition to that an empty line is inserted after `\centering`. I don't
know where this comes from. But this doesn't bother me so much. The
document will compile just fine.

Configuration:

```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: "    "
        sentencesFollow:
            blankLine: 1
            commentOnPreviousLine: 1
    textWrapOptions:
        columns: 79
```
