### ISSUE TITLE
One Sentence Per Line + Indented Hard Wraps

### ISSUE THREAD

**Issue by mikeroher** [cmhughes/latexindent.pl#185]
Hi - I was wondering if latexindent was capable of applying the following format:

* 80 characters per line hard wrapped
* each sentence is on its own line
* only the first word of each sentence is indented, all other words are non-indented.
* paragraphs are separated by blank line

I have tried the following configuration but it does not seem to result in the above format.
```yaml
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    oneSentencePerLine:
        manipulateSentences: 1 
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: "\t"
```

An example of what I'm trying to accomplish is below.

BEFORE (lines are softwrapped in editor):

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur ac nulla eu ultrices integer ac mi et ligula pulvinar rutrum nam tristique sed tortor eget iaculis vamus aliquam venenatis neque. In hac habitasse platea dictumst. Pellentesque sit amet magna non tortor porta rhoncus eget non diam interdum et malesuada fames ac ante ipsum primis in faucibus. Cras sit amet placerat lacus ut porttitor eleifend velit ac laoreet nullam ac finibus erat, a auctor metus. 
```

AFTER:
```
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Donec consectetur ac nulla eu ultrices integer ac mi et ligula pulvinar rutrum 
nam tristique sed tortor eget iaculis vamus aliquam venenatis neque in hac 
habitasse platea dictumst. 
    Pellentesque sit amet magna non tortor porta rhoncus eget non diam interdum et 
malesuada fames ac ante ipsum primis in faucibus. 
    Cras sit amet placerat lacus ut porttitor eleifend velit ac laoreet nullam ac 
finibus erat, a auctor metus.
```

Thanks!

**Comment by cmhughes** [comment]
Not sure! Will try to take a look soon....

**Comment by mikeroher** [comment]
Thank you very much!

**Comment by cmhughes** [comment]
If you use the following YAML:
```
modifyLineBreaks:
    textWrapOptions:
         columns: 80
    oneSentencePerLine:
        manipulateSentences: 1 
        removeSentenceLineBreaks: 1
        textWrapSentences: 1

replacements:
  -
    substitution: s/(^[A-Z])/\t$1/mg
    when: after
```
and run the script using the `-r` switch, e.g.
```
latexindent.pl -m -r -l=myyaml.yaml  myfile.tex
```
then you receive:
```
	Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	Donec consectetur ac nulla eu ultrices integer ac mi et ligula pulvinar rutrum
nam tristique sed tortor eget iaculis vamus aliquam venenatis neque.
	In hac habitasse platea dictumst.
	Pellentesque sit amet magna non tortor porta rhoncus eget non diam interdum et
malesuada fames ac ante ipsum primis in faucibus.
	Cras sit amet placerat lacus ut porttitor eleifend velit ac laoreet nullam ac
finibus erat, a auctor metus.
```

Is this as you would like?
