### ISSUE TITLE
Size of tab for textwrap   and   additional leading indentation

### ISSUE THREAD

**Issue by sv-dl** [cmhughes/latexindent.pl#191]
Hallo,

I try to configure latexindent to my needs and stuck at two problem:

### 1)  Respect Indentation for text wrap
```
# I using indentation by tabs
defaultIndent: "\t\t\t"
# and having text wrapping activated
modifyLineBreaks:
    textWrapOptions:
        #  (in production columns will be larger)
        columns: 8
        huge: overflow
```

It seems that the indentation does not count for wordwrap: `\t\t\t4 6 8 a c` will be wrapped after '8'
**sample.tex**
```
\begin{foo}
4 6 8 a c 
\end{foo}
```

**results**

```
\begin{foo}
                        4 6 8 a
                        c
\end{foo}
```

I would like to set the tab width to a certain value

**test.yaml**
```
defaultIndent: "\t\t\t"
modifyLineBreaks:
    textWrapOptions:
        columns: 8
        huge: overflow
        tabwidth: 2
        respectIndentForWrap: 1
```
which should break the after '4' (three tab indentations counts each two charakters + '4' + space = 8 characters)
```
\begin{foo}
                        4
                        6
                        8
                        a
                        c
\end{foo}
```

Maybe I miss something but I don't find a option to achieve this behavior.

### 2) Additional leading indentation
I want to use latexindent to format snippets of code out of my text editor. Since the snippets may reside inside an environment or something else they may need a indentation.

It would be nice to have a option to take the leading whitespaces of the first line as initial indentation which is prepend to all indentations created by latexindent.

**example.tex**
```
\begin{foo}
  \begin{itemize}
\item foo
\end{itemize}
\end{foo}
```
If I only format the itemize environment I want to keep the initial indentation of (here) two whitespaces from the line `  \begin{itemize}`:
`head -4 example.tex | tail -3 | latexindent.pl` should result in something like
```
12345
  \begin{itemize}
      \item foo
  \end{itemize}
12345
```
(The number-line are only to visualize the indentation.)

I've no idea how to achieve this. Actually latexindent seams to consume all leading white spaces and produce it's own indentation starting at level 0.

 I would be grateful for any suggestions.
   sv-dl
