### ISSUE TITLE
[Question] Problem with OneSentencePerLine and Items

### ISSUE THREAD

**Issue by lambtho12** [cmhughes/latexindent.pl#197]
Hi,
I have been struggling all day without really finding how to do this. Can you help?
I have the following tex example:
```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}

The Trent EconoPac aero-derivative stationary gas turbine specifications in SLS/ISA conditions are:
\begin{itemize}
\item Compressor pressure ratio: $\pi_c = 35$
\item Exhaust mass flow: $\dot{m}_t = 351~lb/s$
\item Exhaust gas temperature: $EGT =725^\circ F$
\item Power output: $\mathcal{P} = 51.20~MW$
\item Heat rate: $HR = 8210 BTU/kWh$
\item Fuel lower heating value (assuming this is regular gasoline fuel): $\Delta H_f = 47110~kJ/kg$
\item Compressor isentropic efficiency: $\eta_{s,c} = 0.88$
\item Combustion chamber efficiency: $\eta_{cc} = 1$
\end{itemize}
Determine the power absorbed by friction and accessories $\mathcal{P}_{f,a}$ in the gas turbine as accurately as possible.

\end{document}
```
And I use this localSettings.yaml
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1     
        textWrapSentences: 1
    textWrapOptions:
        columns: 70
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
    items:
        ItemStartsOnOwnLine: 1
        ItemFinishesWithLineBreak: 0

```

I would like the output to look like this
```tex
The Trent EconoPac aero-derivative stationary gas turbine
specifications in SLS/ISA conditions are:
\begin{itemize}
    \item Compressor pressure ratio: $\pi_c = 35$
    \item Exhaust mass flow: $\dot{m}_t = 351~lb/s$
    \item Exhaust gas temperature: $EGT =725^\circ F$
    \item Power output: $\mathcal{P} = 51.20~MW$
    \item Heat rate: $HR = 8210 BTU/kWh$
    \item Fuel lower heating value (assuming this is regular 
          gasoline fuel): $\Delta H_f = 47110~kJ/kg$
    \item Compressor isentropic efficiency: $\eta_{s,c} = 0.88$
    \item Combustion chamber efficiency: $\eta_{cc} = 1$
\end{itemize}
Determine the power absorbed by friction and accessories
$\mathcal{P}_{f,a}$ in the gas turbine as accurately as 
possible.
```

But this is very far from what I currently get. I do not know exactly what to tweak or if it is even possible. I guess the problem is that the `:` before the environment do not close the sentence and that the individual items do no end with a punctuation. But even when I put a `;` at the end of each item and a `.` after the very last one, the formatting is not done as I would like.

**Comment by cmhughes** [comment]
Thanks for this. I'll take a look over the weekend and post back.

**Comment by cmhughes** [comment]
I think the problem is that the "sentences" within your `\item` commands do not have a punctuation mark at their end. 

Not to worry, you can tweak the settings of `latexindent` to tell it that it should end sentences with `\item` by using the following:
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1     
        textWrapSentences: 1
        sentencesEndWith:
            other: '\\item'
    textWrapOptions:
        columns: 70
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
    items:
        ItemStartsOnOwnLine: 1
        ItemFinishesWithLineBreak: -1
```

Using these settings give:
```
The Trent EconoPac aero-derivative stationary gas turbine
specifications in SLS/ISA conditions are:
\begin{itemize}
	\item Compressor pressure ratio: $\pi_c = 35$
	\item Exhaust mass flow: $\dot{m}_t = 351~lb/s$
	\item Exhaust gas temperature: $EGT =725^\circ F$
	\item Power output: $\mathcal{P} = 51.20~MW$
	\item Heat rate: $HR = 8210 BTU/kWh$
	\item Fuel lower heating value (assuming this is regular gasoline fuel):
	      $\Delta H_f = 47110~kJ/kg$
	\item Compressor isentropic efficiency: $\eta_{s,c} = 0.88$
	\item Combustion chamber efficiency: $\eta_{cc} = 1$
\end{itemize}
Determine the power absorbed by friction and accessories
$\mathcal{P}_{f,a}$ in the gas turbine as accurately as possible.
```
which I believe is as you would like....?

Let me know!
