### ISSUE TITLE
oneSentencePerLine:manipulateSentences:1 does not work well in texts with abreviations

### ISSUE THREAD

**Issue by alanlivio** [cmhughes/latexindent.pl#199]
```
My Program. skills.
```
Goes to
```
My Program.
skills.
```

**Comment by cmhughes** [comment]
This is an interesting test case. The output is as expected. It should be customisable through sentences end with: https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#sentencesendwith

I'll see if I can do anything with it.

**Comment by cmhughes** [comment]
My sincere apologies for my delayed response, I've been slammed with stuff at work and haven't had the head space until now to look at this.

You can tweak the `betterFullStop` regular expression as follows

alanlivio.yaml
-

```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1

fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:\h*[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```

and then run
```
latexindent.pl -m myfile.tex -l alanlivio.yaml
```
to receive
```
My Program. skills.
```
