### ISSUE TITLE
oneSentencePerLine:manipulateSentences:1 does not work well in \textit{et. al.}

### ISSUE THREAD

**Issue by alanlivio** [cmhughes/latexindent.pl#200]
The following text does not break lines.
```
XXX et. al. does ...
```
But let consider a similar one that uses \textit:
```
XXX \textit{et. al.} does ...
```
The break lines goes like that:
```
XXX \textit{et.
 al.} does ...
```

**Comment by cmhughes** [comment]
Thanks for this, and my apologies for my delayed response. 

As in https://github.com/cmhughes/latexindent.pl/issues/199 we can tweak the `fineTuning` field (see https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html#lst-finetuning)

`alanlivio.yaml`

```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1

fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:\h*[a-z]|[A-Z]|\-|~|\,|[0-9]|\}))'
```

and run 
```
latexindent.pl -m myfile.tex -l alanlivio.yaml
```
gives
```
XXX et. al. does

XXX \textit{et. al.} does
```
