### ISSUE TITLE
Preserve line breaks around certain characters commands

### ISSUE THREAD

**Issue by tobiasdiez** [cmhughes/latexindent.pl#204]
For long equations, I sometimes put the equals sign on a new line to make the logical structure of the equation more clear
```
\begin{equation}
	a
	= b
	= c
	= d
\end{equation}
```
Is there a way to preserve this structure with the `-m` switch on? Currently the equation content is condensed into one long line.
Similarly, I would like to preserve the line breaks in the following example as well:
```
\begin{equation}
	a
	\qquad
	\qquad
	b
\end{equation}
```

Finally, it would be nice to add line breaks automatically as well. What I have in mind is to break aligned equations at their alignment character.
```
\begin{split}
	a
	&= b
	&= c
	&= d
\end{split}
```
(btw: is there a reason why `split` from amsmath is not added to `lookForAlignDelims` by default?)

**Comment by cmhughes** [comment]
Hello!
Thanks for this. Could you post your yaml file? The -m switch shouldn't
change your original file by default.

**Comment by tobiasdiez** [comment]
Sure:
```
lookForAlignDelims:
  equationcd: 1
  split: 1

indentAfterItems:
  thmenumerate: 1

indentRules:
  item: "\t"

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1 
  environments:
    DBSFinishesWithLineBreak: 1
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    equationcd:
      DBSFinishesWithLineBreak: 2
```
This configuration works for me except for the two issues that I've reported now.

(I should also remark that I'm using the latexindent version shipped with texlive 2017)
