### ISSUE TITLE
Force line break after certain commands

### ISSUE THREAD

**Issue by tobiasdiez** [cmhughes/latexindent.pl#205]
I would like to always put the `\label` command on its own line, e.g.
```
\begin{equation}
	\label{my label}
	a
\end{equation}
```
Currently this gets condensed to
```
\begin{equation}
	\label{my label} a
\end{equation}
```

**Comment by cmhughes** [comment]
As in your other question, please can you post your yaml file? The -m
switch shouldn't do this by default.

**Comment by tobiasdiez** [comment]
Sure:
```
lookForAlignDelims:
  equationcd: 1
  split: 1

indentAfterItems:
  thmenumerate: 1

indentRules:
  item: "\t"

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1 
  environments:
    DBSFinishesWithLineBreak: 1
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    equationcd:
      DBSFinishesWithLineBreak: 2
```
(I should also remark that I'm using the latexindent version shipped with texlive 2017)
