### ISSUE TITLE
\begingroup ... \engdroup prevents indentation inside an env

### ISSUE THREAD

**Issue by alusiani** [cmhughes/latexindent.pl#207]
Hi,

\begingroup \endgroup seems to be special as it prevents any indentation in the environment where it is present.  The following details what happens:

```latex
\documentclass[aspectratio=141,9pt,xcolor={svgnames,x11names},fleqn,usepdftitle=false,bookmarks=true]{beamer}

\begin{frame}[plain]
  \begin{center}
    \bgroup
      aa
    \egroup
  \end{center}
\end{frame}

\begin{frame}[plain]
\begin{center}
\begingroup
  aa
\endgroup
\end{center}
\end{frame}

\end{document}
```

I have some minimal user configuration, as follows:

```yaml
# Default value of indentation
defaultIndent: "  "

indentRules:
  myenvironment: "  "
  anotherenvironment: "  "
  chapter: ""
  section: ""
  item: ""
  myitem: ""
  ifElseFi: "  "

specialBeginEnd:
  begingroup:
    begin: '\\begingroup'
    end: '\\endgroup'
    lookForThis: 1
  bgroup:
    begin: '\\bgroup'
    end: '\\egroup'
    lookForThis: 1
```

I use texlive-latexindent-20180414-37.fc30.noarch on Fedora 30.

Thanks for latexindent.pl, it is a very useful tool!

Best regards,
\--
Alberto Lusiani
