### ISSUE TITLE
EndFinishesWithLineBreak + lookForAlignDelims adds extra blank line

### ISSUE THREAD

**Issue by pgregory9** [cmhughes/latexindent.pl#209]
Thank you for this wonderful tool! I've been working on this for a couple of days and I hope I have not missed something in the documentation.

I would like this:
```
before words
\begin{myenv}
	body of myenv
\end{myenv}
between words
\begin{myother}{cc}
	1 & 2 \\ 3 & 4 \\
\end{myother}
after words
```
to go to this:
```
before words

\begin{myenv}
	body of myenv
\end{myenv}

between words

\begin{myother}{cc}
	1 & 2 \\
        3 & 4 \\
\end{myother}

after words
```
To make that work I need `myother` in `lookForAlignDelims` and `DBSFinishesWithLineBreak: 1`, but what that results in is: 

```
% myenv is fine, the rest is

between words

\begin{myother}{cc}% in lookForAlignDelims
	1 & 2 \\
	3 & 4 \\

\end{myother}

after words
```
There is an extra blank space between `3 & 4 \\` and `\end{myother}`! Note that this happens whether
`EndFinishesWithLineBreak:` is 2, 3, or 4. 1 doesn't do it, but then I don't get the blank space between `\end{myother}` and `after words` 

Here is my mySettings.yaml:
```
lookForAlignDelims:
    myother: 1

modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 4
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 4
        DBSFinishesWithLineBreak: 1
```
The extra blank line goes away if I remove `myother` from `lookForAlignDelims`, but then  `DBSFinishesWithLineBreak` doesn't work.

Am I missing a setting in `lookForAlignDelims` that I can change?

Many thanks, and let me know if you need more info!
Paul

**Comment by cmhughes** [comment]
Thanks for this, Paul.

I'll take a detailed look soon, but on first review I think it's a bug with DBSFinishesWithLineBreak and the routine behind it. If you change the value of the switch to 0 does that affect the output?

I'll get back to you once I know more, hopefully soon.

**Comment by pgregory9** [comment]
The only difference with `DBSFinishesWithLineBreak: 0` is we don't get the line breaks after DBS (as expected), but we still DO get the extra blank line:

```
\begin{myother}{cc}
	1 & 2 \\ 3 & 4 \\

\end{myother}
```
So the key seems to be that `myother` is in or not in `lookForAlignDelims`.

Thanks,
P

**Comment by cmhughes** [comment]
That's very helpful, thanks. I'll report back.

**Comment by cmhughes** [comment]
I see now that you have specified
```
EndFinishesWithLineBreak: 4
```
With reference to https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#poly-switches this means that you've specified that `\end{<environment name>}`  as 

> *add blank line mode ; a blank line will be added before or after the <part of thing> under 
> consideration, even if the <part of thing> is already on its own line.*

If you change `EndFinishesWithLineBreak` to be `1` then the `\end{myother}` is not changed:
```
lookForAlignDelims:
    myother: 1

modifyLineBreaks:
    environments:
        EndFinishesWithLineBreak: 1
```

However, changing it to `2` or `3` should also leave this unaffected, but it doesn't and gives output that is undesired. 

As a note to myself, to reproduce, start with the following
```
\begin{myother}{cc}% in lookForAlignDelims
	1 & 2 \\
	3 & 4 \\
\end{myother}

\begin{other}
  asdasd
  asdadsa
\end{other}
```
and the following YAML
```
lookForAlignDelims:
    myother: 1

modifyLineBreaks:
    environments:
        EndFinishesWithLineBreak: 2
```
and compare the output between `myother` and `other`.
