### ISSUE TITLE
Add option for checking if the file was modified

### ISSUE THREAD

**Issue by augustjanse** [cmhughes/latexindent.pl#215]
Some beautifiers have an option to check if a file would have modified if running normally. See [black](https://github.com/psf/black):
```
  --check                         Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted. Return code 123 means
                                  there was an internal error.
```

This would be cool to have. For lack of it, it would be nice to know the best way to check in a build server if a file is formatted already without it.

**Comment by cmhughes** [comment]
This sounds like a nice idea, thanks very much. I'll add the feature
request label.

Development is slow at the moment, for which I apologise.

**Comment by augustjanse** [comment]
Thanks! Any idea for a workaround?

**Comment by cmhughes** [comment]
Do you have version control on your build server...? If so, you might be
able to run some kind of "diff" operation....?

**Comment by augustjanse** [comment]
Yeah. Looks like this `.travis.yml` works for me:

```.travis.yml
os: linux
dist: focal
language: perl
perl:
  - "5.30"
install:
 - sudo apt-get -y install texlive-extra-utils
 - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
 - curl -L http://cpanmin.us | perl - App::cpanminus
 - cpanm YAML::Tiny
 - cpanm File::HomeDir
 - cpanm Unicode::GCString
 - cpanm Log::Log4perl
 - cpanm Log::Dispatch::File
script: 
 - |
   for file in *.tex
   do
     latexindent -o delta_$file $file
     diff $file delta_$file # Returns 1 if different
   done
```

Had to set `focal` and install `texlive-extra-utils` to get a recent version, or else it wouldn't work.

**Comment by cmhughes** [comment]
Possibly helpful

https://stackoverflow.com/a/8177756/1091649

**Comment by cmhughes** [comment]
Btw: Log4Perl no longer required :)

**Comment by cmhughes** [comment]
I'm hoping to get to this over the coming months, if my workload allows. 

You've given the following, which is very helpful, thank you:
```
--check                         Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted. Return code 123 means
                                  there was an internal error.
```
Are there any ways that this switch should work, or any other features that it would do?

**Comment by augustjanse** [comment]
Cool! I don't use LaTeX much these days, but I would use this feature for CI if I did. It seems to me that different formatters tend to use different flags, but the main thing would be the return code. A better reference is probably [prettier](https://prettier.io/docs/en/cli.html#--check), which also uses `--check`:
```
prettier --check "src/**/*.js"
```

**Comment by cmhughes** [comment]
Great, that's helpful, many thanks :)

**Comment by cmhughes** [comment]
I'm hopeful to get to this in the near future. Watch this space for updates and possibly request for feedback! :)

**Comment by cmhughes** [comment]
For my reference see https://github.com/cmhughes/latexindent.pl/issues/283

**Comment by SoongJr** [comment]
+1, the return code is the important bit, yes. I'd also add as a wish that it prints the differences like diff would, or more sophisticated: file name, line and column and the differences within that line/block of code.
Simple diff would be fine for me, that's what it currently looks like in my own CI (creates a formatted temp file and then diffs that temp with the actual tex file).

**Comment by SoongJr** [comment]
And in case this helps anyone: Here's my current github workflow, including lint with chktex and compile with latexmk: https://github.com/SoongJr/akad-latex-vorlage/blob/main/.github/workflows/main.yml
```yaml
name: Build LaTeX document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  file: vorlage # root tex file to compile (without extension)
                # If you renamed your root tex file - originally "vorlage.tex" - (e.g. to get a nice PDF name),
                # simply also adjust the filename here.
jobs:
  list_tex_files:
    # list all .tex files in this repo and save them in a variable that can be used by other jobs as input for their matrix (so they run one job on each tex file)
    outputs:
      matrix: ${{ steps.list-files.outputs.matrix }}
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: list .tex files in this repo
        id: list-files
        # print each filename (relative path) as an element of a JSON list, github can parse this into setting output variable "matrix"
        run: |
          printf "::set-output name=matrix::{\"include\":["
          find . -name "*.tex" -exec printf "{\"file\":\"{}\"}," \;
          printf "]}\n"
  check_formatting:
    # run latexindent on each tex file and diff the result with committed file. Produces failure of the formatting is not applied properly.
    needs: [list_tex_files]
    runs-on: [ubuntu-latest]
    strategy:
      # read the output variable of the list_tex_files job
      matrix: ${{fromJson(needs.list_tex_files.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2  # Checks-out repository under $GITHUB_WORKSPACE
      - name: Apply indentation rules to ${{ matrix.file }}
        # first format the content of the file and save this into a temporary file 
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}
          compiler: latexindent
          args: --local -o formatted.tex    # configuration is read from local files in git repository root. you can adjust here if your file is somewhere else.
      - name: Check for correct formatting
        # now compare this temporary file, which is correctly formatted, with the actual file. Any differences will be printed in screen and fail this job.
        uses: dante-ev/latex-action@latest
        with:
          root_file: formatted.tex
          compiler: diff
          args: ${{ matrix.file }}
          
  lint_latex:
    # use chktex to scan the whole project for style issues that could later lead to problems
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2  # Checks-out repository under $GITHUB_WORKSPACE
      - name: Lint ${{ env.file }}.tex
        # run chktex the same way LaTeX-Workshop extension of Visual Studio code would
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.file }}.tex
          compiler: chktex
          args: -eall -n22 -n30 -e16 -q   # make sure to adjust these arguments to match your IDE's (or vice versa)
  build_latex:
    # use latexmk to create a PDF, it can detect whether to run biber and via a .latexmkrc file you can also tell it to run makeglossaries or other steps.
    # PDF is then uploaded so it shows up on the summary page of the succeeded action run.
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2  # Checks-out repository under $GITHUB_WORKSPACE
      - name: Compile ${{ env.file }}.tex
        # run latexmk on the given file
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.file }}.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
      - name: Upload ${{ env.file }}.pdf
        # upload exactly this generated PDF (will show up at the bottom of each run of this github action)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file }}.pdf
          path: ${{ env.file }}.pdf
          if-no-files-found: error
```
