### ISSUE TITLE
Custom environment-like commands support

### ISSUE THREAD

**Issue by psttf** [cmhughes/latexindent.pl#218]
Is there a way to declare custom "environment-like" commands so that code between these commands will be indented? An example would be `collectexercises` and `collectexercisesstop` commands from the xsim package.

I tried to use `specialBeginEnd` but it failed. Using the `config.yaml` file on the `test.tex` file does not indent anything.

- `config.yaml` 
```yaml
specialBeginEnd:
    collectexercises:
        begin: '\\collectexercises'
        end: '\\collectexercisesstop'
        lookForThis: 1
```
- `test.tex` 
```tex
\collectexercises{}
\input{text/tasks_theory}
\input{text/tasks_practice_predicates}
\input{text/tasks_practice_propositions}
\input{text/tasks_practice_sets}
\collectexercisesstop{}
```

It is interesting that if I remove the closing brace or all braces from `\collectexercises{}` and `\collectexercisesstop{}` the contents become indented. Is this a conflict between detecting `specialBeginEnd` and other code blocks (e.g. commands with arguments between `{}`)?

**Comment by cmhughes** [comment]
Hi there!
Thanks for this.

I think that you'll need `specialBeforeCommand: 1` to help with this, see the description following https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-specialafter.

So, if you modify your `config.yaml` to be:
```
specialBeginEnd:
    collectexercises:
        begin: '\\collectexercises'
        end: '\\collectexercisesstop'
        lookForThis: 1
    specialBeforeCommand: 1
```
then you should receive:
```
\collectexercises{}
	\input{text/tasks_theory}
	\input{text/tasks_practice_predicates}
	\input{text/tasks_practice_propositions}
	\input{text/tasks_practice_sets}
\collectexercisesstop{}
```
Is this as you'd like? Let me know if not :)
