### ISSUE TITLE
Option to start \begin and \end environment on new lines

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#22]
I think this needs an option to put `\begin{<name>}` and `\end{<name>}` on thier own line. 

For example, it would be nice to translate

```																			    
\begin{minipage}{.5\textwidth}
body\end{minipage}
```

into

```																			   
\begin{minipage}{.5\textwidth}
    body
\end{minipage}
```

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/8329629b9300d5dd906381bfb2a72475e3b9ba00 this feature is on the way to being full implemented for environments. 

Currently, the `yaml` looks like this:

```
modifyLineBreaks:
    everyBeginStartsOnOwnLine: 1
    everyBodyStartsOnOwnLine: 1
    everyEndStartsOnOwnLine: 1
    everyEndFinishesWithLineBreak: 1
    equation*:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```

I think I'd prefer it to be:

```
modifyLineBreaks:
    environments:
        everyBeginStartsOnOwnLine: 1
        everyBodyStartsOnOwnLine: 1
        everyEndStartsOnOwnLine: 1
        everyEndFinishesWithLineBreak: 1
        equation*:
           BeginStartsOnOwnLine: 1
           BodyStartsOnOwnLine: 1
           EndStartsOnOwnLine: 1
           EndFinishesWithLineBreak: 1
     ifElseFi:
        everyBeginStartsOnOwnLine: 1
        everyBodyStartsOnOwnLine: 1
        everyEndStartsOnOwnLine: 1
        everyEndFinishesWithLineBreak: 1
        ifnum:
           BeginStartsOnOwnLine: 1
           BodyStartsOnOwnLine: 1
           EndStartsOnOwnLine: 1
           EndFinishesWithLineBreak: 1
   etc.....
```

This would allow the user to specify linebreak choices globally on a per-object basis (as well as a per-named object).
