### ISSUE TITLE
One cell per line

### ISSUE THREAD

**Issue by homocomputeris** [cmhughes/latexindent.pl#231]
Hi!

It would be great to be able to format tables is such a way that every cell is put on a separate line.
For example,
```latex
\begin{tabular}{ll}
a & a \\
a & a \\
\end{tabular}
```
would become
```latex
\begin{tabular}{llll}
    a 
    & a
    \\ % using DBSStartsOnOwnLine: 1
    & a 
    & a
\end{tabular}
```
There are three main reasons:

- it's much easier to `diff` cells than rows, especially when using git
- when table rows are long, it's more meaningful to break lines at `&` than to put them in a middle of a line and then hard wrap
- using Knuth's style (`&` at the beginning) makes it easier not to lose `&`

**Comment by cmhughes** [comment]
Thanks for this.

There's not an 'out of the box' solution, but perhaps we could construct something using the replacement switch....?  What do you think?

**Comment by homocomputeris** [comment]
Thanks for the answer!
Unforturately, I know nothing about Perl. As a straightforward solution, I'd suggest break lines before every `&`

**Comment by cmhughes** [comment]
If I start with the file, `myfile.tex`

```tex
\begin{tabular}{ll}
a&b\\
c &d \\
\end{tabular}

\begin{tabular}{ll}
a\&b\\
c &d \\
\end{tabular}

\begin{tabular}{ll}
a
&b\\
c &d \\
\end{tabular}
```
and the YAML `new-cell.yaml`
```YAML
replacements:
  -
    substitution: |-
      s/(.)(?<!\\)&/$1\n&/mg

lookForAlignDelims:
   tabular: 
      spacesBeforeAmpersand: 0
```
and run the command
```
latexindent.pl myfile.tex -r -l new-cell.yaml
```
then I receive the following output
```tex
\begin{tabular}{ll}
	a
	& b \\
	c
	& d \\
\end{tabular}

\begin{tabular}{ll}
	a\&b \\
	c
	& d  \\
\end{tabular}

\begin{tabular}{ll}
	a
	& b \\
	c
	& d \\
\end{tabular}
```

Is this as you would like?

**Comment by homocomputeris** [comment]
Yes, it seems so.
Unfortunately, ATM I can't test it with other table environments.

**Comment by cmhughes** [comment]
The settings I've provided shouldn't be restricted to other environments.

Is this resolved for the  moment?

**Comment by homocomputeris** [comment]
Given
```yaml
replacements:
  -
    substitution: |-
      s/(.)(?<!\\)&/$1\n&/mg

lookForAlignDelims:
   tabular:
      spacesBeforeAmpersand: 0

modifyLineBreaks:
    environments:
      DBSStartsOnOwnLine: 1
      DBSFinishesWithLineBreak: 1
      BeginStartsOnOwnLine: 1
      BodyStartsOnOwnLine: 1
```
the document
```latex
\documentclass[]{article}
\usepackage{tabularx,xltabular}

\begin{document}
\begin{tabularx}{\linewidth}{XX} a & b \\ c & d\end{tabularx}

\begin{xltabular}{\linewidth}{XX}a & b \\ c & d\end{xltabular}

\begin{tabular}{ll}a & b \\c & d\end{tabular}
\end{document}
```
after the 1st run becomes
```latex
\begin{document}
\begin{tabularx}{\linewidth}{XX} a
	 & b
	\\
	c
	 & d\end{tabularx}

\begin{xltabular}{\linewidth}{XX}a
	& b \\ c
	& d\end{xltabular}

\begin{tabular}{ll}a
	& b
	\\
	c
	& d\end{tabular}
\end{document}
```
and, after the 2nd, it becomes
```latex
\documentclass[]{article}
\usepackage{tabularx,xltabular}

\begin{document}
\begin{tabularx}{\linewidth}{XX} a

	 & b
	\\
	c

	 & d\end{tabularx}

\begin{xltabular}{\linewidth}{XX}a

	& b \\ c

	& d\end{xltabular}

\begin{tabular}{ll}a

	& b
	\\
	c

	& d\end{tabular}
\end{document}
```

I would expect the result to be idempotent and environment-independent. And `BodyStartsOnOwnLine: 1` seems not to work.

**Comment by cmhughes** [comment]
If we use the following YAML, say `cmh.yaml`
```YAML
replacements:
  -
    substitution: |-
      s/([a-zA-Z0-9])\h*(?<!\\)&/$1\n&/mg

lookForAlignDelims:
   tabular:
      spacesBeforeAmpersand: 0

modifyLineBreaks:
    environments:
      DBSStartsOnOwnLine: 1
      DBSFinishesWithLineBreak: 1
      BeginStartsOnOwnLine: 1
      BodyStartsOnOwnLine: 1
    mandatoryArguments:
        tabularx: 
            LCuBStartsOnOwnLine: -1
            RCuBFinishesWithLineBreak: 1 
        xltabular: 
            LCuBStartsOnOwnLine: -1
            RCuBFinishesWithLineBreak: 1 
        tabular: 
            LCuBStartsOnOwnLine: -1
            RCuBFinishesWithLineBreak: 1 
```
and run 
`
latexindent.pl -r -m -l cmh.yaml myfile.tex
`
then we receive
```tex
\documentclass[]{article}
\usepackage{tabularx,xltabular}

\begin{document}
\begin{tabularx}{\linewidth}{XX}
	a
	 & b
	\\
	c
	 & d\end{tabularx}

\begin{xltabular}{\linewidth}{XX}
	a
	& b \\ c
	& d\end{xltabular}

\begin{tabular}{ll}
	a
	& b
	\\
	c
	& d\end{tabular}
\end{document}
```

This uses the idea of `partnering poly-switches` as detailed in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#partnering-bodystartsonownline-with-argument-based-poly-switches.  In particular, 

- `RCuBFinishesWithLineBreak: 1 ` says to finish right curly brace `}` with a line break
-  `LCuBStartsOnOwnLine: -1` says that left curly brace `{` should *not* start on its own line

Is this as you would like?
