### ISSUE TITLE
How not to break lines at the end of arguments?

### ISSUE THREAD

**Issue by homocomputeris** [cmhughes/latexindent.pl#232]
Hi!

When `oneSentencePerLine` is used, commands which contain text, e.g.
```latex
\todo{Really?}
\todo{Really.}
```
become
```latex
\todo{Really?
}
\todo{Really.
}
```
and the `RCuB` brace is detached, which makes no sense.

How can this be fixed?

**Comment by cmhughes** [comment]
Thanks for this. If I use the following, say `cmh.yaml`

```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 0
            questionMark: 0
            other: '(?:\.\)(?!\h*[a-z]))|(?:\?\})|(?:\.\})|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```
and your original file, say `myfile.tex` and use the command
```
latexindent.pl -m myfile.tex -l cmh.yaml
```
then I receive the output:
```tex
Sentence \todo{Really?}
Sentence \todo{Really.}
```
Does this help? Further information at https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-multiple-sentences6-mod2
