### ISSUE TITLE
Line break wrongly and inconsistenly removed after \section{}

### ISSUE THREAD

**Issue by homocomputeris** [cmhughes/latexindent.pl#233]
Hi! I've found a very peculiar bug. Latexindent removes a line break and moves a comment.

The document
```latex
\documentclass[draft]{report}
\usepackage{graphicx}

\begin{document}
\chapter{Chapter}
Text.

\begin{figure}[h]
    \centering
    \includegraphics[width=\linewidth]{picture.png}
    \caption{Caption}
    \label{fig:label}
    \begin{tabular}{l}
        Legend -- entry
        \\
        Legend -- entry
    \end{tabular}
\end{figure}

% see the line below
\section{Section}
List:
\begin{description}
    \item[one] is the first.
\end{description}

% compare with this one
\section{Section}
List:
\begin{description}
    \item[one] is the first.
\end{description}

\end{document}
```
becomes
```latex
\documentclass[draft]{report}
\usepackage{graphicx}

\begin{document}
\chapter{Chapter}
Text.

\begin{figure}[h]
    \centering
    \includegraphics[width=\linewidth]{picture.png}
    \caption{Caption}
    \label{fig:label}
    \begin{tabular}{l}
        Legend -- entry
        \\
        Legend -- entry
    \end{tabular}
\end{figure}

\section{Section} List:
\begin{description}
    \item[one] is the first.
    % see the line below
\end{description}

% compare with this one
\section{Section}
List:
\begin{description}
    \item[one] is the first.
\end{description}

\end{document}
```
Here is the configuration file:
```yaml
onlyOneBackUp: 1

# remove trailing whitespace from all lines
removeTrailingWhitespace:
    beforeProcessing: 1
    afterProcessing: 1

# default value of indentation
defaultIndent: "    "


# modifyLineBreaks will only be searched if the -m
# switch is active
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 0
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 0
        sentenceIndent: ""
        sentencesFollow:
            par: 1
            blankLine: 1
            fullStop: 1
            exclamationMark: 1
            questionMark: 1
            rightBrace: 1
            commentOnPreviousLine: 1
            other: 0
        sentencesBeginWith:
            A-Z: 1
            a-z: 0
            other: 0
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 1
            exclamationMark: 1
            questionMark: 0
            other: 0
    textWrapOptions:
        columns: 0
        separator: ""
        perCodeBlockBasis: 0
        all: 0
        alignAtAmpersandTakesPriority: 1
        environments:
            quotation: 0
        ifElseFi: 0
        optionalArguments: 0
        mandatoryArguments: 0
        items: 0
        specialBeginEnd: 0
        afterHeading: 0
        preamble: 0
        filecontents: 0
        masterDocument: 0
    removeParagraphLineBreaks:
        all: 0
        beforeTextWrap: 0
        alignAtAmpersandTakesPriority: 1
        environments:
            quotation: 0
        ifElseFi: 0
        optionalArguments: 0
        mandatoryArguments: 0
        items: 0
        specialBeginEnd: 0
        afterHeading: 0
        preamble: 0
        filecontents: 0
        masterDocument: 0
        paragraphsStopAt:
            environments: 1
            verbatim: 1
            commands: 0
            ifElseFi: 0
            items: 0
            specialBeginEnd: 0
            heading: 0
            filecontents: 0
            comments: 0
    environments:
        DBSStartsOnOwnLine: 1
        DBSFinishesWithLineBreak: 1
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```

**Comment by cmhughes** [comment]
Is your configuration file minimal? If it can be reduced to be as minimal as possible, that would be helpful.

**Comment by homocomputeris** [comment]
That's the minimum I've got:
```yaml
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 0
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
```
which yields
```latex
\documentclass[draft]{report}
\usepackage{graphicx}

\begin{document}
\chapter{Chapter}
Text.

\begin{figure}[h]
	\centering
	\includegraphics[width=\linewidth]{picture.png}
	\caption{Caption}
	\label{fig:label}
	\begin{tabular}{l}
		Legend -- entry \\ Legend -- entry\end{tabular} \end{figure} 

\section{Section} List: \begin{description} \item[one] is the first.
	      % see the line below
\end{description}

% compare with this one
\section{Section}
List: \begin{description} \item[one] is the first.
\end{description}

\end{document}
```

It seems that it fails to recognize a new sentence after `\end{figure} \section{...}`

**Comment by cmhughes** [comment]
Thanks, that's helpful and much appreciated. I'll have a look and get back
to you.

**Comment by cmhughes** [comment]
Can you post your *desired * output as well?

**Comment by homocomputeris** [comment]
Sure. Basically, I wouldn't expect any change at all:
```latex
\documentclass[draft]{report}
\usepackage{graphicx}

\begin{document}
\chapter{Chapter}
Text.

\begin{figure}[h]
    \centering
    \includegraphics[width=\linewidth]{picture.png}
    \caption{Caption}
    \label{fig:label}
    \begin{tabular}{l}
        Legend -- entry
        \\
        Legend -- entry
    \end{tabular}
\end{figure}

% see the line below
\section{Section}
List:
\begin{description}
    \item[one] is the first.
\end{description}

% compare with this one
\section{Section}
List:
\begin{description}
    \item[one] is the first.
\end{description}

\end{document}
```

**Comment by cmhughes** [comment]
The script is behaving as expected. 

When we run the following command, using your minimal configuration file as `cmh.yaml`,
```
latexindent.pl myfile.tex -l cmh.yaml -m -tt
```
then detailed information is given into the log file, `indent.log`. In particular, we see that starting at line 209 of `indent.log`:
```log
Finding sentences...
       follows: }
       
       sentence: Text
       ends with: .
       follows: }
       
       sentence: Legend -- entry \\ Legend -- entry \end{tabular} \end{figure} LTXIN-TK-blank-line
       \section{Section} List: \begin{description} \item[one] is the first
       ends with: .
       follows: }
       
       sentence: List: \begin{description} \item[one] is the first
       ends with: .
```

In particular, you'll see that your sentence that starts with `Legend` finishes with `.` (full-stop/period); everything in between is classed as part of the body of the sentence. 

Perhaps you'd like to modify the `sentencesEndWith` field. In particular, appending the settings that we used in your other issue (https://github.com/cmhughes/latexindent.pl/issues/232) into, say, `cmh1.yaml`:

```YAML
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 0
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 0
            questionMark: 0
            other: '\\end\{tabular\}|(?:\.\)(?!\h*[a-z]))|(?:\?\})|(?:\.\})|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```
then running
```
latexindent.pl myfile.tex -l cmh1.yaml -m -tt
```
we receive
```tex
\documentclass[draft]{report}
\usepackage{graphicx}

\begin{document}
\chapter{Chapter}
Text.

\begin{figure}[h]
	\centering
	\includegraphics[width=\linewidth]{picture.png}
	\caption{Caption}
	\label{fig:label}
	\begin{tabular}{l}
		Legend -- entry \\ Legend -- entry\end{tabular}
\end{figure}

% see the line below
\section{Section}
List: \begin{description} \item[one] is the first.
\end{description}

% compare with this one
\section{Section}
List: \begin{description} \item[one] is the first.
\end{description}

\end{document}
```

Note that the `oneSentencePerLine` routine operates before any of the code blocks have been found.

Is this as you would like?
