### ISSUE TITLE
Fails to format this code

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#239]
Latexindent doesn't seem to like the following code, which it simply flattens instead of formatting properly.

```latex
\ExplSyntaxOn
\newcommand*{\fixcref}{
    % Allow spaces in `cref` command.
    \cs_set_eq:Nc \bers_cref:nn { @cref }
    \cs_generate_variant:Nn \bers_cref:nn { nx }
    \cs_set_protected:cpn { @cref } ##1 ##2
        {
            \seq_set_split:Nnn \l_bers_cref_seq { , } { ##2 }
            \bers_cref:nx { ##1 } { \seq_use:Nn \l_bers_cref_seq { , } }
        }
    \seq_new:N \l_bers_cref_seq
}
\ExplSyntaxOff
```

**Comment by cmhughes** [comment]
Interesting! I can't test this at the moment, but the first thing I'd try is using the following:
```yaml
commandCodeBlocks:
    stringsAllowedBetweenArguments:
      - 
        amalgamate: 1
      - '\#\#\d' 
```
