### ISSUE TITLE
Argument containing "\\{}" is not indented

### ISSUE THREAD

**Issue by bunder** [cmhughes/latexindent.pl#240]
latexindent 3.8.3, 2020-11-06

```
$ latexindent -y="defaultIndent: '  '" test.cls 
\def\test{
  text
}

\def\test{
\\{}
text
}
```

**Comment by cmhughes** [comment]
Try this:

```yaml
specialBeginEnd:
    specialBeforeCommand: 1
    doublebackslash:
        begin: '\\\\\{'
        end: '\} '
        lookForThis: 1
```
