### ISSUE TITLE
betterFullStop for other sentence delimiters

### ISSUE THREAD

**Issue by Konfekt** [cmhughes/latexindent.pl#243]
Could other custom sentence delimiters be included in what betterFullStop achieves for dots?

For example, the settings

```
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
      sentencesEndWith:
        other: \:
```
and input

```
This sentence \cite{tex:stackexchange} finishes here.
```

produce

```
This sentence \cite{tex:
stackexchange} finishes here.
```

where instead

```
This sentence \cite{tex:stackexchange} finishes here.
```

would have been expected.

**Comment by cmhughes** [comment]
You've specified that you'd like sentences to end with `:`, so the output you've posted is expected.....? If you can expand your example, providing the *original* and what the *desired* output, that would be helpful.

Having said that, modifying the betterFullStop routine can be done by [fineTuning](https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html), for example save the following into `Konfekt.yaml`

```yaml
fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.|:\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```
and then run
```
latexindent.pl -m -y Konfekt myfile.tex
```

**Comment by Konfekt** [comment]
The input

```
This sentence \cite{tex:stackexchange} finishes here.
```

produces

```
This sentence \cite{tex:
stackexchange} finishes here.
```

where instead

```
This sentence \cite{tex:stackexchange} finishes here.
```

would have been preferred as `:` is semantically not the end of a sentence.

However, my settings were incomplete.
Because `;` is also a sentence delimiter, according to https://github.com/cmhughes/latexindent.pl/issues/167

```
modifyLineBreaks:oneSentencePerLine: sentencesBeginWith:other: [a-z]
```

has to be added to insert a line break after a semicolon when the next non-white space letter is a lower case letter.

The proposed YAML parameter

```
--yaml="modifyLineBreaks:oneSentencePerLine:sentencesEndWith: \
       other: \:|\; ; \
modifyLineBreaks:oneSentencePerLine: sentencesBeginWith:other: [a-z] , \
fineTuning:modifyLineBreaks:betterFullStop:  '(?:\.|:\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'"
```

does not work as intended:


```
We go; this sentence \cite{tex:stackexchange} finishes here.
```

produces

```
We go; this sentence \cite{tex:stackexchange} finishes here.
```

where instead

```
We go;
this sentence \cite{tex:stackexchange} finishes here.
```

would have been preferred.

However, it seems that simply omitting the once necessary line

```
modifyLineBreaks:oneSentencePerLine: sentencesBeginWith:other: [a-z]
```

makes everyting work as desired.

That is

```
--yaml="modifyLineBreaks:oneSentencePerLine:sentencesEndWith: \
       other: \:|\;"
```

produces the preferred output.

**Comment by Konfekt** [comment]
Correction. This setting does not resolve the initial issue:

```
--yaml="modifyLineBreaks:oneSentencePerLine:sentencesEndWith: \
       other: \:|\;"
```

on

```
We go; you see: this sentence \cite{tex:stackexchange} finishes here.
```

produces

```
We go;
you see: this sentence \cite{tex:stackexchange} finishes here.
```

instead of

```
We go;
you see:
this sentence \cite{tex:stackexchange} finishes here.
```

Therefore,

```
modifyLineBreaks:oneSentencePerLine: sentencesBeginWith:other: [a-z]
```

has to be added to insert a line break after a colon `:` when the next non-white space letter is a lower case letter.
Though the discussion https://github.com/cmhughes/latexindent.pl/issues/167 was about the semicolon `;`, this setting is no longer necessary for the semicolon `;` but only for the colon `:`.

Thus, the initial issue persists.

**Comment by cmhughes** [comment]
Try this:
```yaml
fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.|:\|\;)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```

If it doesn't work as you would like, please give:
1. Original tex
2. Your yaml settings
3. Desired output

**Comment by Konfekt** [comment]
With the proposed setting, the text ist leaved unchanged; instead:

1. Original Tex
```
We go; you see: this sentence \cite{tex:stackexchange} finishes here.
```
2. Yaml settings:
```
--yaml="modifyLineBreaks:oneSentencePerLine:sentencesEndWith: \
       other: \:|\; ; \
modifyLineBreaks:oneSentencePerLine: sentencesBeginWith:other: [a-z] , \
fineTuning:modifyLineBreaks:betterFullStop:  '(?:\.|:\|\;)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'"
```
3. Expected output:
```
We go;
you see:
this sentence \cite{tex:stackexchange} finishes here.
```

**Comment by cmhughes** [comment]
Starting with your file, and using
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            a-z: 1

fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.|;|:(?![a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```
then I receive
```tex
We go;
you see:
this sentence \cite{tex:stackexchange} finishes here.
```
Is this as you would like?

**Comment by Konfekt** [comment]
Yes, the end result is as asked for, however I do not obtain it. I am using

```sh
latexindent --yaml="modifyLineBreaks:oneSentencePerLine:manipulateSentences: 1,
  modifyLineBreaks:oneSentencePerLine:sentencesBeginWith:a-z: 1,
  fineTuning:modifyLineBreaks:betterFullStop: '(?:\.|;|:(?![a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'"
```

On a sidenote, previously

```
modifyLineBreaks:oneSentencePerLine:sentencesEndWith:
  other: \;|\:
```

had to be set. This is no longer necessary or does betterFullStop override this option?

**Comment by cmhughes** [comment]
Have you tried the settings that I have provided? These are the settings I recommend for your desired output.

**Comment by Konfekt** [comment]
I think so, as  

```
latexindent --yaml="modifyLineBreaks:oneSentencePerLine:manipulateSentences: 1,
  modifyLineBreaks:oneSentencePerLine:sentencesBeginWith:a-z: 1,
  fineTuning:modifyLineBreaks:betterFullStop: '(?:\.|;|:(?![a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'"
```

uses the same settings as

```
latexindent -y Konfekt
```

with `Konfekt` reading

```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            a-z: 1

fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.|;|:(?![a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```

Or am I mistaken?
