### ISSUE TITLE
How to ingore . followed by "\ " in sentences?

### ISSUE THREAD

**Issue by newptcai** [cmhughes/latexindent.pl#246]
With the setting
```yaml
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 0
        sentencesFollow:
           other: "\)|\}"
        sentencesEndWith:
            basicFullStop: 1
```
The sentence
```
This vs.\ that is wrong.
```
becomes
```
This vs.
\ that is wrong.
```
Is there anyway to tell latexindent `.\ ` should not be considered end of a sentence?

**Comment by cmhughes** [comment]
Sorry for the delay, I'm hoping to get to this over the next few days....

**Comment by newptcai** [comment]
It's fine! This is open source project. I really appreciate that you made this.

**Comment by cmhughes** [comment]
Using the following settings
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1

fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:\\|[a-z]|[A-Z]|\-|~|\,|[0-9]))'
```
then I receive
```tex
This vs.\ that is wrong.
```
is this as you would like?
