### ISSUE TITLE
Commands of form `\iffoo{...}{...}{...}` mistaken as ifElseFi type

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#250]
original .tex code
--
```latex
\ifxetex
	foo
\else
	\ifluatex
		\ifnumgreater{2}{1}{
			bar
		}{}
	\else
	\fi
\fi
```

yaml settings
--
none

I tried to fix this behaviour with the following, but this doesn't work either.
```yaml
fineTuning:
    ifElseFi:
        name: '@?if[a-zA-Z@]*(?!\s*{)'
```

desired or expected output
--
same as original
