### ISSUE TITLE
Indentation within square brackets spanning multiple lines

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#254]
original .tex code
--
```tex
\fooa{
	<<
		/bar [
			<<
				baz
			>>
		]
	>>
}

\foob[1]{
	bar
}
```

yaml settings
--
```yaml
defaultIndent: "\t"
fineTuning:
    NamedGroupingBracesBrackets:
      name: '[0-9\.a-zA-Z@\*><\/]+?'
      follow: '\h|\R|\{|\[|\$|\)|\('
lookForAlignDelims:
    align: 0
removeTrailingWhitespace: 1
specialBeginEnd:
    specialBeforeCommand: 1
    cmh:
        begin: '/[CK]'
        end: '\['
        lookForThis: verbatim
    angledBrackets:
        begin: '\<\<'
        end: '\>\>'
        lookForThis: 1
    # squareBrackets:
    #     begin: '\['
    #     end: '\]'
    #     lookForThis: verbatim
```

actual/given output
--
```
\fooa{
	<<
		/bar [
		<<
			baz
		>>
		]
	>>
}

\foob[1]{
	bar
}
```
i.e., The contents of `\fooa` is not indented correctly (left alone), while `\foob` is fine.
Uncommenting the `squareBrackets` block creates the opposite problem: `\foob` is indented incorrectly, while `\fooa` is fine.

desired or expected output
--
same as input

**Comment by cmhughes** [comment]
This was interesting!

Using the following
```yaml
fineTuning:
    NamedGroupingBracesBrackets:
      name: '[0-9\.a-zA-Z@\*><\/]+?'
      follow: '^|\h|\R|\{|\[|\$|\)|\('
removeTrailingWhitespace: 1
specialBeginEnd:
    specialBeforeCommand: 1
    angledBrackets:
        begin: '\<\<'
        end: '\>\>'
        lookForThis: 1
noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
```
gives your desired output. 

The important lines are 
```yaml
      follow: '^|\h|\R|\{|\[|\$|\)|\('
```
which says that `namedGroupingBracesBrackets` can happen at the beginning of a string. 

The lines
```yaml
noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
```
say that the body of `namedGroupingBracesBrackets` should not receive any additional indentation. Hope this helps!
```tex
\fooa{
	<<
		/bar [
			<<
				baz
			>>
		]
	>>
}

\foob[1]{
	bar
}
```
