### ISSUE TITLE
Forest environment + math mode

### ISSUE THREAD

**Issue by jasonhan-vassar** [cmhughes/latexindent.pl#265]
Hi, so I've been using the `forest` environment and indentation behaves strangely when math mode is used inside it. Could you please help me get `latexindent.pl` to behave the same with or without math mode usage? I am using the custom settings discussed in issue #133:

```YAML
noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
    UnNamedGroupingBracesBrackets: 1
```

Here is a working example without math mode:

### Expected and Actual

```LaTeX
\begin{forest}
    parse tree
    [1
        [0.5
            [0.5
                [0.5]
                [0.5]]
            [0.5
                [0.5]
                [0.5]]
        ]
        [0.5
            [0.5
                [0.5]
                [0.5]]
            [0.5
                [0.5]
                [0.5]]
        ]
    ]
\end{forest}
```

Here is an example with math mode that does not work as intended:

### Expected

```LaTeX
\begin{forest}
    parse tree
    [$\neg (\neg P \to (Q \lor R))$
        [$\neg P \to (Q \lor R)$
            [$\neg P$ [$P$]]
            [$Q \lor R$
                [$Q$]
                [$R$]
            ]
        ]
    ]
\end{forest}
```

### Actual
```LaTeX
\begin{forest}
    parse tree
    [$\neg (\neg P \to (Q \lor R))$
    [$\neg P \to (Q \lor R)$
    [$\neg P$ [$P$]]
    [$Q \lor R$
    [$Q$]
    [$R$]
    ]
    ]
    ]
\end{forest}
```

Thanks for reading!

**Comment by jasonhan-vassar** [comment]
Here is an example that's more similar to the working example. It's a bit different than my original math mode example (note that some indentation still remains) so I thought I would include it:

### Expected
```LaTex
\begin{forest}
    parse tree
    [1
        [$0.5$
            [0.5
                [0.5]
                [0.5]]
            [0.5
                [0.5]
                [0.5]]
        ]
        [0.5
            [0.5
                [0.5]
                [0.5]]
            [0.5
                [0.5]
                [0.5]]
        ]
    ]
\end{forest}
```

### Actual
```LaTeX
\begin{forest}
    parse tree
    [1
    [$0.5$
    [0.5
    [0.5]
    [0.5]]
    [0.5
    [0.5]
    [0.5]]
    ]
    [0.5
    [0.5
        [0.5]
        [0.5]]
    [0.5
        [0.5]
        [0.5]]
    ]
    ]
\end{forest}
```

**Comment by cmhughes** [comment]
Hello!
Thanks for this. 

Is your distribution up to date? Which version of `latexindent.pl` are you using? I'm on V3.9.1, and here are the outputs that I receive, using:

jasonhan.yaml
-
```yaml
defaultIndent: ' '
noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
    UnNamedGroupingBracesBrackets: 1
```

sample code 1
-
```tex
\begin{forest}
 parse tree
 [$\neg (\neg P \to (Q \lor R))$
  [$\neg P \to (Q \lor R)$
   [$\neg P$ [$P$]]
   [$Q \lor R$
    [$Q$]
    [$R$]
   ]
  ]
 ]
\end{forest}
```

and

sample code 2
-
```tex
\begin{forest}
 parse tree
 [1
  [$0.5$
   [0.5
    [0.5]
    [0.5]]
   [0.5
    [0.5]
    [0.5]]
  ]
  [0.5
   [0.5
    [0.5]
    [0.5]]
   [0.5
    [0.5]
    [0.5]]
  ]
 ]
\end{forest}
```

You can check the version you're using by typing `latexindent.pl -v` at the command prompt.
Let me know
Chris

**Comment by jasonhan-vassar** [comment]
Whoops, I forgot to include the version. That was a reminder to update to the latest, so now I am on 3.9.1.

It turns out this was the culprit in my settings. This was from a previous issue resolved between us and I didn't think it would affect this case at all:

```YAML
# problematic
specialBeginEnd:
    path:
        begin: '\\path'
        end: ';'
        lookForThis: 1
    specialBeforeCommand: 1

noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
    UnNamedGroupingBracesBrackets: 1
```

Do you know why this is affecting the indentation?

**Comment by cmhughes** [comment]
The reason for this is the line
```yaml
    specialBeforeCommand: 1
```
which instructs `latexindent.pl` to find the `$...$` before the braces. Then, the default routine for finding `UnNamedGroupingBracesBrackets` fails, because the `$...$` are no longer in the code.

We can fix this, by telling `latexindent.pl` to look for `UnNamedGroupingBracesBrackets` after line breaks using `\R` and horizontal spaces using `\h` by using 
```yaml
fineTuning:
    UnNamedGroupingBracesBrackets: 
      follow: '\{|\[|,|&|\)|\(|\$|\R|\h'
```

The complete YAML is below, which gives the output as described above.

```yaml
defaultIndent: ' '

specialBeginEnd:
    path:
        begin: '\\path'
        end: ';'
        lookForThis: 1
    specialBeforeCommand: 1

noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
    UnNamedGroupingBracesBrackets: 1

fineTuning:
    UnNamedGroupingBracesBrackets: 
      follow: '\{|\[|,|&|\)|\(|\$|\R|\h'
```

I fully appreciate that this is not ideal and that you, the user, shouldn't have to go through this. In parallel to maintaining the existing implementation, I am trying to develop a new implementation that I *hope* would mean less of this of this kind of stuff :)

I hope this works, let me know!
Chris
