### ISSUE TITLE
Enhancement: space before the leading ampersand

### ISSUE THREAD

**Issue by zhi-wang** [cmhughes/latexindent.pl#275]
Hi, I guess this is an enhancement-related question: is there a way to avoid the extra space character before the leading ampersand? One example is as follows,

```tex
\begin{equation}
\begin{aligned}
 & a = b, \\
 & c = d.
\end{aligned}
\end{equation}
```

I can see that padding spaces around the ampersands is usually a good thing, especially if equations are aligned along the equal signs, and there are switches in the YAML file to fine-tune the code behavior, but I was unable to find a switch for the leading ampersand characters.

Thanks.

**Comment by cmhughes** [comment]
Hello,
Thanks for this.

Have you seen
https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-tabular4yaml
....?

Does it help?
Chris

**Comment by cmhughes** [comment]
If I use the following, then I receive

```yaml
defaultIndent: ' '
lookForAlignDelims:
   aligned: 
      spacesBeforeAmpersand: 0

```
then I receive:
```tex
\begin{equation}
 \begin{aligned}
  & a = b, \\
  & c = d.
 \end{aligned}
\end{equation}
```

**Comment by cmhughes** [comment]
You might also want to see https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-myenv-noadd1

Let me kniw if there is anything else :)

**Comment by cmhughes** [comment]
If I use
```yaml
defaultIndent: ' '
lookForAlignDelims:
   aligned: 
      spacesBeforeAmpersand: 0
noAdditionalIndent:
   aligned: 1
```
then I receive
```tex
\begin{equation}
 \begin{aligned}
 & a = b, \\
 & c = d.
 \end{aligned}
\end{equation}
```

**Comment by zhi-wang** [comment]
Thank your for your reply. This is basically what I had tried -- it did remove the space before the leading ampersand. But I decided to remove this setting `spacesBeforeAmpersand: 0` for the time being, because it will break more common cases where equations are aligned along the equal signs. For example:

```tex
\begin{equation}
 \begin{aligned}
 a& = b, \\
 c& = d.
 \end{aligned}
\end{equation}
```
I think having spaces before the ampersands looks better for these equations. :)


> If I use
> 
> ```yaml
> defaultIndent: ' '
> lookForAlignDelims:
>    aligned: 
>       spacesBeforeAmpersand: 0
> noAdditionalIndent:
>    aligned: 1
> ```
> 
> then I receive
> 
> ```
> \begin{equation}
>  \begin{aligned}
>  & a = b, \\
>  & c = d.
>  \end{aligned}
> \end{equation}
> ```

**Comment by cmhughes** [comment]
Do you need anything else from me?

**Comment by zhi-wang** [comment]
This is the only question I have now.

**Comment by cmhughes** [comment]
Please can you be specific, I thought I had answered your question already.

**Comment by zhi-wang** [comment]
I see... I was just trying to keep the title of this issue short, but I guess the complete version of my question should read "How can I avoid padding space before the leading ampersand character whereas in the mean time keep the space characters around the ampersand if it is not the first non-whitespace character? I can't have both of them." Sorry that my previous posts were not clear to you.

**Comment by cmhughes** [comment]
How about
```
noAdditionalIndent:
   aligned: 1
```

**Comment by zhi-wang** [comment]
I wish I could format the following tex code
```tex
\begin{equation}
          \begin{aligned}
&a = b, \\
&c = d.
  \end{aligned}
\end{equation}

\begin{equation}
   \begin{aligned}
       a&= b, \\
    c&= d.
        \end{aligned}
\end{equation}
```
to
```tex
\begin{equation}
    \begin{aligned}
    & a = b, \\
    & c = d.
    \end{aligned}
\end{equation}

\begin{equation}
    \begin{aligned}
    a & = b, \\
    c & = d.
    \end{aligned}
\end{equation}
```

But with the configuration you recommended
```yaml
defaultIndent: '    '
lookForAlignDelims:
   aligned: 
      spacesBeforeAmpersand: 1
noAdditionalIndent:
   aligned: 1
```

The first two equations are always formatted to
```tex
\begin{equation}
    \begin{aligned}
     & a = b, \\
     & c = d.
    \end{aligned}
\end{equation}
```

The difference is more obvious in an external text editor.

![Screenshot from 2021-06-05 15-30-35](https://user-images.githubusercontent.com/13459753/120904690-20afc300-c613-11eb-8567-a4a36ef4ffd1.png)

I was wondering if there is a yaml option to avoid padding an extra space before the ampersand if it happens to be the first non-whitespace character, even if `spacesBeforeAmpersand: 1` is implicitly or explicitly set. I couldn't simply set it to 0 because it'd format the second equation to
```tex
\begin{equation}
    \begin{aligned}
    a& = b, \\
    c& = d.
    \end{aligned}
\end{equation}
```
which is not what I anticipated either.

Thanks.

**Comment by cmhughes** [comment]
Ok, thanks, I understand now :) 

How about if I develop the following option:

```yaml
lookForAlignDelims:
   aligned: 
      spacesBeforeAmpersand: 
            default:  1
            leadingBlankColumn: 0
```

Does this look like it would be the appropriate interface?

**Comment by zhi-wang** [comment]
This looks good to me. Thanks!

**Comment by cmhughes** [comment]
This is implemented, and documented, as of https://github.com/cmhughes/latexindent.pl/commit/2eb28144e697fdb9e255029d316448ca93c42d7e, and will be part of the next release (coming soon). If you need it before the release, you can clone the `develop` branch. 

demonstration
-

Starting with
```tex
\begin{equation}
    \begin{aligned}
    & a = b, \\
    & c = d.
    \end{aligned}
\end{equation}

\begin{equation}
    \begin{aligned}
    a & = b, \\
    c & = d.
    \end{aligned}
\end{equation}
```
and using 
```yaml
defaultIndent: ' '

noAdditionalIndent:
  aligned: 1

lookForAlignDelims:
   aligned: 
      spacesBeforeAmpersand: 
        default: 2
        leadingBlankColumn: 0
```
then the result is
```
\begin{equation}
 \begin{aligned}
 & a = b, \\
 & c = d.
 \end{aligned}
\end{equation}

\begin{equation}
 \begin{aligned}
 a  & = b, \\
 c  & = d.
 \end{aligned}
\end{equation}
```
The fields `default` and `leadingBlankColumn` both take *integer* values that represent the spaces to be added before ampersands. They are both optional.
