### ISSUE TITLE
closing `\if<something>` command with {} breaks indentation

### ISSUE THREAD

**Issue by SoongJr** [cmhughes/latexindent.pl#283]
Issue:
--
ChkTeX warns about commands that are terminated implicitly by whitespace and suggests to use explicit termination with `{}`. But if I do, latexindent doesn't recognize the command as an `\if` anymore.  
Workaround: explicit termination is not as important for `\if` statements as it is for commands elsewhere, so terminate implicitly and tell chktex to ignore it.

original .tex code
--
```latex
\newif\iflistoftables{}

\iflistoftables{}
        \listoftables
\fi

\iflistoftables       % chktex 1 don't terminate \if-commands with {} as it breaks auto-indentation
      \listoftables
\fi
```

yaml settings
--
`-y="defaultIndent: '  '"`

actual/given output
--
```latex
\newif\iflistoftables{}

\iflistoftables{}
\listoftables
\fi

\iflistoftables       % chktex 1 don't terminate \if-commands with {} as it breaks auto-indentation
  \listoftables
\fi
```

desired or expected output
--
```latex
\newif\iflistoftables{}

\iflistoftables{}
  \listoftables
\fi

\iflistoftables       % chktex 1 don't terminate \if-commands with {} as it breaks auto-indentation
  \listoftables
\fi
```

**Comment by cmhughes** [comment]
Thanks for this! :)

As you say, the `{}` cause problems for the default pattern searching of `latexindent.pl`. We can configure the tool by using the following settings:

SoongJr.yaml
-
```yaml
specialBeginEnd:
    ifWithArgs:
        begin: '\\iflistoftables\{\}'
        end: '\\fi'
        lookForThis: 1
    specialBeforeCommand: 1
```
and then call `latexindent.pl` with
```
latexindent.pl -l SoongJr.yaml myfile.tex
```
to receive
```tex
\newif\iflistoftables{}

\iflistoftables{}
	\listoftables
\fi

\iflistoftables       % chktex 1 don't terminate \if-commands with {} as it breaks auto-indentation
	\listoftables
\fi
```
I hope this helps, let me know!

**Comment by SoongJr** [comment]
Thanks for the workaround 😁 This does fix this particular `\if`, but for some reason, doing this influences unrelated indentation...
yaml:
```yaml
defaultIndent: '  '
indentPreamble: 1
specialBeginEnd:
    ifWithArgs:
        begin: '\\iflistoftables\{\}'
        end: '\\fi'
        lookForThis: 1
    specialBeforeCommand: 1
```

input:
```latex
\newcommand{\Messbox}[2]{
\setlength{\unitlength}{1.0mm}
\begin{picture}(#1,#2)
\linethickness{0.05mm}
\put(0,0){\dashbox{0.2}(#1,#2)
{\parbox{#1mm}{
\centering\footnotesize
Breite $ = #1 {\ mm}$\\
Höhe $ = #2 {\ mm}$
}
}
}
\end{picture}
}
```
output:
```latex
\newcommand{\Messbox}[2]{
  \setlength{\unitlength}{1.0mm}
  \begin{picture}(#1,#2)
    \linethickness{0.05mm}
    \put(0,0){\dashbox{0.2}(#1,#2)
      {\parbox{#1mm}{
          \centering\footnotesize
          Breite $ = #1 {\ mm}$\\
          Höhe $ = #2 {\ mm}$
        }
      }
    }
  \end{picture}
}
```

Without the `specialBeginEnd` in .latexindent.yaml, the code is indented back to the way it was previously done:
```latex
\newcommand{\Messbox}[2]{
  \setlength{\unitlength}{1.0mm}
  \begin{picture}(#1,#2)
    \linethickness{0.05mm}
    \put(0,0){\dashbox{0.2}(#1,#2)
    {\parbox{#1mm}{
    \centering\footnotesize
    Breite $ = #1 {\ mm}$\\
    Höhe $ = #2 {\ mm}$
    }
    }
    }
  \end{picture}
}
```

The new indentation is actually better, I'm just confused why that unrelated rule in yaml (ths time I'm making sure that there is no other code in the file, the above are the complete file contents) is affecting this indentation...

**Comment by SoongJr** [comment]
I'm now using this yaml file:
```yaml
defaultIndent: '  '
indentPreamble: 1
specialBeginEnd:
    ifWithArgs:
        begin: '\\if[a-zA-Z@]*?\{\}'
        end: '\\fi'
        lookForThis: 1
    specialBeforeCommand: 1
```

But this indents `\else` as well, which shouldn't be indented... How can I tell it that? I had a quick look at DefaultSettings.yaml but couldn't find anything that helped me 😐 The `fineTuning: IfElseFi: name: '(?!@?if[a-zA-Z@]*?\{)@?if[a-zA-Z@]*?'` value seems to actively ignore if-commands terminated with a curly brace, if I read the regex correctly, but trying to override this in .latexindent.yaml with `name: '(?!@?if[a-zA-Z@]*?\{[^\}])@?if[a-zA-Z@]*?'` didn't have any effect.

I think for now I need to keep using the other workaround of silencing chktex about this warning, I'm putting too much time into this 😅

**Comment by cmhughes** [comment]
Thanks for this. Let me go through your points in turn.

using fineTuning `ifElseFi`
-
As you described, we can tweak the `fineTuning` field; so, using:
```yaml
fineTuning:
    ifElseFi:
      name: '(?!(?:newif))@?if[a-zA-Z@]*?(?:\{\})?'
```
gives the output:
```tex
\newif\iflistoftables{}

\iflistoftables{}
	\listoftables
\fi

\iflistoftables
	\listoftables
\fi
```

using `specialBeginEnd`
-
If you wish to use the initial option I gave you, and account for `else` statements, then you can try
```
defaultIndent: '  '
indentPreamble: 1
specialBeginEnd:
    ifWithArgs:
        begin: '\\if[a-zA-Z@]*?\{\}'
        middle: '\\else'  # <!---------- NEW BIT
        end: '\\fi'
        lookForThis: 1
    specialBeforeCommand: 1
```
See https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-middle-yaml for further demonstration.

your next example: option 1
-
Using the settings
```yaml
defaultIndent: '  '

specialBeginEnd:
    specialBeforeCommand: 1
```
gives the following
```tex
\newcommand{\Messbox}[2]{
  \setlength{\unitlength}{1.0mm}
  \begin{picture}(#1,#2)
    \linethickness{0.05mm}
    \put(0,0){\dashbox{0.2}(#1,#2)
      {\parbox{#1mm}{
          \centering\footnotesize
          Breite $ = #1 {\ mm}$\\
          Höhe $ = #2 {\ mm}$
        }
      }
    }
  \end{picture}
}
```
The reason that `specialBeforeCommand` is needed is because of `$ = #1 {\ mm}$`. 

your next example: option 2
-
Alternatively, you can use the following yaml:
```yaml
defaultIndent: '  '

fineTuning:
    namedGroupingBracesBrackets:
      name: '[0-9\.a-zA-Z@\*><#]+?'
      follow: '\h|\R|\{|\[|\$|\)|\(|='
```
which gives the same output as above. This is just a slight tweak to the default, as it allows `namedGroupingBracesBrackets` to have `#` in the name, and to be found after `=`.

your next example: option 3
-
Another option is to use `noIndentBlock` so that the problematic parts are stored as verbatim, and so don't get in the way of the brace matching routine:
```yaml
defaultIndent: '  '

noIndentBlock:
  SoongJr1:
    begin: 'Breite\h*\$'
    body: '.*?'
    end: '\$\\\\'
  SoongJr2:
    begin: 'Höhe\h*\$'
    body: '.*?'
    end: '\$'
```
The output is as above. See https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-noindent1 for further examples.

Hopefully this gives you options, and at least one of them appeals/works for you :)

**Comment by SoongJr** [comment]
Thanks a lot for your detailed explanations!
I kept getting strange behavior trying to verify my configuration and finally found out that the auto-formatter in my IDE (VS Code with LaTeX-Workshop extension) does not call latexindent in the working directory I expected it to, so it couldn't find .latexindent.yaml... I had to specify `-l=%DIR%/.latexindent.yaml` as an argument (instead of just `-l`). That's part of why I had so many problems...
Having trouble getting the finetune to work (it looked like it just had no effect at all), but your second suggestion with `middle` worked. My yaml is now this:
```yaml
defaultIndent: '  '
indentPreamble: 1
specialBeginEnd:
    # correctly indent `\if` constructs where the command is terminated with {} (e.g. `\ifassignment{}`)
    ifWithArgs:
        begin: '\\if[a-zA-Z@]*?\{\}'
        middle: '\\else'
        end: '\\fi'
        lookForThis: 1
    specialBeforeCommand: 1
```
Thank you so much, this makes it much easier to keep indented _and_ adhering to chktex. I like to enforce both rules in github actions ;)

**Comment by cmhughes** [comment]
That's great, I'm glad it is working :)

If you have a link to your github actions, I'd be interested to see it!

Feel free to post as and when you have questions :)

**Comment by SoongJr** [comment]
of course, it's the least I can do :)
Here's the action in action on my fork of [akad-latex-vorlage](https://github.com/SoongJr/akad-latex-vorlage): https://github.com/SoongJr/akad-latex-vorlage/actions

And here's a copy of main.yml, the first two jobs are for checking indentation and the rest for compiling and linting:
```yaml
name: Build LaTeX document
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  list_tex_files:
    # list all .tex files in this repo and save them in a variable that can be used by other jobs as input for their matrix (so they run one job on each tex file)
    outputs:
      matrix: ${{ steps.list-files.outputs.matrix }}
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: list .tex files in this repo
        id: list-files
        # print each filename (relative path) as an element of a JSON list, github can parse this into setting output variable "matrix"
        run: |
          printf "::set-output name=matrix::{\"include\":["
          find . -name "*.tex" -exec printf "{\"file\":\"{}\"}," \;
          printf "]}\n"
  check_formatting:
    # run latexindent on each tex file and diff the result with committed file. Produces failure of the formatting is not applied properly.
    needs: [list_tex_files]
    runs-on: [ubuntu-latest]
    strategy:
      # read the output variable of the list_tex_files job
      matrix: ${{fromJson(needs.list_tex_files.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2  # Checks-out repository under $GITHUB_WORKSPACE
      - name: Apply indentation rules to ${{ matrix.file }}
        # first format the content of the file and save this into a temporary file 
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}
          compiler: latexindent
          args: --local -o formatted.tex    # configuration is read from local files in git repository root. you can adjust here if your file is somewhere else.
      - name: Check for correct formatting
        # now compare this temporary file, which is correctly formatted, with the actual file. Any differences will be printed in screen and fail this job.
        uses: dante-ev/latex-action@latest
        with:
          root_file: formatted.tex
          compiler: diff
          args: ${{ matrix.file }}
          
  build_latex:
    # use latexmk to create a PDF, it can detect whether to run biber and via a .latexmkrc file you can also tell it to run makeglossaries or other steps.
    # If you renamed your root tex file, originally "vorlage.tex" (e.g. to get a nice PDF name), simply also adjust the filename in this job's matrix.
    # PDF is then uploaded so it shows up on the summary page of the succeeded action run.
    # Finally, the whole project is linted with ChkTeX (done at the end so that a failure fails the action, but does not prevent PDF from being built)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [ vorlage ] # root tex file(s) to compile (without extension). Only set multiple files if you are creating multiple PDFs.
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2  # Checks-out repository under $GITHUB_WORKSPACE
      - name: Compile ${{ matrix.file }}.tex
        # run latexmk on the given file
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
      - name: Upload ${{ matrix.file }}.pdf
        # upload exactly this generated PDF (will show up at the bottom of each run of this github action)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.file }}.pdf
          path: ${{ matrix.file }}.pdf
          if-no-files-found: error
      - name: Lint ${{ matrix.file }}.tex
        # run chktex the same way LaTeX-Workshop extension of Visual Studio code would
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}.tex
          compiler: chktex
          args: -eall -n22 -n30 -e16 -q   # make sure to adjust these arguments to match your IDE's (or vice versa)
```
