### ISSUE TITLE
[Proposal] Treat `minted` aliases as `verbatim` in `defaultSettings.yaml`

### ISSUE THREAD

**Issue by XuehaiPan** [cmhughes/latexindent.pl#288]
Please provide the following when posting an issue:

The `minted` package allows users to define aliases to the `minted` environment ([Defining shortcuts](https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/minted/minted.pdf#Defining%20shortcuts)). These environments, i.e. source code blocks, should be treated as `verbatim`s as well.

original .tex code
--
*Please paste your .tex code here. Please note in answering your issue, I may add the code you provide to the test-cases directory. Please detail explicitly if you would prefer me not to do so.*.

```latex
% !TEX encoding = UTF-8 Unicode
% !TEX program = latexmk
% !TEX options = -xelatex -shell-escape test
% !TEX root = ./test.tex

\documentclass{article}

\usepackage{xcolor}   % for code block background color
\usepackage{relsize}  % defines macro \smaller
\usepackage{setspace} % to modify spacing
\setlength{\parindent}{0pt} % remove indentation for paragraphs

\usepackage[final=true]{minted}
\usemintedstyle{default}
\setminted{
  bgcolor={black!5},
  autogobble=true,
  showspaces=false,
  tabsize=4,
  fontsize={\footnotesize}
}
\setmintedinline{fontsize={\smaller}}

\newminted{latex}{}
\newminted{python}{}
\newmintinline{latex}{}
\newmintinline{python}{}
\newmintinline{bash}{}

\begin{document}

To define new minted environment aliases in your preamble:

\begin{latexcode}
  \usepackage{minted}
  \newminted{python}{}
  \newmintinline{python}{}
\end{latexcode}

Then you can use environment \latexinline|\begin{pythoncode} ... \end{pythoncode}| to write Python code blocks.

\medskip

To compile: \bashinline|latexmk -xelatex -shell-escape test|

\bigskip

\textbf{\large Examples:}

\medskip

Code block:

\begin{pythoncode}
  for i in range(10):
      print(i)
\end{pythoncode}

Code block with options:

\begin{pythoncode*}{linenos=true}
  for i in range(10):
      print(i)
\end{pythoncode*}

Inline code: \pythoninline|print('Hello, world!')|

\end{document}
```

yaml settings
--
*Please paste your YAML settings (if any) here*

```yaml
# default value of indentation
defaultIndent: '  '

#  verbatim environments specified 
#  in this field will not be changed at all!
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1
    # aliases defined by `\newminted`
    # for example, `\newminted{perl}` defines two environments "perlcode" and "perlcode*"
    '\w+code*?': 1

#  verbatim commands such as \verb! body !, \lstinline$something else$
verbatimCommands:
    verb: 1
    lstinline: 1  # covered by the last entry
    mintinline: 1  # covered by the last entry
    '\w+inline': 1  # aliases defined by `\newmintedinline`
```

actual/given output
--
*Please paste the output you receive here*

Without customized YAML config (use defaults):

```latex
\begin{pythoncode}
for i in range(10):
print(i)
\end{pythoncode}
```

With customized YAML config:

```latex
\begin{pythoncode}
  for i in range(10):
      print(i)
\end{pythoncode}
```

desired or expected output
--
*Please paste your desired/expected output here; that is, what do you want the output to look like*

Treat `minted` aliases as `verbatim` by default, i.e., achieve the last result above with the default settings.

anything else
--
*Please put any comments or anything else here :)*

PDF result:

![Screenshot](https://user-images.githubusercontent.com/16078332/134479182-6bf06599-6ef4-48e3-85c6-7b895d03cf0f.png)
