### ISSUE TITLE
How to separate sentences by `%` when enabling the one-sentence-per-line mode?

### ISSUE THREAD

**Issue by taquangtrung** [cmhughes/latexindent.pl#295]
Hi,

I'm looking to configure latextindent to separate sentences by the comment symbol `%`.

Here is my LaTeX code:

```latex
This is the 1st sentence. This is the 2nd sentence which is very long so that its length exceeds 80 characters and will be broken into 2 lines. And here is the 3rd sentence.
```

and the YAML configuration of latexindent:

```yaml
defaultIndent: "  "

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 1
        textWrapSentences: 1
        sentenceIndent: ""
    textWrapOptions:
        columns: 80
        separator: ""
```

When running latexindent with the `-m` flag, I obtained:

```latex
This is the 1st sentence.
This is the 2nd sentence which is very long so that its length exceeds 80
characters and will be broken into 2 lines.
And here is the 3rd sentence.
```

Is it possible to make latexindent add a separator `%` between every two sentences so that I can obtain an output like?

```latex
This is the 1st sentence.
%
This is the 2nd sentence which is very long so that its length exceeds 80
characters and will be broken into 2 lines.
%
And here is the 3rd sentence.
```

I tried to set both `sentenceIndent` and `separator` to `\n%` and they didn't work: they will also add the separator `%` inside the second sentence.

Thank you for spending time looking at this issue!

**Comment by cmhughes** [comment]
I think the replacement switches might be helpful here.

Following https://tex.stackexchange.com/questions/30595/is-there-such-a-thing-as-a-latex-code-formatter/499759#499759 can you try

```yaml
replacements:
  -
    when: after
    substitution: |-
      s/([a-zA-Z]\. \h*\R) (\h*[a-zA-Z]) /$1
            %
            $2/sxg
```
You will need to use `-r` in your call to latexindent.

I can't test the above, but it should at least be close. Let me know.

**Comment by taquangtrung** [comment]
@cmhughes: Thanks a lot for your reply!

I modified the replacement string a bit to remove whitespace

```
replacements:
  -
    when: after
    substitution: |-
      s/([a-zA-Z]\. \h*\R) (\h*[a-zA-Z]) /$1%
      $2/sxg
```

then, it can work well with lines not in an environment:

```latex
This is the 1st sentence.
%
This is the 2nd sentence which is very long so that its length exceeds 80
characters and will be broken into 2 lines.
%
And here is the 3rd sentence.
```

However, when separating sentences inside an environment, the result becomes like:

```latex
\begin{paragraph}
  This is the 1st sentence.
%
  This is the 2nd sentence which is very long so that its length exceeds 80
  characters and will be broken into 2 lines.
%
  And here is the 3rd sentence.
\end{paragraph}
```

For a general solution, I think that maybe a sentence separator is better?

It is feature to implement such feature? 

I can take a look at the code and figure out to do it, and any advice from you
would be very appreciated.

**Comment by cmhughes** [comment]
Can you try
```yaml
replacements:
  -
    when: after
    substitution: |-
      s/([a-zA-Z]\.\h*\R)((\h*)[a-zA-Z])/$1$3%
      $2/sxg
```
Note that it should add the leading space to the % as well by using $3
