### ISSUE TITLE
Incorrect line break

### ISSUE THREAD

**Issue by qiancy98** [cmhughes/latexindent.pl#299]
Please provide the following when posting an issue:

original .tex code
--
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{tabular}{cc}	1 & 2
\end{tabular}
\begin{equation*} E = m c^2 \end{equation*}
\end{document}
```

yaml settings
--
```yaml
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```

actual/given output
--
(Not changed)

desired or expected output
--
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{tabular}{cc}
	1 & 2
\end{tabular}
\begin{equation*}
	E = m c^2 
\end{equation*}
\end{document}
```
anything else
--

- Why is it a *feature* that `equation*` behaves differently? I notice that you single out the behaviour of `equation*`.
- If an option is given to an environment (it is `tabular` here), then the `BodyStartsOnOwnLine` won't work. Is this a *feature*?

**Comment by cmhughes** [comment]
Thanks for this. 

I hope to try this out soon, but in the meantime can you take a look at https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#partnering-bodystartsonownline-with-argument-based-poly-switches and see if that helps? 

> Why is it a feature that equation* behaves differently? I notice that you single out the behaviour of equation*.

It's there for demonstration to help the user understand how things can be specified on a per-name basis.

**Comment by qiancy98** [comment]
> It's there for demonstration to help the user understand how things can be specified on a per-name basis.

Well, thanks. (It took me about 30min's to find that this has been specified. hhh)

> Can you take a look at https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#partnering-bodystartsonownline-with-argument-based-poly-switches and see if that helps?

Thank you for your notice. It works well with the following command:
```YAML
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
    mandatoryArguments:
        tabular:
            RCuBFinishesWithLineBreak: 1
```

<del>I noticed this. (Actually I read the whole book yesterday.) But I do not know how to combine it with what I am doing now...
If what you mean is to add `\n` after all `mandatoryArguments`, I do not think it is proper... (as there are tooooo many arguments in normal text.) After all, they are special, as they are the arguments of the enviroment. What I want is to start my body on its own line.</del>

Ps: I notice that, in the table https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#tab-poly-switch-mapping, there is a space in `namedGroupingBraces Brackets`. Is that what you want? (there is no space in all other names.)
You can close this comment after you answer this ps.
