### ISSUE TITLE
call latexindent without file extension

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#30]
currently it crashes without an extension, e.g

latexindent myfile

will crash.

**Comment by cmhughes** [comment]
possible `yaml` interface
```
fileExtensionPreference:
      tex: 1
      sty: 2
      cls: 3
```
