### ISSUE TITLE
Extra dot when using RegEx

### ISSUE THREAD

**Issue by qiancy98** [cmhughes/latexindent.pl#300]
Please provide the following when posting an issue:

original .tex code
--
```LaTeX
\documentclass{article}
\begin{document}
Hello World.
\end{document}
```

yaml settings
--
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            betterFullStop: 0  # .
            questionMark: 0     # ?
            exclamationMark: 0 # !
            other: "(?<![A-Z])(\.|\!|\?)(?=\s|\n)"
```

actual/given output
--
```LaTeX
\documentclass{article}
\begin{document}
Hello World.
.
\end{document}
```

desired or expected output
--
(Not changed)

anything else
--
It will be OK if we change the setting to the following
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            betterFullStop: 0  # .
            questionMark: 0     # ?
            exclamationMark: 0 # !
            other: "(?<![A-Z])(?:\.|\!|\?)(?=\s|\n)"
```
It seems that you have noticed this in your documentation.
So, I wonder if it is a *feature* or a bug.
