### ISSUE TITLE
Option to ignore multiline commands in alignment environments?

### ISSUE THREAD

**Issue by jameswhqi** [cmhughes/latexindent.pl#308]
original .tex code
--
```latex
\begin{tabular}{cc}
1&2\only<2->{\\
3&4}
\end{tabular}
```

yaml settings
--
```yaml
defaultIndent: "  "
lookForAlignDelims:
  tabular:
    dontMeasure: largest
```

actual/given output
--
```latex
\begin{tabular}{cc}
  1 & 2\only<2->{ \\
    3 & 4}
\end{tabular}
```

desired or expected output
--
```latex
\begin{tabular}{cc}
  1 & 2\only<2->{ \\
  3 & 4}
\end{tabular}
```

**Comment by cmhughes** [comment]
Hello,
When I run 
```
latexindent.pl myfile.tex
```
with your code, then I get
```tex
\begin{tabular}{cc}
	1 & 2\only<2->{ \\
	3 & 4}
\end{tabular}
```
I believe this is your desired output. 

Which version are you using?

**Comment by jameswhqi** [comment]
Sorry, I forgot that I had `dontMeasure: largest` in my settings.  Editing the OP accordingly.  Still it would be great if the multiline commands can be ignored even if it's on a line with `dontMeasure`.

**Comment by cmhughes** [comment]
For your example, you can try
```yaml
defaultIndent: "  "
lookForAlignDelims:
  tabular:
    dontMeasure: largest

specialBeginEnd:
    onlyAsVerb:
        begin: '\\only<2->'
        end: '\{'
        lookForThis: verbatim
```
then the output is
```tex
\begin{tabular}{cc}
  1 & 2\only<2->{ \\
  3 & 4}
\end{tabular}
```

**Comment by jameswhqi** [comment]
But I also use `\only` elsewhere in the document, where I want the usual indentation rules to be observed.  Is that possible?

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/90175fedde8cf18ace32263156ff0aca92842bc0 a new option is available:
```yaml
lookForAlignDelims:
   tabular: 
      dontMeasure: largest
      lookForChildCodeBlocks: 0
```
which gives the output
```tex
\begin{tabular}{cc}
	1 & 2\only<2->{ \\
	3 & 4}
\end{tabular}
```

This will be part of the next release, coming soon hopefully.
