### ISSUE TITLE
oneSentencePerLine not behaving as expected

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#320]
It seems that `latexindent.pl` is not putting new sentences on a new line as I would have expected:

`main.tex`:
```latex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

\end{document}
```

`.latexindent.yaml`:
```yaml
defaultIndent: "    "
removeTrailingWhitespace: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 100
    oneSentencePerLine:
      manipulateSentences: 1
```

Expected result:
```latex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id 
est laborum.

\end{document}
```

Command run:
```bash
latexindent.pl -l -m main.tex > output.tex
```

Actual result:
```latex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.

\end{document}
```

**Comment by cmhughes** [comment]
I don't think your yaml is indented correct, can you try
```yaml
defaultIndent: "    "
removeTrailingWhitespace: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 100
  oneSentencePerLine:
    manipulateSentences: 1
```

**Comment by tdegeus** [comment]
Thanks, that makes sense. 

A follow up question: can I apply the wrapping only to lines that exceed the maximal line width?

**Comment by cmhughes** [comment]
Text wrapping should only apply to lines bigger than columns.

If I haven't understood correctly, please provide a complete example :)

**Comment by tdegeus** [comment]
The following should stay untouched:
```latex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit
esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.

\end{document}
```
but with your `yaml` file gets formatted to:
```latex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

\end{document}
```

**Comment by cmhughes** [comment]
The default behaviour of `oneSentencePerLine` is to *remove* sentence line breaks; see https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-onesentenceperline. 

You can change this as follows:
```yaml
defaultIndent: "    "
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0  # <!---- NEW BIT
```
then the output is
```tex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit
esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.

\end{document}
```
