### ISSUE TITLE
oneSentencePerLine cuts `I.e.\`

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#321]
Please provide the following when posting an issue:

original .tex code
```latex
\documentclass{article}

\begin{document}

I.e.\ it is a finite constant.

\end{document}
```

yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: "    "
removeTrailingWhitespace: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 100
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0
```

command:
```bash
latexindent.pl -l -m -s -w main.tex
```

actual/given output
```latex
\documentclass{article}

\begin{document}

I.e.
\ it is a finite constant.

\end{document}
```

desired or expected output
```latex
\documentclass{article}

\begin{document}

I.e.\ it is a finite constant.

\end{document}
```

**Comment by cmhughes** [comment]
Thanks for this, perhaps you can tweak the fine tuning as in https://github.com/cmhughes/latexindent.pl/issues/200

How about the following? 

```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1

fineTuning:
    modifyLineBreaks:
      betterFullStop: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:I\.e)|(?:etc))))\.(?!(?:\h*[a-z]|[A-Z]|\-|~|\,|[0-9]|\}))'
```
