### ISSUE TITLE
latexindent.exe win32

### ISSUE THREAD

**Issue by ostaith** [cmhughes/latexindent.pl#326]
Hi cmhughes, 
Thanks for your nice indent tool. Can I expect some new features?

1. can you build 32bit latexindent.exe still?

2. for latex3 code, can set such as 'add extra space' to each token to separate them.

code1:
```
\cs_new_protected_nopar:Npn\maoxuan_hyper_link:nn
  {\hyper@link{link }}
```

indent to:
```
\cs_new_protected_nopar:Npn \maoxuan_hyper_link:nn
  { \hyper@link { link } }
```

explain:
```
\cs_new_protected_nopar:Npn \maoxuan_hyper_link:nn
                           ^
  { \hyper@link { link } }
   ^           ^ ^    ^ ^
^ means extra space
```

3. code will alignment with '=' (it's better can be set, eg, '-') in code block:

code2:
```
\geometry
  {
    papersize  = { 130mm , 184mm } ,
    lines  = 25 ,
    hmargin = 15mm ,
    bindingoffset = 5mm ,
    headheight = 10pt ,
    headsep = \baselineskip ,
    includehead = true ,
    vcentering = true
  }
```

indent to:
```
\geometry
  {
    papersize     = { 130mm , 184mm } ,
    lines         = 25 ,
    hmargin       = 15mm ,
    bindingoffset = 5mm ,
    headheight    = 10pt ,
    headsep       = \baselineskip ,
    includehead   = true ,
    vcentering    = true
  }
```

code3:
```
\geometry
  \mybegin %%%%%%%% <-- can be customized begin and end
    papersize  = { 130mm , 184mm } ,
    lines  = 25 ,
    hmargin = 15mm ,
    bindingoffset = 5mm ,
    headheight = 10pt ,
    headsep = \baselineskip ,
    includehead = true ,
    vcentering = true
  \myend %%%%%%%% <-- can be customized begin and end
```

indent to:
```
\geometry
  \mybegin 
    papersize     = { 130mm , 184mm } ,
    lines         = 25 ,
    hmargin       = 15mm ,
    bindingoffset = 5mm ,
    headheight    = 10pt ,
    headsep       = \baselineskip ,
    includehead   = true ,
    vcentering    = true
  \myend
```

code4:
```
\dim_set:Nn \l_maoxuan_headsep_dim
  {
    \headsep - \box_ht:N \l_maoxuan_main_head_rule_box
    - \box_dp:N \l_maoxuan_main_head_rule_box %%%%%%%% <-- this line need extra indent
  }
```

indent to:
```
\dim_set:Nn \l_maoxuan_headsep_dim
  {
    \headsep - \box_ht:N \l_maoxuan_main_head_rule_box
             - \box_dp:N \l_maoxuan_main_head_rule_box %%%%%%%% <-- expected output
  }
```

code5:
```
\xeCJKsetup
  {
    AllowBreakBetweenPuncts = true ,
    CheckSingle             = true ,
    AutoFakeBold            = false ,
    AutoFakeSlant           = false ,
    CheckFullRight          = true ,
    NewLineCS+              = \mxendarticle \item \mnitem
    \maoxuan_endline_mark: , %%%%%%%% <-- this line need extra indent
    NoBreakCS+              = \mnote ,
    PunctStyle              = kaiming ,
    KaiMingPunct+           = ：； ,
  }
```

indent to:
```
\xeCJKsetup
  {
    AllowBreakBetweenPuncts = true ,
    CheckSingle             = true ,
    AutoFakeBold            = false ,
    AutoFakeSlant           = false ,
    CheckFullRight          = true ,
    NewLineCS+              = \mxendarticle \item \mnitem
                              \maoxuan_endline_mark: , %%%%%%%% <-- expected output
    NoBreakCS+              = \mnote ,
    PunctStyle              = kaiming ,
    KaiMingPunct+           = ：； ,
  }
```

**Comment by cmhughes** [comment]
Hello,
Thanks for this.

> can you build 32bit latexindent.exe still?

Yes, it's available from the https://github.com/cmhughes/latexindent.pl/releases/tag/V3.14 page

code 1
-
```yaml
replacements:
  -
    # change {\\... into { \\...
    substitution: |-
      s/\{\h*(\\|[a-z]|[A-Z])/\{ $1/sgx
    when: after
  -
    # change <letter>} into <letter> }
    substitution: |-
      s/([a-z]|[A-Z])\h*\}/$1 \}/sgx
    when: after
  -
    # change <letter>{ into <letter> {
    substitution: |-
      s/([a-z]|[A-Z])\h*\{/$1 \{/sgx
    when: after

indentRules:
  maoxuan_hyper_link:nn:
    body: '  '
```
called with `latexindent.pl -r -l myfile.yaml myfile.tex` gives
```tex
\cs_new_protected_nopar:Npn\maoxuan_hyper_link:nn
  { \hyper@link { link }}
```

code 2
-
```yaml
lookForAlignDelims:
   geometry: 
      delimiterRegEx: '(=)'

specialBeginEnd:
    papersize:
        begin: '\{\h*[0-9]+'
        end: 'mm\h*\}'
    specialBeforeCommand: 1

indentRules:
  geometry:
    body: '  '
```
gives
```tex
\geometry
  {
	  papersize     = { 130mm , 184mm } ,
	  lines         = 25 ,
	  hmargin       = 15mm ,
	  bindingoffset = 5mm ,
	  headheight    = 10pt ,
	  headsep       = \baselineskip ,
	  includehead   = true ,
	  vcentering    = true
  }
```
code 3
-
```yaml
lookForAlignDelims:
   mybegin: 
      delimiterRegEx: '(=)'

specialBeginEnd:
    mybegin:
        begin: '\\mybegin'
        end: '\\myend'
```
gives
```tex
\geometry
\mybegin %%%%%%%% <-- can be customized begin and end
	papersize     = { 130mm , 184mm } ,
	lines         = 25 ,
	hmargin       = 15mm ,
	bindingoffset = 5mm ,
	headheight    = 10pt ,
	headsep       = \baselineskip ,
	includehead   = true ,
	vcentering    = true
\myend %%%%%%%% <-- can be customized begin and end
```

code 4
-
```yaml
lookForAlignDelims:
   l_maoxuan_headsep_dim: 
      delimiterRegEx: '(-)'
```
gives
```tex
\dim_set:Nn \l_maoxuan_headsep_dim
{
	\headsep - \box_ht:N \l_maoxuan_main_head_rule_box
	         - \box_dp:N \l_maoxuan_main_head_rule_box %%%%%%%% <-- this line need extra indent
}
```

code 5
-
```yaml
lookForAlignDelims:
   xeCJKsetup: 
      delimiterRegEx: '(=)'

indentRules:
  xeCJKsetup:
    body: '  '
```
gives
```tex
\xeCJKsetup
  {
	  AllowBreakBetweenPuncts = true ,
	  CheckSingle             = true ,
	  AutoFakeBold            = false ,
	  AutoFakeSlant           = false ,
	  CheckFullRight          = true ,
	  NewLineCS+              = \mxendarticle \item \mnitem
	  \maoxuan_endline_mark: , %%%%%%%% <-- this line need extra indent
	  NoBreakCS+              = \mnote ,
	  PunctStyle              = kaiming ,
	  KaiMingPunct+           = ：； ,
  }
```
I don't like the following, it's quite a hack, but
```yaml
lookForAlignDelims:
   xeCJKsetup: 
      delimiterRegEx: '(=)'

indentRules:
  xeCJKsetup:
    body: '  '
  mxendarticle: '                          '

specialBeginEnd:
    mxendarticle:
        begin: '\\mxendarticle'
        end: ','
```
gives
```tex
\xeCJKsetup
  {
	  AllowBreakBetweenPuncts = true ,
	  CheckSingle             = true ,
	  AutoFakeBold            = false ,
	  AutoFakeSlant           = false ,
	  CheckFullRight          = true ,
	  NewLineCS+              = \mxendarticle \item \mnitem
	                            \maoxuan_endline_mark: , %%%%%%%% <-- this line need extra indent
	  NoBreakCS+              = \mnote ,
	  PunctStyle              = kaiming ,
	  KaiMingPunct+           = ：； ,
  }
```

**Comment by ostaith** [comment]
Hi cmhughes,

Thanks for your quick reply.

1. I check this https://github.com/cmhughes/latexindent.pl/releases/tag/V3.14 link, but both standalone `latexindent.exe` and `latexindent.exe` in `latexindent.zip` are 64bit.

2. update, for rule `for latex3 code, can set such as 'add extra space' to each token to separate them.`, I expect latexindent can **add** extra space if two tokens are not separate, and **delete** redundant spaces if they have too many spaces:

   <pre>
   case 1: \token_one\token_two     --> \token_one \token_two % no space
   case 2: \token_one    \token_two --> \token_one \token_two % too many spaces
   </pre>

3. I found you already give some yaml rules, but these rules are specific. I expect some general rules, then I don't need for different code blocks add different rules.

**Comment by ostaith** [comment]
1. OK, I almost understand your `lookForAlignDelims` rule. Before I thought it can only used in `tabular` environment. I'll learn the section of `Aligning at delimiters` in `latexindex.pdf` again.

2. for the 'space separate' rule, I also try to understand solution firstly. but,
   1) what's the `body`'s mean in rule? I see many `body` in `latexindent.pdf`, and some even have regex,
      ```
      indentRules:
        geometry:
          body: '  '
      ```
   2) what's latexindent regex syntax? can u give the link in your documentation? for example your rule `s/\{\h*(\\|[a-z]|[A-Z])/\{ $1/sgx`, what `s/`, `\h`, `/sgx` mean? the `\h` looks like same as `\s`.

3. for standalone `latexindent.exe` in windows, seems the `-l` option is invalid. even I use `-l localSettings.yaml`, it still use the `defaultSettings.yaml`.

**Comment by cmhughes** [comment]
Thanks for this.

> I check this https://github.com/cmhughes/latexindent.pl/releases/tag/V3.14 link, but both standalone latexindent.exe and latexindent.exe in latexindent.zip are 64bit.

`latexindent.exe` is produced by [github actions](https://github.com/cmhughes/latexindent.pl/actions/workflows/build-documentation-and-windows-exe.yaml). If you have a way for it to produce a 32bit version, let me know.

> 
> case 1: \token_one\token_two     --> \token_one \token_two % no space
> case 2: \token_one    \token_two --> \token_one \token_two % too many spaces

We can adapt the code I provided above
```yaml
replacements:
  -
    substitution: |-
      s/([a-z]|[A-Z])\h*\\/$1 \\/sgx
    when: after
```
This means that a letter followed 0 or more spaces, followed by a `\` will be replaced by the letter, one space, and the backslash.

> I found you already give some yaml rules, but these rules are specific. I expect some general rules, then I don't need for different code blocks add different rules.

There are no general rules for this. You should be able to adapt the code I provided on a per-case basis.

> for the 'space separate' rule, I also try to understand solution firstly. but what's latexindent regex syntax? can u give the link in your documentation? for example your rule s/\{\h*(\\|[a-z]|[A-Z])/\{ $1/sgx, what s/, \h, /sgx mean?

The regex syntax is standard, it's not particular to `latexindent`. The `s/` means 'substitute', the `\h` means horizontal space, and the `sgx` are modifiers. You can read more about this at https://perldoc.perl.org/perlre, for example.

> for standalone latexindent.exe in windows, seems the -l option is invalid. even I use -l localSettings.yaml, it still use the defaultSettings.yaml:

I tested this on a Windows laptop, and was not able to reproduce this error.
