### ISSUE TITLE
Extra indent applied before \Else statement

### ISSUE THREAD

**Issue by avatar-lavventura** [cmhughes/latexindent.pl#328]
Indent is not correctly applied for `else` statements.

`code.tex`

```
\If{$p_n.isOverlap(j.startTime, completeTime, j.Core)$}
\State{}$j.\sigma \gets \mathrm{refunded}$
\Else{}
\State{}$j.deposit \gets j.deposit - (\mathrm{gain} + \mathrm{refund})$
\EndIf{}
```
--
yaml settings

```yaml
defaultIndent: "    "
verbatimEnvironments:
    longtable: 1
    tabularx: 1
specialBeginEnd:
  If:
    begin: '\\If'
    middle: '\\ElsIf'
    end: '\\EndIf'
    lookForThis: 1
  specialBeforeCommand: 1
```
--
*Please paste the output you receive here*

```
\If{$p_n.isOverlap(j.startTime, completeTime, j.Core)$}
    \State{}$j.\sigma \gets \mathrm{refunded}$
    \Else{}
    \State{}$j.deposit \gets j.deposit - (\mathrm{gain} + \mathrm{refund})$
\EndIf{}
```

desired or expected output
--
*Please paste your desired/expected output here; that is, what do you want the output to look like*

```
\If{$p_n.isOverlap(j.startTime, completeTime, j.Core)$}
    \State{}$j.\sigma \gets \mathrm{refunded}$
\Else{}
    \State{}$j.deposit \gets j.deposit - (\mathrm{gain} + \mathrm{refund})$
\EndIf{}
```

code example:

```c
if (cond):
    x = 1;
else
    x = 2;  
```

**Comment by cmhughes** [comment]
Thanks for this.

How about
```yaml
defaultIndent: "    "
specialBeginEnd:
  If:
    begin: '\\If'
    middle: 
        - '\\ElsIf'
        - '\\Else'
    end: '\\EndIf'
  specialBeforeCommand: 1
```
which gives
```tex
\If{$p_n.isOverlap(j.startTime, completeTime, j.Core)$}
    \State{}$j.\sigma \gets \mathrm{refunded}$
\Else{}
    \State{}$j.deposit \gets j.deposit - (\mathrm{gain} + \mathrm{refund})$
\EndIf{}
```
