### ISSUE TITLE
Avoid `.}` being split, or split it better

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#329]
original .tex code
```tex
    \caption{
        \textbf{\protect\subref*{fig:dep:a}.}
        Foo.
    }
```
yaml settings
```
onlyOneBackUp: 1
defaultIndent: "    "
removeTrailingWhitespace: 1
lookForAlignDelims:
   align: 0
modifyLineBreaks:
  textWrapOptions:
    columns: 100
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0
```
actual/given output
```tex
    \caption{
        \textbf{\protect\subref*{fig:dep:a}.
        }
        Foo.
    }
```
desired or expected output
```tex
    \caption{
        \textbf{\protect\subref*{fig:dep:a}.}
        Foo.
    }
```
or
```tex
    \caption{
        \textbf{
            \protect\subref*{fig:dep:a}.
        }
        Foo.
    }
```
