### ISSUE TITLE
Indent incorrectly removed

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#330]
Please provide the following when posting an issue:

original .tex code
```tex
and $z = \zeta$ (\cref{eq:z}) \footnote{
    We remark that:
    I)
    The fit of the prefactors.
    II)
    We have checked that
    III)
    $C_f = A / t = c_1^{-1} A^{1 - \zeta} \sim A^{0.37}$.
}.
```
yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: "    "
removeTrailingWhitespace: 1
lookForAlignDelims:
   align: 0
modifyLineBreaks:
  textWrapOptions:
    columns: 100
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0
```

actual/given output
```tex
and $z = \zeta$ (\cref{eq:z}) \footnote{
We remark that:
I)
The fit of the prefactors.
II)
We have checked that
III)
$C_f = A / t = c_1^{-1} A^{1 - \zeta} \sim A^{0.37}$.
}.
```
desired or expected output
```tex
and $z = \zeta$ (\cref{eq:z}) \footnote{
    We remark that:
    I)
    The fit of the prefactors.
    II)
    We have checked that
    III)
    $C_f = A / t = c_1^{-1} A^{1 - \zeta} \sim A^{0.37}$.
}.
```

**Comment by cmhughes** [comment]
Thanks for this.

This needs `fineTuning` for the `c_1^{-1}`, because we have a `namedGroupingBracesBrackets` that contains an underscore.

So, using
```yaml
fineTuning:
    namedGroupingBracesBrackets:
      name: '[0-9\.a-zA-Z@\*><_]+?'
```
gives the output
```tex
and $z = \zeta$ (\cref{eq:z}) \footnote{
	We remark that:
	I)
	The fit of the prefactors.
	II)
	We have checked that
	III)
	$C_f = A / t = c_1^{-1} A^{1 - \zeta} \sim A^{0.37}$.
}.
```
