### ISSUE TITLE
Compressing multiple blank spaces between words into one

### ISSUE THREAD

**Issue by musm** [cmhughes/latexindent.pl#336]
Is there a simple yaml setting I could turn on to compress spaces between words, such that
```
hello     world, my      name is    Joe
```
to 
```
hello world, my name is Joe
```

**Comment by cmhughes** [comment]
Yes, absolutely!

Try the following
```yaml
replacements:
  -
    substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
    when: before
  -
    substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
    when: after
```
You'll need to use one of the replacement switches, for example
```
latexindent.pl - rv myfile.tex 
```
