### ISSUE TITLE
`beforeFindingChildCodeBlocks` messing with `equation*`

### ISSUE THREAD

**Issue by haroldojunios** [cmhughes/latexindent.pl#337]
original .tex code
--
``` latex
\begin{equation*}
  f(X) = \int_{-\infty}^{X} p(X)~dX =
  \begin{cases}
    0, & X < -1 \\
    \frac{X + 1}{2}, & -1 < X < 1, \\
    1, & \text{caso contrário}
  \end{cases}
\end{equation*}

one
    two three four one
    two three four one
    two three four \test{test
  five six seven
eight nine} ten eleven
twelve thirteen
    fourteen fifteen sixteen seventeen
```

yaml settings
--
``` yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    beforeFindingChildCodeBlocks: 1
    all: 1
  removeParagraphLineBreaks:
    mainDocument: 1
    beforeTextWrap: 1
  environments:
    EndStartsOnOwnLine: 1
removeTrailingWhitespace:
  beforeTextWrap: 1
```

actual/given output
--
``` latex
\begin{equation*}
	f(X) = \int_{-\infty}^{X} p(X)~dX = \begin{cases} 0,     & X < -1      \\ \frac{X +
              1}{2}, & -1 < X < 1, \\ 1, & \text{caso contrário}
	\end{cases} \end{equation*}

one two three four one two three four one two three four \test{test five six
	seven eight nine} ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```

desired or expected output
--
``` latex
\begin{equation*}
  f(X) = \int_{-\infty}^{X} p(X)~dX =
  \begin{cases}
    0,               & X < -1                \\
    \frac{X + 1}{2}, & -1 < X < 1,           \\
    1,               & \text{caso contrário}
  \end{cases}
\end{equation*}

one two three four one two three four one two three four \test{test five six
	seven eight nine} ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```

anything else
--

If I remove the line containing `beforeFindingChildCodeBlocks` it gives me:

``` latex
\begin{equation*}
	f(X) = \int_{-\infty}^{X} p(X)~dX =
	\begin{cases}
		0,               & X < -1                \\
		\frac{X + 1}{2}, & -1 < X < 1,           \\
		1,               & \text{caso contrário}
	\end{cases}
\end{equation*}

one two three four one two three four one two three four \test{test
	five six seven
	eight nine}
ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```

It doesn't mess with the `equation*` environment, but the text inside the command `\test` isn't correctly formatted.

**Comment by cmhughes** [comment]
Thanks for this.

How about the following
```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    beforeFindingChildCodeBlocks: 0 #<!------ NEW
    all: 1
  removeParagraphLineBreaks:
    mainDocument: 1
    beforeTextWrap: 1
    mandatoryArguments: 1           #<!------ NEW
  environments:
    EndStartsOnOwnLine: 1
removeTrailingWhitespace:
  beforeTextWrap: 1
```
which gives
```tex
\begin{equation*}
	f(X) = \int_{-\infty}^{X} p(X)~dX =
	\begin{cases}
		0,               & X < -1                \\
		\frac{X + 1}{2}, & -1 < X < 1,           \\
		1,               & \text{caso contrário}
	\end{cases}
\end{equation*}

one two three four one two three four one two three four \test{test five six seven eight nine}
ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```

**Comment by haroldojunios** [comment]
This is a good solution, but it's not what I really want. I would like to have `beforeFindingChildCodeBlocks` set to 1 so the number of characters in lines with commands don't grow too big. Is it possible?

**Comment by cmhughes** [comment]
Ok, here's two more options:

option 1: using poly-switches
-
```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    beforeFindingChildCodeBlocks: 1
    all: 1
  removeParagraphLineBreaks:
    mainDocument: 1
    beforeTextWrap: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
    #equation*:                       # use these lines if you want
    #    BeginStartsOnOwnLine: 0      # per-name settings
    #    BodyStartsOnOwnLine: 0       #
    #    EndStartsOnOwnLine: 0        #
    #    EndFinishesWithLineBreak: 0  # 
removeTrailingWhitespace:
  beforeTextWrap: 1
```
this gives
```tex
\begin{equation*}
	f(X) = \int_{-\infty}^{X} p(X)~dX =
	\begin{cases}
		0,     & X < -1                \\
		\frac{X +
		1}{2}, & -1 < X < 1,           \\
		1,     & \text{caso contrário}
	\end{cases}
\end{equation*}

one two three four one two three four one two three four \test{test five six
	seven eight nine} ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```

option 2: using verbatim
-
```yaml
verbatimEnvironments:
    equation*: 1

modifyLineBreaks:
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    beforeFindingChildCodeBlocks: 1
    all: 1
  removeParagraphLineBreaks:
    mainDocument: 1
    beforeTextWrap: 1
removeTrailingWhitespace:
  beforeTextWrap: 1
```
gives
```tex
\begin{equation*}
  f(X) = \int_{-\infty}^{X} p(X)~dX =
  \begin{cases}
    0, & X < -1 \\
    \frac{X + 1}{2}, & -1 < X < 1, \\
    1, & \text{caso contrário}
  \end{cases}
\end{equation*}

one two three four one two three four one two three four \test{test five six
	seven eight nine} ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```

**Comment by haroldojunios** [comment]
The poly-switch option is good enough for me. Just one doubt, is it normal to the `\frac{X + 1}{2}, & -1 < X < 1, \\` line be splited in 2 lines using this approach?

**Comment by cmhughes** [comment]
If you perform `textWrapping` before finding code blocks, then it's a possibility. By using `beforeFindingChildCodeBlocks: 1` you're telling the script to do text wrapping before it knows anything about `\frac` and most other code blocks. The only thing the script knows about at this point is verbatim code blocks. 

As you can see, it's all quite intricate :)

**Comment by cmhughes** [comment]
You might like to try adding the following
```yaml
noIndentBlock:
    frac:
        begin: '\\frac\{
        body: '[^}]*?'
        end: '\}'
```
it should help to prevent the argument to frac being split.

**Comment by haroldojunios** [comment]
Thank you for your readiness and patience. It's such a great tool and you always answer us with kindness.

**Comment by haroldojunios** [comment]
Sorry for reopening this issue, but I noted something strange, with this code:

``` latex
\begin{equation*}
p(X) =
\begin{cases}
0.5, & -1 < X < 1, \\
0,   & \text{caso contrário}
\end{cases}
\end{equation*}
```

formatting with the "option 1: using poly-switches" it cycles, on reformatting, between

``` latex
\begin{equation*}
	p(X) =
	\begin{cases}
		0.5, & -1 < X < 1,           \\
		0,   & \text{caso contrário}
	\end{cases}
\end{equation*}
```

and

``` latex
\begin{equation*}
	p(X) =
	\begin{cases}
		0.5, & -1 < X < 1, \\
		0,   & \text{caso
			contrário}
	\end{cases}
\end{equation*}
```

The first is what I want, but every time that I format my document it changes this piece.

Obs. I also needed to put `DBSStartsOnOwnLine: -1` to not have the same cycling with the DBS going from same line to single line and back.

**Comment by cmhughes** [comment]
Apologies for the delay, I'm hoping to get to this soon.

**Comment by cmhughes** [comment]
Apologies for the delay. You'll see that in https://github.com/cmhughes/latexindent.pl/issues/346 I'm hoping to overhaul the textWrap routine, and your issue will be one of the many tests that I include within it. I'm unsure as to the time frame, development is slow at the moment. My apologies.

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/issues/346 I have overhauled the text wrap part of `latexindent.pl`.

starting file
-
```tex
\begin{equation*}
  f(X) = \int_{-\infty}^{X} p(X)~dX =
  \begin{cases}
    0, & X < -1 \\
    \frac{X + 1}{2}, & -1 < X < 1, \\
    1, & \text{caso contrário}
  \end{cases}
\end{equation*}

one
    two three four one
    two three four one
    two three four \test{test
  five six seven
eight nine} ten eleven
twelve thirteen
    fourteen fifteen sixteen seventeen
```
settings
-
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 80
```
output
-
```tex
\begin{equation*}
	f(X) = \int_{-\infty}^{X} p(X)~dX =
	\begin{cases}
		0,               & X < -1                \\
		\frac{X + 1}{2}, & -1 < X < 1,           \\
		1,               & \text{caso contrário}
	\end{cases}
\end{equation*}

one two three four one two three four one two three four \test{test five six
	seven eight nine} ten eleven twelve thirteen fourteen fifteen sixteen seventeen
```
I'll get V3.16 released soon.
