### ISSUE TITLE
Avoid formatting on specific line (without `.latexindent.yaml`

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#347]
I have a `*.cls` file in which `oneSentencePerLine` introduces an error. 
I would like to avoid formatting in this specific line of code without changing my `.latexindent.yaml` file, because I want downstream projects also to not touch this formatting. 

So I'm search for the equivalent of
```cpp
// clang-format off
...
// clang-format on
```
in clang-format (for C++). Or
```python
... # noqa: F401 
```
for flake8 (for Python).

original .tex code
```tex
\pretocmd{\chapter}{\renewcommand\thesection{\thechapter.\arabic{section}}}{}{}
```

yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align: 0

modifyLineBreaks:
  textWrapOptions:
    columns: 100
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0

fineTuning:
  namedGroupingBracesBrackets:
    name: '[0-9\.a-zA-Z@\*><_]+?'

# remove recurrent spaces
replacements:
- substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
  when: before
- substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
  when: after
```
actual/given output
```tex
\pretocmd{\chapter}{\renewcommand\thesection{\thechapter.%
        \arabic{section}}}{}{}
```
desired or expected output
```tex
\pretocmd{\chapter}{\renewcommand\thesection{\thechapter.\arabic{section}}}{}{}
```
