### ISSUE TITLE
`textWrapOptions` broken?

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#355]
Please provide the following when posting an issue:

original .tex code
```
This is a very long sentence that I would like to be cut at the set line width which is however currently not done. Sentences are put on different lines.
```
yaml settings
```yaml
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  condenseMultipleBlankLinesInto: 1
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0
  textWrapOptions:
    columns: 100
```
actual/given output
```tex
This is a very long sentence that I would like to be cut at the set line width which is however currently not done.
Sentences are put on different lines.
```
desired or expected output
```tex
This is a very long sentence that I would like to be cut at the set line width which is however 
currently not done.
Sentences are put on different lines.
```
Note that this is working with `latexindent.pl=3.15` but not with `latexindent.pl=3.16` neither `latexindent.pl=3.17`

**Comment by cmhughes** [comment]
Text wrapping and oneSentencePerLine are orthogonal processes....

If you want sentences wrapped, how about https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-sentence-wrap1-yaml

**Comment by tdegeus** [comment]
Thanks for you response. 

I don't think of them as orthogonal. Consider the following formatting rule:
1. Every sentence starts on a new line.
2. No line can exceed 100 characters.
3. Only format if 1 or 2 is violated. 
 
I don't think this can be done anymore? When I add `textWrapSentences: 1` then 3 is violated. But 2 is violated if I put `textWrapSentences: 0`.

**Comment by cmhughes** [comment]
OK, understood. I don't have access to a computer for a few days. I'll test this when I can.

**Comment by cmhughes** [comment]
So you want to text wrap some sentences but not others? Once you detail 
```yaml
    textWrapSentences: 1
```
you are saying 'employ the text wrapping routine on all sentences'. If you don't want that to happen, then the `lines` switch is for you. https://latexindentpl.readthedocs.io/en/latest/sec-the-line-switch.html

**Comment by cmhughes** [comment]
Or, are you saying that you'd like
```yaml
    removeSentenceLineBreaks: 0
```
to be employed by the *sentence text wrapping* routine as well? This is not currently the behaviour, but I could explore it.... 

----
For my reference, I think it would be the following line in `Wrap.pm`
https://github.com/cmhughes/latexindent.pl/blob/2198e4a70427114d20bddb1073e6970bbc249c02/LatexIndent/Wrap.pm#L228
and it would need a check to see if the object is a `sentence` and if `removeSentenceLineBreaks` is 1.

**Comment by tdegeus** [comment]
I'm not entirely sure, but I suppose. In pseudo-algorithm what I want is:
```
text = enforceSentenceStartsOnNewLine(text)
text = enforceHardWrapAtWidth(text, linewidth)
```

**Comment by cmhughes** [comment]
Yes, this already happens :)

But, the text wrap routine removes line breaks regardless of the value of removeSentenceLineBreaks.

If I've understood this, I need to change this so that removeSentenceLineBreaks is respected by text wrap.

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/25bbaf14cdefbe472571db5f2caca77c1c6f8398, I think that this is progressed. Here's a demo.

Starting with your text:
```tex
This is a very long sentence that I would like to be cut at the set line width which is however currently not done.
Sentences are put on different lines.
This is a very long sentence that is formatted like it should and it
should therefore not be touched by the formatter.
```
and using 
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0
    textWrapSentences: 1 
  textWrapOptions:
    columns: 100
```
gives
```tex
This is a very long sentence that I would like to be cut at the set line width which is however
currently not done.
Sentences are put on different lines.
This is a very long sentence that is formatted like it should and it
should therefore not be touched by the formatter.
```

Using 
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1 # <!============ different
    textWrapSentences: 1 
  textWrapOptions:
    columns: 100
```
gives
```tex
This is a very long sentence that I would like to be cut at the set line width which is however
currently not done.
Sentences are put on different lines.
This is a very long sentence that is formatted like it should and it should therefore not be
touched by the formatter.
```

What do you think?
