### ISSUE TITLE
Confusion: wrap test in caption of figure/table

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#357]
Sorry for posing a question again. I tried to resolve this with the docs, but I got a bit lost.

original .tex code
```tex
This is a very long sentence that should be wrapped at some point, which is the case in the main text, but not in captions.

\begin{table}[htp]
    \centering
    \caption{
        This is a very long sentence that should be wrapped at some point, which is the case in the main text, but not in captions.
    }
\end{table}
```

yaml settings
```yaml
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 0
    textWrapSentences: 1
  textWrapOptions:
    columns: 100
    blocksBeginWith:
      other: '\\caption'
    blocksFollow:
      other: |-
        (?x)
          \\\]
          |
          \\item(?:\h|\[)
          |
          \\begin|{figure\}
          |
          \\end|{figure\}
          \\begin|{table\}
          |
          \\end|{table\}
```

actual/given output
```tex
This is a very long sentence that should be wrapped at some point, which is the case in the main
text, but not in captions.

\begin{table}[htp]
    \centering
    \caption{
        This is a very long sentence that should be wrapped at some point, which is the case in the main text, but not in captions.
    }
\end{table}
```

desired or expected output
```tex
This is a very long sentence that should be wrapped at some point, which is the case in the main
text, but not in captions.

\begin{table}[htp]
    \centering
    \caption{
        This is a very long sentence that should be wrapped at some point, which is the case in the 
        main text, but not in captions.
    }
\end{table}
```

Ran with `pre-commit`
```yaml
repos:
- repo: https://github.com/cmhughes/latexindent.pl
  rev: V3.17.1
  hooks:
  - id: latexindent
    args: [-s, -wd, -l, -m, -r]
```
