### ISSUE TITLE
environment formatted inline

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#376]
Please provide the following when posting an issue:

original .tex code
```tex
For a slip event at interface $s$, we have $\Delta R_s > 0$ and $\Delta R_i = 0$ for $i \neq s$, inducing
\begin{equation}
    \label{eq:delta_fi}
    \Delta f_i = K\Delta R_s \,\, \mathrm{for} \,\, i \geq s ; \quad \Delta f_i=0 \,\, \mathrm{otherwise}.
\end{equation}
We can then deduce that
\begin{equation}
    \label{eq:DR_DF_multi}
    \Delta F = \frac{h K}{H} \Delta R_s \sum\limits_{i=s}^n i \, = \frac{h K}{H}\Delta R_s (n+s)(n-s+1) / 2.
\end{equation}
which we verify in \cref{fig:2c}.
```
yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align: 0

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
fineTuning:
  namedGroupingBracesBrackets:
    name: '[0-9\.a-zA-Z@\*><_]+?'

# remove recurrent spaces
replacements:
- substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
  when: before
- substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
  when: after
```

actual/given output
```tex
For a slip event at interface $s$, we have $\Delta R_s > 0$ and $\Delta R_i = 0$ for $i \neq s$, inducing \begin{equation} \label{eq:delta_fi} \Delta f_i = K\Delta R_s \,\, \mathrm{for} \,\, i \geq s ; \quad \Delta f_i=0 \,\, \mathrm{otherwise}.
\end{equation}
We can then deduce that \begin{equation} \label{eq:DR_DF_multi} \Delta F = \frac{h K}{H} \Delta R_s \sum\limits_{i=s}^n i \, = \frac{h K}{H}\Delta R_s (n+s)(n-s+1) / 2.
\end{equation}
which we verify in \cref{fig:2c}.

```

1. The equations are all formatted on the same line, which I don't want.2. 
2. A spurious white line is introduced at the end

desired or expected output
```tex
For a slip event at interface $s$, we have $\Delta R_s > 0$ and $\Delta R_i = 0$ for $i \neq s$, inducing
\begin{equation}
    \label{eq:delta_fi}
    \Delta f_i = K\Delta R_s \,\, \mathrm{for} \,\, i \geq s ; \quad \Delta f_i=0 \,\, \mathrm{otherwise}.
\end{equation}
We can then deduce that
\begin{equation}
    \label{eq:DR_DF_multi}
    \Delta F = \frac{h K}{H} \Delta R_s \sum\limits_{i=s}^n i \, = \frac{h K}{H}\Delta R_s (n+s)(n-s+1) / 2.
\end{equation}
which we verify in \cref{fig:2c}.
```

**Comment by cmhughes** [comment]
Thanks for this, I'll take a look soon and see what I can do :)

**Comment by cmhughes** [comment]
Thanks for this, and apologies for the delay.

why does this happen?
-
`latexindent.pl` defines a sentence as having to: 

- *follow* something,  see https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-sentencesfollow
- *begin* with something, see https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-sentencesbeginwith
- *end* with something see https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-sentencesendwith

So in your code, this means that 
```tex
For a slip event at interface $s$, we have $\Delta R_s > 0$ and $\Delta R_i = 0$ for $i \neq s$, inducing
\begin{equation}
    \label{eq:delta_fi}
    \Delta f_i = K\Delta R_s \,\, \mathrm{for} \,\, i \geq s ; \quad \Delta f_i=0 \,\, \mathrm{otherwise}.
```
is a sentence. So, with your code, the line breaks within this sentence will be removed.

what can we do? option 1
-
We can employ poly-switches to undo the line break removal using
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
  environments:                         # <----
      BeginStartsOnOwnLine: 1           # <----
      BodyStartsOnOwnLine: 1            # <---- NEW
  mandatoryArguments:                   # <----
      label:                            # <----
        RCuBFinishesWithLineBreak: 1    # <----
```
which gives
```tex
For a slip event at interface $s$, we have $\Delta R_s > 0$ and $\Delta R_i = 0$ for $i \neq s$, inducing
\begin{equation}
	\label{eq:delta_fi}
	\Delta f_i = K\Delta R_s \,\, \mathrm{for} \,\, i \geq s ; \quad \Delta f_i=0 \,\, \mathrm{otherwise}.
\end{equation}
We can then deduce that
\begin{equation}
	\label{eq:DR_DF_multi}
	\Delta F = \frac{h K}{H} \Delta R_s \sum\limits_{i=s}^n i \, = \frac{h K}{H}\Delta R_s (n+s)(n-s+1) / 2.
\end{equation}
which we verify in \cref{fig:2c}.
```
what can we do? option 2
-
We can tweak what a sentence is by saying that *sentences should end with `\begin{<something>}`*
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    sentencesEndWith:                   # <----
        other: |-                       # <----
          (?x) \\begin\{[a-zA-Z]+?\}    # <---- NEW
  environments:                         # <----
      BeginStartsOnOwnLine: 1           # <----
```
and in which case we receive, again,
```tex
For a slip event at interface $s$, we have $\Delta R_s > 0$ and $\Delta R_i = 0$ for $i \neq s$, inducing
\begin{equation}
	\label{eq:delta_fi}
	\Delta f_i = K\Delta R_s \,\, \mathrm{for} \,\, i \geq s ; \quad \Delta f_i=0 \,\, \mathrm{otherwise}.
\end{equation}
We can then deduce that
\begin{equation}
	\label{eq:DR_DF_multi}
	\Delta F = \frac{h K}{H} \Delta R_s \sum\limits_{i=s}^n i \, = \frac{h K}{H}\Delta R_s (n+s)(n-s+1) / 2.
\end{equation}
which we verify in \cref{fig:2c}.
```
other comments (your issue (2))
-
I couldn't replicate the behaviour you describe "spurious white line is introduced at the end"....

Does this help? Let me know :)
