### ISSUE TITLE
How can I keep same indent for foreach's end bracket and foreach

### ISSUE THREAD

**Issue by avatar-lavventura** [cmhughes/latexindent.pl#379]
I want end bracket to be same indent with start of `\foreach` , example:

```tex
\foreach ... in {...} {
...
}  # same place where `\foreach` starts
```

yaml setting:

```yaml
defaultIndent: "    "
verbatimEnvironments:
    longtable: 1
    tabularx: 1
    minted: 1
    item: 1
specialBeginEnd:
  If:
    begin: '\\If'
    middle:
        - '\\ElsIf'
        - '\\Else'
    end: '\\EndIf'
  specialBeforeCommand: 1
```
---

latexindent.pl keeps add a indent before the `}` and adds indent before the second line that follows up and also add 8 space indent inside the foreach block instead of 4 space indent.

```tex
\foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
        \node at (4.5, -\i) {\j};
    }
    \node[PR] at (3.48, -0.5) {};
         \node[PR] at (3.48, -1.5) {};
    \node[PR] at (3.48, -3.5) {};
        \node[PR] at (3.48, -1.5) {};
```

* desired or expected output

```tex
\foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
    \node at (4.5, -\i) {\j};  # 4 space instead of 8
}
\node[PR] at (3.48, -0.5) {};
\node[PR] at (3.48, -1.5) {};
\node[PR] at (3.48, -3.5) {};
\node[PR] at (3.48, -1.5) {};
```

**Comment by cmhughes** [comment]
Thanks for this, it was interesting!

solution
-
Put the following in your yaml settings, say `latexindent.yaml`
```yaml
commandCodeBlocks:
    stringsAllowedBetweenArguments:
      - 'in'                  # allows 'in' between arguments
      - '\\[a-z]\/\\[a-z]'    # allows any letter followed by / followed by another letter between arguments
noAdditionalIndent:
    foreach: 
        body: 1
```
and then run 
```
latexindent.pl -l myfile.tex
```
and you receive
```tex
\foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
	\node at (4.5, -\i) {\j};
}
\node[PR] at (3.48, -0.5) {};
\node[PR] at (3.48, -1.5) {};
\node[PR] at (3.48, -3.5) {};
\node[PR] at (3.48, -1.5) {};
```

explanation
-
* we allow `in` and `\i/\j` between arguments by using https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-commandcodeblocks
* we specify that we want `noAdditionalIndent` for the `foreach` command as demonstrated in, for example, https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-myenv-noadd5

I hope this helps, let me know if you have anything else! :)

**Comment by avatar-lavventura** [comment]
Thank you for your depth answer.

Please note that 

```yaml
specialBeginEnd:
  If:
    begin: '\\If'
    middle:
        - '\\ElsIf'
        - '\\Else'
    end: '\\EndIf'
  specialBeforeCommand: 1
```

was also causing this output that I shared in my question. Would it be possible to merge it with you answer?

**Comment by cmhughes** [comment]
Happy to help :)

In your code,  I see ` {\footnotesize $F^{};` and I think you're missing a few closing braces across a few lines.

Can you fix these and try again?

**Comment by avatar-lavventura** [comment]
Sorry I gave you the wrong code. Can you please have a look at to this:

```tex
        \foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
            \node at (4.5, -\i) {\j};
        }
        \node[PR] at (3.48, -0.5) {alper\\$\mathsf{J}$,$A$,...};
        \node[PR] at (3.48, -1.5) {\footnotesize $A$};
```

output:

```tex
\foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
    \node at (4.5, -\i) {\j};
}
\node[PR] at (3.48, -0.5) {alper\\$\mathsf{J}$,$A$,...};
        \node[PR] at (3.48, -1.5) {\footnotesize $A$};
```

Having `\\` in between the `{ }` is the main cause I believe

**Comment by cmhughes** [comment]
When I use the YAML I gave above, and run 
```
latexindent.pl -l myfile.tex
```
then I receive
```tex
\foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
	\node at (4.5, -\i) {\j};
}
\node[PR] at (3.48, -0.5) {alper\\$\mathsf{J}$,$A$,...};
\node[PR] at (3.48, -1.5) {\footnotesize $A$};
\node[PR] at (3.48, -1.5) {\footnotesize $B$};
```
This looks like your desired output. 

To make a minimal example, make a copy of your code, and strip it down until the problem is replicated.

**Comment by avatar-lavventura** [comment]
Interesting I am getting completely different output with following configuration, where I merge the one I give in my question with your answer:

```yam
defaultIndent: "    "
verbatimEnvironments:
    longtable: 1
    tabularx: 1
    minted: 1
    item: 1
specialBeginEnd:
  If:
    begin: '\\If'
    middle:
        - '\\ElsIf'
        - '\\Else'
    end: '\\EndIf'
  specialBeforeCommand: 1
commandCodeBlocks:
    stringsAllowedBetweenArguments:
      - 'in'                  # allows 'in' between arguments
      - '\\[a-z]\/\\[a-z]'    # allows any letter followed by / followed by another letter between arguments
noAdditionalIndent:
    foreach:
        body: 1
```

**Comment by cmhughes** [comment]
Interesting! 

The problem part was the combination of
```yaml
  specialBeforeCommand: 1
```
and the default settings for `inlineMath`:
```
inlineMath:
         begin: '(?<!\$)(?<!\\)\$(?!\$)'
         end: '(?<!\\)\$(?!\$)'
         lookForThis: 1
```
which says that `$` can not be preceeded by a backslash. 

We can change this by using
```yaml
specialBeginEnd:
    specialBeforeCommand: 1
    inlineMath:
        begin: '(?:\\\\\$)|(?:(?<!\$)(?<!\\)\$(?!\$))'     # <!------------ NEW BIT
        end: '(?<!\\)\$(?!\$)'
        lookForThis: 1
commandCodeBlocks:
    stringsAllowedBetweenArguments:
      - 'in'                  # allows 'in' between arguments
      - '\\[a-z]\/\\[a-z]'    # allows any letter followed by / followed by another letter between arguments
```
This says that `inlineMath` can begin with
* either `\\$`
* or `$` as long as it is not preceeded by a backslash.

This gives the output
```tex
\foreach \i/\j in {0.5/$H_{0}$, 1.5/$H_{0}$ } {
	\node at (4.5, -\i) {\j};
}
\node[PR] at (3.48, -0.5) {alper\\$\mathsf{J}$,$A$,...};
\node[PR] at (3.48, -1.5) {\footnotesize $A$};
\node[PR] at (3.48, -1.5) {\footnotesize $B$};
```
