### ISSUE TITLE
latexindent does not indent properly, add characters for regex capturing group

### ISSUE THREAD

**Issue by Leoriem-code** [cmhughes/latexindent.pl#380]
Original $\TeX$ code:
```tex
\begin{document}
\section{}
    \subsection*{I} We will have:\\
    Some text here

    \subsection*{II} But, there are many different cases,\\
    if \(m=1\), \[a=b+c\]
    else if \(m=2\), \[a^2=b^2+c^2\]
    other cases...
        \end{document}
```
YAML settings
--
(I tried to include only what is different from the default settings)
```yaml
defaultIndent: "    "
removeTrailingWhitespace:
    beforeProcessing: 0
    afterProcessing: 1
lookForAlignDelims:
    document:
        delims: 1
        alignDoubleBackSlash: 0
        spacesBeforeDoubleBackSlash: 1
specialBeginEnd:
    inlineMath:
        lookForThis: 0
indentAfterHeadings:
    section:
        indentAfterThisHeading: 1
        level: 3
    subsection*:
        indentAfterThisHeading: 0
        level: 4
noAdditionalIndent:
    document: 0
indentRules:
    section: "    "
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            other: ':\n|(\\\\)'
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 1
        SpecialEndFinishesWithLineBreak: 1
```
Actual output
--
```tex
\begin{document}
    \section{}
        \subsection*{I}
        We will have:
        Some text here 

    \subsection*{II} But, there are many different cases, \\
    \\
    if \(m=1\),
    \[a=b+c\]
    else if \(m=2\),
    \[a^2=b^2+c^2\]
    other cases...
\end{document}
```

desired or expected output
--
```tex
\begin{document}
    \section{}
        \subsection*{I} We will have:
        Some text here 

        \subsection*{II} But, there are many different cases, \\
        if \(m=1\),
        \[a=b+c\]
        else if \(m=2\),
        \[a^2=b^2+c^2\]
        other cases...
\end{document}
```

anything else
--
1. The command used is `latexindent -l -m file`.
2. The `\\` on line 8 of the actual output were added because in `settings`->`modifyLineBreaks`->`sentencesEndWith`->`other`, the regex expression make use of a capturing group `()`. When we use a non-capturing group `(?:)`, the `\\` are not added. You may want to look into this behavior.
3. As you can see when comparing line 3 on the actual and the desired output, the text after the `}` is sent to another line but it's not wanted. Which option do I need to change to stop this ?
4. It may be related to point 2, but on the actual output, from line 7 onwards, the indent is not correct. As you can see, it should be 8 spaces instead (4 for `\begin...\end...`, and 4 for `\section`). I think it's related because when I have the following settings, the indent for line 7 is still wrong but otherwise the indent if correct.
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            other: ':\n|\\\\'
```
gives
```tex
\begin{document}
    \section{}
        \subsection*{I}
        We will have:
        Some text here 

    \subsection*{II} But, there are many different cases, \\
        if \(m=1\),
        \[a=b+c\]
        else if \(m=2\),
        \[a^2=b^2+c^2\]
        other cases...
\end{document}
```

**Comment by cmhughes** [comment]
Thanks for this.

If I use 
```yaml
defaultIndent: "    "
removeTrailingWhitespace:
    beforeProcessing: 0
    afterProcessing: 1
lookForAlignDelims:
    document:
        delims: 0                       # <!--- NEW
        alignDoubleBackSlash: 0
        spacesBeforeDoubleBackSlash: 1
indentAfterHeadings:
    section:
        indentAfterThisHeading: 1
        level: 3
    subsection*:
        indentAfterThisHeading: 0
        level: 4
noAdditionalIndent:
    document: 0
indentRules:
    section: "    "
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
          other: '(?:\\\\)'         # <!--- NEW
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 1
        SpecialEndFinishesWithLineBreak: 1
```
then I receive
```tex
\begin{document}
    \section{}
        \subsection*{I}
        We will have:\\
        Some text here.

        \subsection*{II}
        But, there are many different cases,\\
        if \(m=1\),
        \[a=b+c\]
        else if \(m=2\),
        \[a^2=b^2+c^2\]
        other cases...
\end{document}
```
comments
-
* it's not clear why you would have `delims: 1` set for `document`....? This is intended for aligning at delimiter (like `tabular`, for example)
* I've used *non-capturing* groups `(?:)`, which is needed; using capturing groups breaks the algorithm. I've detailed this in the fine tuning section (https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html) but I accept that it could be highlighted in other places too
* from `latexindent.pl` point of view, sentences need to finish with something that you specify. So, in your code, the line that you have in your first `subsection*` that says `Some text here` does not end with anything. I've taken the liberty of adding a full stop to your original code as I'm assuming that, in practice, your sentence will finish with something. If that's not the case, and you need `latexindent.pl` to assume that sentences will not finish with a specific character, then let me know and I can look at it

I hope this helps, let me know.
