### ISSUE TITLE
Bracket block alone not (correctly) indented

### ISSUE THREAD

**Issue by vepain** [cmhughes/latexindent.pl#386]
### Subfile 1

```latex
% subfile.tex

{
text
}

{
{
text
}
}
```

### Subfile 2

```latex
% subfile_2.tex
\section{A section}

{
text
}

{
{
text
}
}
```

## YAML Settings

Default

### Subfile 1

```latex
% subfile.tex

{
text
}

{
{
        text
    }
}
```

### Subfile 2

```latex
% subfile_2.tex
\section{A section}

 { % note that there are 2 spaces while it should not be
  text
 }

 {
  {
          text
      }
 }
```

### Subfile 1

```latex
% subfile.tex

{
    text
}

{
    {
        text
    }
}
```

### Subfile 2

```latex
% subfile_2.tex
\section{A section}

{
    text
}

{
    {
        text
    }
}
```

**Comment by cmhughes** [comment]
Thanks for this, good questions :)

Subfile 1
-
We need to tell `latexindent.pl` to look for unnamed braces following a blank line; we can use
```yaml
fineTuning:
    UnNamedGroupingBracesBrackets:
      follow: '\{|\[|,|&|\)|\(|\$|\R'

noAdditionalIndentGlobal:
    UnNamedGroupingBracesBrackets: 1
```
which gives
```tex
% subfile.tex

{
	text
}

{
	{
		text
	}
}
```
See also https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-myenv-rules3 and https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-myenv-rules3

Subfile 2
-
You can use
```yaml
indentRules:
   section: 
      body: ""
      mandatoryArguments: "    "

noAdditionalIndentGlobal:
    UnNamedGroupingBracesBrackets: 1
```
which gives
```tex
% subfile_2.tex
\section{A section}

{ % note that there are 2 spaces while it should not be
    text
}

{
    {
	    text
    }
}
```
See also https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-myenv-rules3
