### ISSUE TITLE
Subscript bracket combined with superscript broke latexindent

### ISSUE THREAD

**Issue by vepain** [cmhughes/latexindent.pl#387]
## Original .tex code

```latex
% subfile.tex

\acommand{
L^+_{v}
}

\acommand{
L_v^{+}
}
```

## YAML settings

Default

## Actual/given output

```latex
% subfile/tex
\acommand{
L^+_{v}
}

\acommand{
L_v^{+}
}
```

## Desired or expected output

```latex
\acommand{
    L^+_{v}
}

\acommand{
     L_v^{+}
}
```

**Comment by cmhughes** [comment]
Thanks for this :)

We can use the `fineTuning` to help us with this
```yaml
fineTuning:
    namedGroupingBracesBrackets:
      name: '[0-9\.a-zA-Z@\*><_+^]+?'
```
which gives
```tex
% subfile.tex

\acommand{
	L^+_{v}
}

\acommand{
	L_v^{+}
}
```
See also https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html#lst-fine-tuning2
