### ISSUE TITLE
Indentation inside a command

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#391]
original .tex code
--
```latex
\documentclass{article}

\title{
My title
}

\begin{document}
BLA.

\begin{equation}
e = mc^2.
\end{equation}
\end{document}
```

yaml settings
--
```yaml
defaultIndent: "  "

noAdditionalIndentGlobal:
    commands: 0
```

actual/given output
--
```latex
\documentclass{article}

\title{
My title
}

\begin{document}
BLA.

\begin{equation}
  e = mc^2.
\end{equation}
\end{document}
```

desired or expected output
--
```latex
\documentclass{article}

\title{
  My title
}

\begin{document}
  BLA.

  \begin{equation}
    e = mc^2.
  \end{equation}
\end{document}
```

With the `commands` option, I was hoping to indent the contents of `\title{...}`. Also, I'm not sure if it's reasonable to expect that everything between `\begin{document}` and `\end{document}` be indented, but could you please point me to the option that would enable/disable it?

I use latexindent 3.19.1 on macOS installed via Homebrew.

Thank you in advance.

**Comment by cmhughes** [comment]
Thanks for this :) 

Perhaps the following might help
```yaml 
indentPreamble: 1
noAdditionalIndent:
    document: 0
```
Let me know!
