### ISSUE TITLE
Erroneous linebreak?

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#394]
Please provide the following when posting an issue:

original .tex code
--
```diff
-    By construction, \(\phi_{k,i}(x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\), \(\{\phi_{k,i}^>(x)\} \downarrow 0\) and \(\{\phi_{k,i}^<(x)\} \uparrow 0\) as \(k \to \infty\) for all \(x > 0\).
+    By construction, \(\phi_{k,i}
+    (x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\), \(\{\phi_{k,i}^>(x)\} \downarrow 0\) and \(\{\phi_{k,i}^<(x)\} \uparrow 0\) as \(k \to \infty\) for all \(x > 0\).
```

yaml settings
--
```yaml
indentPreamble: 1
defaultIndent: "  "

indentAfterHeadings:
    part:
       indentAfterThisHeading: 0
       level: 1
    chapter:
       indentAfterThisHeading: 0
       level: 2
    section:
       indentAfterThisHeading: 1
       level: 3
    subsection:
       indentAfterThisHeading: 1
       level: 4
    subsection*:
       indentAfterThisHeading: 1
       level: 4
    subsubsection:
       indentAfterThisHeading: 1
       level: 5
    paragraph:
       indentAfterThisHeading: 1
       level: 6
    subparagraph:
       indentAfterThisHeading: 1
       level: 7

noAdditionalIndent:
    document: 0

indentRules:
   chapter: " "
   section: "  "
   subsection: "  "
   paragraph: "  "
   item: "  "

dos2unixlinebreaks: 1

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            other: "\$|\\("
    # poly-switches below here
    environments:
        DBSStartsOnOwnLine: 0
        DBSFinishesWithLineBreak: 1
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 2
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
        equation*:
            BeginStartsOnOwnLine: 1
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 1
    specialBeginEnd:
        displayMath:
          SpecialBeginStartsOnOwnLine: 1
          SpecialBodyStartsOnOwnLine: 1
          SpecialEndStartsOnOwnLine: 1
          SpecialEndFinishesWithLineBreak: 1
```

actual/given output
--
See diff above.

desired or expected output
--
I would not expect a linebreak before `(x)`.

**Comment by cmhughes** [comment]
Can you strip the yaml down to minimal, please?

**Comment by dpo** [comment]
Sorry. I modified the post above to reflect my non-default settings.

**Comment by dpo** [comment]
The culprit seems to be
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            other: "\$|\\("
```

**Comment by cmhughes** [comment]
When I start with 
```tex
By construction, \(\phi_{k,i}(x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\), \(\{\phi_{k,i}^>(x)\} \downarrow 0\) and \(\{\phi_{k,i}^<(x)\} \uparrow 0\) as \(k \to \infty\) for all \(x > 0\).
```
and the settings
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            other: "\$|\\("
```
then I receive
```tex
By construction, \(\phi_{k,i}(x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\), \(\{\phi_{k,i}^>(x)\} \downarrow 0\) and \(\{\phi_{k,i}^<(x)\} \uparrow 0\) as \(k \to \infty\) for all \(x > 0\).
```
Your example does not demonstrate the problem. Please see [I've just been asked to write a minimal working example (MWE), what is that?](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that)] and ensure that code you post is *minimal* and demonstrates the problem.

**Comment by dpo** [comment]
Sorry. It seems the behavior occurs because of surrounding LaTeX code.

I boiled down the LaTeX code to this:
```latex
\begin{proof}
	Define
	\[
		x = 1.
	\]
	By construction, \(\phi_{k,i}(x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\).
\end{proof}
```
With
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            other: "\$|\\("
```
I obtain
```latex
\begin{proof}
	Define \[ x = 1.
	\]
	By construction, \(\phi_{k,i}
	(x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\).
\end{proof}
```

**Comment by cmhughes** [comment]
Thanks for more details.

solution
-
Using 
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            other: "\$|\\\\\("
```
gives
```tex
\begin{proof}
	Define \[ x = 1.
	\]
	By construction, \(\phi_{k,i}(x) = \phi_{k,i}^>(x) + \phi_{k,i}^<(x)\).
\end{proof}
```
I hope this as you would like. 

explanation
-
In your YAML you've specified
```yaml
 other: "\$|\\("
```
This is translated to mean "either $ or (". Note that "\\\(" translates to "(". 

We modify it to be
```yaml
other: "\$|\\\\\("
```
which is translated to mean "either $ or \\\(". Note that "\\\\" translates to "\\" so when followed by "\(" it translates literally into "\\\(".
