### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#395]
Sorry for ignoring the issue template. I just have some questions and since Discussions are not enabled in this repository, I don't know where else to ask them.

I was not able to find answers to the following questions in the documentation:

1. I like for `\quad` and `\qquad` to appear on their own line in certain math environments (`equation`, `equation*`/`\[ ... \]`, etc.). How can that be arranged? I suspect something with `specialBeginEnd`, but I don't see clearly how to formulate it.
2. I like for `\label{...}` to appear on its own line as well. How can that be arranged?
3. Is there a poly-switch for starred environments? For example, I use
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2
```
because I like my environments to have the form
```latex
\begin{bla}%
  \label{bla:mylabel}
  ...
\end{bla}
```
where I use the comment to preserve page numbers in references to the label.
But obviously, for starred environments, there won't be a label, and so I don't need the comment.
Thus I would like to use `BodyStartsOnOwnLine: 1` for them.
How can I achieve this without listing all starred environments explicitly?
Is there a
```yaml
modifyLineBreaks:
    environments*:   # <-- note the star
        BodyStartsOnOwnLine: 1
```
or something similar? Not a big deal, but I thought I would ask.

Many thanks in advance!

**Comment by cmhughes** [comment]
> Sorry for ignoring the issue template. 

It's not ideal; it means that I'm *guessing* as to what you want. This costs us both time, as there will be back and forth. It demonstrates my main concern with the 'discussions' area: questions and answers that are unspecified make for extra work.

> I like for \quad and \qquad to appear on their own line in certain math environments (equation, equation*/\[ ... \], etc.). How can that be arranged? I suspect something with specialBeginEnd, but I don't see clearly how to formulate it.

Starting with
```tex
\[
f(x)=3\quad g(x)=4\qquad h(x)=5
\]
```
and using 
```yaml
specialBeginEnd:
    displayMath:
        begin: \\\[
        end: \\\]
        middle:
           - \\quad
           - \\qquad
        lookForThis: 1

modifyLineBreaks:
    specialBeginEnd:
        SpecialMiddleStartsOnOwnLine: 1
        SpecialMiddleFinishesWithLineBreak: 1
```
gives
```tex
\[
	f(x)=3
\quad
	g(x)=4
\qquad
	h(x)=5
\]
```
See https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#id56 and https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-special2

Alternatively, using 
```yaml
modifyLineBreaks:
    commands:
      label:
        CommandStartsOnOwnLine: 1
    specialBeginEnd:
      quad:
        SpecialBeginStartsOnOwnLine: 1
        SpecialEndFinishesWithLineBreak: 1

specialBeginEnd:
    quad:
        begin: \\q+ua   # \\qua or \\qqua 
        end: d          # d
        lookForThis: 1              
```
gives
```tex
\[
	f(x)=3
	\quad
	g(x)=4
	\qquad
	h(x)=5
\]
```
> I like for \label{...} to appear on its own line as well. How can that be arranged?

Starting with 
```tex
\begin{equation}
  f(x)=3\quad g(x)=4\qquad h(x)=5\label{eq:cmh}
\end{equation}
```
and using 
```yaml
modifyLineBreaks:
    commands:
      label:
        CommandStartsOnOwnLine: 1
    specialBeginEnd:
      quad:
        SpecialBeginStartsOnOwnLine: 1
        SpecialEndFinishesWithLineBreak: 1

specialBeginEnd:
    quad:
        begin: \\q+ua   # \\qua or \\qqua 
        end: d          # d
        lookForThis: 1              
```
gives
```tex
\begin{equation}
	f(x)=3
	\quad
	g(x)=4
	\qquad
	h(x)=5
	\label{eq:cmh}
\end{equation}
```
See https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#poly-switches-for-other-code-blocks
> Is there a poly-switch for starred environments?

No, there is not. You would have to specify `environments`, which would cover every environment, or otherwise specify the starred environments individually.

**Comment by dpo** [comment]
Many thanks for indulging my questions! I still have an issue with `\label`.

Starting with
```latex
\begin{equation}%
	\label{eq:problem} \minimize{x} \ f(x).
\end{equation}
```
and
```yaml
modifyLineBreaks:
    commands:
        label:
            CommandStartsOnOwnLine: 1
            CommandNameFinishesWithLineBreak: 1
```
I get
```latex
\begin{equation}%
	\label{eq:problem} \minimize{x} \ f(x).
\end{equation}
```
whereas I was expecting
```latex
\begin{equation}%
	\label{eq:problem}
        \minimize{x} \ f(x).
\end{equation}
```

**Comment by cmhughes** [comment]
No problem :)

Using
```yaml
modifyLineBreaks:
    commands:
      label:
        CommandStartsOnOwnLine: 1
    mandatoryArguments:                     
        RCuBFinishesWithLineBreak: 1
```
gives
```tex
\begin{equation}%
	\label{eq:problem}
	\minimize{x}
	\ f(x).
\end{equation}
```

**Comment by dpo** [comment]
Thank you, but something more general seems to have happened here, where a line break is also inserted after another command (`\minimize`). Is there a way to insert a line break after `\label` only?

**Comment by cmhughes** [comment]
Perhaps the following:
```yaml
modifyLineBreaks:
    commands:
      label:
        CommandStartsOnOwnLine: 1
    mandatoryArguments:                   
      label:  
        RCuBFinishesWithLineBreak: 1
```
