### ISSUE TITLE
Extra comment?

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#398]
original .tex code
--
```latex
Some text with a command \citep[Theorem~\(10.1\)]{rtrw}
\begin{equation}%
	\label{eq:nlp-stationarity}
	0 \in \nabla f(x) + \partial (h + \chi(\cdot; \R^n_+))(x).
\end{equation}
```

yaml settings
--
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesBeginWith:
            other: "\$|\\\\\("
```

actual/given output
--
```latex
Some text with a command \citep[Theorem~\(10.1\)]{rtrw} \begin{equation} \label{eq:nlp-stationarity} 0 \in \nabla f(x) + \partial (h + \chi(\cdot; \R^n_+))(x).
	%
\end{equation}
```

desired or expected output
--
```latex
Some text with a command \citep[Theorem~\(10.1\)]{rtrw} \begin{equation} \label{eq:nlp-stationarity} 0 \in \nabla f(x) + \partial (h + \chi(\cdot; \R^n_+))(x).
\end{equation}
```

Where does that final `%` come from?
