### ISSUE TITLE
BodyStartsOnOwnLine: 2

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#399]
Starting with
```latex
\begin{lemma} This is a lemma. \end{lemma}
```
and
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2
```
we obtain
```latex
\begin{lemma}%
	This is a lemma. \end{lemma}
```
as documented.

However, if we start with
```latex
\begin{lemma}
	This is a lemma.
\end{lemma}
```
no `%` is appended after `\begin{lemma}`.
Is there another option for one to be appended?
It'd be useful when `\begin{lemma}` is followed by a `\label{...}` to preserve page number references.

**Comment by cmhughes** [comment]
Thanks for this.

The poly-switche value of 2 will only activate if a line break is needed to be added. If you want to replace all occurrences of `\begin{lemma}` with `\begin{lemma}%` then you can use the replacement switch, as detailed in https://latexindentpl.readthedocs.io/en/latest/sec-replacements.html#examples-of-replacements

For example, using the following in `latexindent.yaml`
```yaml
replacements:
  -
    amalgamate: 0
  -
    substitution: |-
        s/\\begin\{lemma\}\h*\R/\\begin{lemma\}%\n/sg
    when: before
```
and running
```
latexindent.pl -l -r myfile.tex
```
gives
```tex
\begin{lemma}%
	This is a lemma.
\end{lemma}
```
Note that `\\R` means line break.

Another alternative, if you want a more general solution:
```yaml
replacements:
  -
    amalgamate: 0
  -
    substitution: |-
        s/(\\begin\{[^}]+?\})\h*\R/$1%\n/sg
    when: before
```
Note that `\\begin\{[^}]+?\}` means `\\begin` followed by `{` then any character _except_ `}` and then `}`.

**Comment by dpo** [comment]
Thank you. Things are getting increasingly complicated.

In fact, I'm all confused because this doesn't work: starting with
```latex
\begin{lemma} This is a lemma. \end{lemma}
```
and
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
    environments:
        BodyStartsOnOwnLine: 2
```
(i.e., I added `manipulateSentences: 1`), results in no `%` being added:
```latex
\begin{lemma}
	This is a lemma.
\end{lemma}
```
