### ISSUE TITLE
log file preferences

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#40]
```
logFilePreferences:
       traceModeShowsPerlModuleLocations: 1
       showEveryYamlRead: 1
       showAlmagamatedSettings: 0
       traceModeIncreaseIndent: '>>>>>>'
       traceModeDecreaseIndent: '<<<<<<'
       traceModeBetweenLines: '\n'
       endLogFileWith: 
```
