### ISSUE TITLE
Verbatim command on new lines fails on some inputs (and other inconsistencies)

### ISSUE THREAD

**Issue by ankitp94** [cmhughes/latexindent.pl#400]
Please provide the following when posting an issue:

original .tex code
--
```
One that \begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align} Alpha beta gamma can choosing a The quick brown
fox jumps over the lazy dog.
```

 
yaml settings
--
Only mentioning the relevant code below. Changed lines are highlighted as # <------
```
verbatimEnvironments:
    align: 1 # <------
    align*: 1 # <------

modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    oneSentencePerLine:
        manipulateSentences: 1 # <------
        removeSentenceLineBreaks: 1
        multipleSpacesToSingle: 1
        textWrapSentences: 1   # setting to 1 disables main textWrap routine  <------
        sentenceIndent: ""
        sentencesFollow:
            par: 1
            blankLine: 1
            fullStop: 1
            exclamationMark: 1
            questionMark: 1
            rightBrace: 1
            commentOnPreviousLine: 1
            other: 0
        sentencesBeginWith:
            A-Z: 1
            a-z: 0
            other: 0
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 1
            exclamationMark: 1
            questionMark: 1
            other: 0
    textWrapOptions:
        columns: 80 # <------
    environments:
        BeginStartsOnOwnLine: 1 # <------
        BodyStartsOnOwnLine: 1 # <------
        EndStartsOnOwnLine: 1 # <------
        EndFinishesWithLineBreak: 1
        DBSFinishesWithLineBreak: 0 # <------
    commands:
        label:  # <------
            CommandStartsOnOwnLine: 1 # <------
        CommandStartsOnOwnLine: 0
        CommandNameFinishesWithLineBreak: 0
    optionalArguments:
        LSqBStartsOnOwnLine: 0
        OptArgBodyStartsOnOwnLine: 0
        RSqBStartsOnOwnLine: 0
        RSqBFinishesWithLineBreak: 0
    mandatoryArguments:
        LCuBStartsOnOwnLine: 0
        MandArgBodyStartsOnOwnLine: 0
        RCuBStartsOnOwnLine: 0
        RCuBFinishesWithLineBreak: 0
        label:  
            RCuBFinishesWithLineBreak: 1
    verbatim:
        VerbatimBeginStartsOnOwnLine: 1 # <------
        VerbatimEndFinishesWithLineBreak: 1 # <------
```

actual/given output
--
```
One that \begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align} Alpha beta gamma can choosing a The quick brown
fox jumps over the lazy dog.

```
desired or expected output
--
```
One that 
\begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align} 
Alpha beta gamma can choosing a The quick brown
fox jumps over the lazy dog.

```
---
# Inconsistencies Across Examples

There are some inconsistencies in the way the script works. 

If the previous sentence ends with a period, then the script works as intended. For example, the following input
```
One that. \begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align} Alpha beta gamma can choosing a The quick brown
fox jumps over the lazy dog.


```
gives the following output:

```
One that.
\begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align}
Alpha beta gamma can choosing a The quick brown
fox jumps over the lazy dog.
```

Similarly, the following input produces the desired outcome:
```
One that \begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align} Alpha beta gamma

```
giving the following output:
```
One that
\begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align}
Alpha beta gamma

```

--
Thank you so much for your effort in creating this script! Please me know if I can provide more information. (I am using the latest release from Github: `3.19.1` on Windows)

**Comment by cmhughes** [comment]
Thanks for this.

Your question is focused on the `oneSentencePerLine` feature, and we can strip your settings down to the following to re-create the behaviour:
```yaml
verbatimEnvironments:
    align: 1 # <------

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1 # <------
    verbatim:
        VerbatimBeginStartsOnOwnLine: 1 # <------
        VerbatimEndFinishesWithLineBreak: 1 # <------
```

To understand this, we need to understand that the process ordering is:

1. find `verbatim` blocks, and perform poly-switch _adding_ of line breaks
2. perform `oneSentencePerLine` routine, which _removes_ line breaks within sentences

From `latexindent` point of view, it has found a sentence, and has _removed_ the sentence line breaks. 

There are a couple of things you can set to influence this.

option 1: set `removeSentenceLineBreaks: 0 `
-

```yaml
verbatimEnvironments:
    align: 1 

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1 
        removeSentenceLineBreaks: 0         # <!--- option 1
    verbatim:
        VerbatimBeginStartsOnOwnLine: 1 
        VerbatimEndFinishesWithLineBreak: 1 
```
gives
```tex
One that
\begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align}
Alpha beta gamma can choosing a The quick brown
fox jumps over the lazy dog.
```

option 2: use a higher poly-switch value
-
```yaml
verbatimEnvironments:
    align: 1 # <------

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1 
    verbatim:
        VerbatimBeginStartsOnOwnLine: 3     # <!--- option 2
        VerbatimEndFinishesWithLineBreak: 3 # <!--- option 2
```
gives
```tex
One that 

\begin{align}
    a\begin{cases}
     b    \end{cases}.
\end{align} 

Alpha beta gamma can choosing a The quick brown fox jumps over the lazy dog.
```
