### ISSUE TITLE
`\label` on separate line in `equation`

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#401]
original .tex code
```tex
This is a sentence
\begin{equation}
    a = b
    \label{eq:foo}
\end{equation}
that stops here.
```

yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align: 0

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    multipleSpacesToSingle: 1
  items:
    ItemFinishesWithLineBreak: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
indentRules:
  item: '    '
fineTuning:
  namedGroupingBracesBrackets:
    name: '[0-9\.a-zA-Z@\*><_]+?'

# remove recurrent spaces
replacements:
- substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
  when: before
- substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
  when: after
```

actual/given output
```tex
This is a sentence
\begin{equation}
    a = b \label{eq:foo}
\end{equation}
that stops here.
```

desired or expected output
```tex
This is a sentence
\begin{equation}
    a = b
    \label{eq:foo}
\end{equation}
that stops here.
```

**Comment by cmhughes** [comment]
Many thanks.

Please use the issue template, it helps me understand what you're starting
with and what you want to get to.

**Comment by tdegeus** [comment]
ok. edited

**Comment by cmhughes** [comment]
Can you look at the solution in https://github.com/cmhughes/latexindent.pl/issues/395

**Comment by cmhughes** [comment]
```yaml
modifyLineBreaks:
    commands:
      label:
        CommandStartsOnOwnLine: 1
```
