### ISSUE TITLE
`DBSFinishesWithLineBreak: 1` confused

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#402]
original .tex code
```tex
This is some text. That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b \\
            c = d
        \end{split}
    \end{equation}
}
that ends here.
```

yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align: 0

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    multipleSpacesToSingle: 1
  items:
    ItemFinishesWithLineBreak: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
indentRules:
  item: '    '
fineTuning:
  namedGroupingBracesBrackets:
    name: '[0-9\.a-zA-Z@\*><_]+?'

# remove recurrent spaces
replacements:
- substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
  when: before
- substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
  when: after
```

actual/given output
```tex
This is some text.
That needs formatting \detail{
    \begin{equation}
        \begin{split}
            a = b \\ c = d
        \end{split}
    \end{equation}
} that ends here.
```

desired or expected output
```tex
This is some text.
That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b \\
            c = d
        \end{split}
    \end{equation}
}
that ends here.
```

**Comment by cmhughes** [comment]
Please use the issue template, then I'll look at it.

**Comment by tdegeus** [comment]
ok. edited.

**Comment by cmhughes** [comment]
Starting with
```tex
This is some text. That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b \\
            c = d
        \end{split}
    \end{equation}
}
that ends here.
```
and using
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
  commands:                        # <!--- NEW BIT
    detail:                        # <!--- NEW BIT
      CommandStartsOnOwnLine: 1    # <!--- NEW BIT
  mandatoryArguments:              # <!--- NEW BIT
    detail:                        # <!--- NEW BIT
      RCuBFinishesWithLineBreak: 1 # <!--- NEW BIT
```
gives
```tex
This is some text.
That needs formatting
\detail{
	\begin{equation}
		\begin{split}
			a = b \\ c = d
		\end{split}
	\end{equation}
}
that ends here.
```

**Comment by cmhughes** [comment]
Oh, and if you want the `DBSFinishesWithLineBreak` to activate, then you need to use
```yaml
lookForAlignDelims:
  split: 1
```
Here's the complete YAML

```yaml
lookForAlignDelims:
  split: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
  commands:                        # <!--- NEW BIT
    detail:                        # <!--- NEW BIT
      CommandStartsOnOwnLine: 1    # <!--- NEW BIT
  mandatoryArguments:              # <!--- NEW BIT
    detail:                        # <!--- NEW BIT
      RCuBFinishesWithLineBreak: 1 # <!--- NEW BIT
```
then you receive
```tex
This is some text.
That needs formatting
\detail{
	\begin{equation}
		\begin{split}
			a = b \\
			c = d
		\end{split}
	\end{equation}
}
that ends here.
```

**Comment by tdegeus** [comment]
Thanks. However, it does not work for me:
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align: 0

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    multipleSpacesToSingle: 1
  mandatoryArguments:
    footnote:
      MandArgBodyStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 1
    detail:
      MandArgBodyStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 1
  commands:
    label:
      CommandStartsOnOwnLine: 1
    detail:
      CommandStartsOnOwnLine: 1
  items:
    ItemFinishesWithLineBreak: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
indentRules:
  item: '    '
fineTuning:
  namedGroupingBracesBrackets:
    name: '[0-9\.a-zA-Z@\*><_]+?'

# remove recurrent spaces
replacements:
- substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
  when: before
- substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
  when: after
```
formats to
```tex
This is some text.
That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b \\ c = d
        \end{split}
    \end{equation}
}
that ends here.
```

**Comment by cmhughes** [comment]
You need this bit
```yaml
lookForAlignDelims:
  split: 1
```
to give
```tex
This is some text.
That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b \\
            c = d
        \end{split}
    \end{equation}
}
that ends here.
```

**Comment by tdegeus** [comment]
I see, thanks. It is not exactly what I hoped to have, that is that 
```tex
This is some text. That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b + c \\
            d = e \\
            f = g
        \end{split}
    \end{equation}
}
that ends here.
```
would not be formatted with
```yaml
lookForAlignDelims:
  align: 0
  split: 0

modifyLineBreaks:
  environments:
    DBSFinishesWithLineBreak: 1
```
both `split` and `equation` are an environment, so I would expect the double backslash to be forced to have a line break. Instead, it is formatted to 
```tex
This is some text.
That needs formatting
\begin{equation}
    \begin{split}
        a = b + c \\ d = e \\ f = g
    \end{split}
\end{equation}
that ends here.
```
which I would say to contradict the `DBSFinishesWithLineBreak: 1`.

------

What does work as expected (though not what I wanted), is that with
```yaml
lookForAlignDelims:
  align: 1
  split: 1

modifyLineBreaks:
  environments:
    DBSFinishesWithLineBreak: 1
```
the text is formatted to:
```tex
This is some text.
That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b + c \\
            d = e     \\
            f = g
        \end{split}
    \end{equation}
}
that ends here.

**Comment by tdegeus** [comment]
Ok I got it:
```yaml
lookForAlignDelims:
  align:
    delims: 1
    alignDoubleBackSlash: 0
  split:
    delims: 1
    alignDoubleBackSlash: 0
```
but I'm still a bit confused that `DBSFinishesWithLineBreak` did not do it.

**Comment by cmhughes** [comment]
Great, thanks.

I'm going to consider this a feature request: see if it's possible to enable `DBS` poly-switches can work _without_ requiring `lookForAlignDelims`. 

This came up in https://github.com/cmhughes/latexindent.pl/issues/393 from @ankitp94. I'd hope this won't take too long, but I'm currently working on text wrapping.

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/3ef192c9a08ff79ede947f21508f68739e0b3d87, this is implemented. Specifically, there is now no longer a need to specify a code block within `lookForAlignDelims`.

This will be part of the next release (early 2023), let's leave this open until then. Demonstrations below.

demonstration 1
-
starting with
```tex
This is some text. That needs formatting
\detail{
    \begin{equation}
        \begin{split}
            a = b \\
            c = d
        \end{split}
    \end{equation}
}
that ends here.
```
and using
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    textWrapSentences: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
```
gives
```tex
This is some text.
That needs formatting \detail{
    \begin{equation}
        \begin{split}
            a = b \\
            c = d
        \end{split}
    \end{equation}
} that ends here.
```

demonstration 2
-
starting with 
```tex
This is some text.
That needs formatting
\[
        a = b + c \\ d = e \\ f = g
\]
that ends here.
```
and using
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    textWrapSentences: 1
  specialBeginEnd:
    DBSFinishesWithLineBreak: 2
    SpecialBeginStartsOnOwnLine: 1
    SpecialBodyStartsOnOwnLine: 1
    SpecialEndStartsOnOwnLine: 1
    SpecialEndFinishesWithLineBreak: 1
```
gives
```tex
This is some text.
That needs formatting
\[
    a = b + c \\%
    d = e \\%
    f = g
\]
that ends here.
```
demonstration 3
-
starting with
```tex
This is some text.
That needs formatting
\cmh{
        a = b + c \\ d = e \\ f = g
      }
that ends here.
```
and using 
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    textWrapSentences: 1
  mandatoryArguments:                     
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 1
      DBSFinishesWithLineBreak: 2
```
gives
```tex
This is some text.
That needs formatting \cmh{
    a = b + c \\%
    d = e \\%
    f = g
}
that ends here.
```
