### ISSUE TITLE
Better separation of e.g. `\footnote`

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#403]
original .tex code
```tex
This has some note~\footnote{
    This is my footnote.
} that I want to highlight.

But I want to also encode some details \detail{
    That I also want to highlight.
}.
```

yaml settings
```
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align: 0

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    multipleSpacesToSingle: 1
  items:
    ItemFinishesWithLineBreak: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
indentRules:
  item: '    '
fineTuning:
  namedGroupingBracesBrackets:
    name: '[0-9\.a-zA-Z@\*><_]+?'

# remove recurrent spaces
replacements:
- substitution: s/([a-zA-Z0-9.}{])\h{2,}([a-zA-Z0-9.}{])/$1 $2/sg
  when: before
- substitution: s/([a-zA-Z0-9.()}{])\h{2,}([a-zA-Z0-9.()}{]|(?:\\(?!\\)))/$1 $2/sg
  when: after
```

actual/given output
```tex
This has some note~\footnote{ This is my footnote.
} that I want to highlight.

But I want to also encode some details \detail{ That I also want to highlight.
}.
```

desired or expected output
```tex
This has some note~\footnote{
    This is my footnote.
} that I want to highlight.

But I want to also encode some details \detail{
    That I also want to highlight.
}.
```

**Comment by cmhughes** [comment]
Please use the issue template, then I'll look at it.

**Comment by tdegeus** [comment]
edited

**Comment by cmhughes** [comment]
Starting with 
```tex
This has some note~\footnote{
    This is my footnote.
} that I want to highlight.

But I want to also encode some details \detail{
    That I also want to highlight.
}.
```
and using 
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
  mandatoryArguments:               # <!--- NEW BIT
    footnote:                       # <!--- NEW BIT
      MandArgBodyStartsOnOwnLine: 1 # <!--- NEW BIT
    detail:                         # <!--- NEW BIT
      MandArgBodyStartsOnOwnLine: 1 # <!--- NEW BIT
```
gives
```tex
This has some note~\footnote{
	This is my footnote.
} that I want to highlight.

But I want to also encode some details \detail{
	That I also want to highlight.
}.
```
You could also use
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
  mandatoryArguments:               # <!--- NEW BIT
    MandArgBodyStartsOnOwnLine: 1 # <!--- NEW BIT
````
