### ISSUE TITLE
How to only indent code inside a specified block

### ISSUE THREAD

**Issue by m-zheng** [cmhughes/latexindent.pl#405]
Thanks for making such a nice tool. 

I would like to only indent code inside a specified block. For example, I want to keep everything unchanged except the code inside the `\begin{tabular} blablabla \end{tabular}` being indented.

original .tex code
--
```tex
\chapter{Chapter1}
\ifpdf
    \graphicspath{{Chapter1/Figs/PDF/}}
\else
    \graphicspath{{Chapter1/Figs/Vector/}{Chapter1/Figs/}}
\fi
\section{Aim and objectives}
\begin{enumerate}
\item bla
\item bla
\end{enumerate}

\begin{table}[h!]
\centering
\begin{tabular}
	\hline
	Bla & \bf{1} & 1 \\ 
	Bla & 1 & 1     \\ \hline
\end{tabular}
\end{table}
```

yaml settings
--
```
noAdditionalIndentGlobal:
    environments: 1
    commands: 1
    optionalArguments: 1
    mandatoryArguments: 1
    ifElseFi: 1
    items: 1
    keyEqualsValuesBracesBrackets: 1
    namedGroupingBracesBrackets: 1
    UnNamedGroupingBracesBrackets: 1
    specialBeginEnd: 1
    afterHeading: 1
    filecontents: 1

indentRules:
    tabular: "\t"
```

actual/given output
--
```tex
\chapter{Chapter1}
\ifpdf
\graphicspath{{Chapter1/Figs/PDF/}}
\else
\graphicspath{{Chapter1/Figs/Vector/}{Chapter1/Figs/}}
\fi
\section{Aim and objectives}
\begin{enumerate}
\item bla
\item bla
\end{enumerate}

\begin{table}[h!]
\centering
\begin{tabular}
	\hline
	Bla & \bf{1} & 1 \\
	Bla & 1      & 1 \\ \hline
\end{tabular}
\end{table}
```
desired or expected output
--
```tex
\chapter{Chapter1}
\ifpdf
    \graphicspath{{Chapter1/Figs/PDF/}}
\else
    \graphicspath{{Chapter1/Figs/Vector/}{Chapter1/Figs/}}
\fi
\section{Aim and objectives}
\begin{enumerate}
\item bla
\item bla
\end{enumerate}

\begin{table}[h!]
\centering
\begin{tabular}
	\hline
	Bla & \bf{1} & 1 \\
	Bla & 1      & 1 \\ \hline
\end{tabular}
\end{table}
```

anything else
--
I checked the issue [348](https://github.com/cmhughes/latexindent.pl/issues/348) and your [comments](https://github.com/cmhughes/latexindent.pl/issues/391#issuecomment-1345511972). But no luck. Any help would be appreciated.
