### ISSUE TITLE
Finetuning betterFullStop

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#406]
It seems logical to keep `\emph{...?}` on one line. Consider:

original .tex code
```tex
An example: \emph{Is this a question?}
Another sentence.
```
yaml settings
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
```

actual/given output
```tex
An example: \emph{Is this a question?
}
Another sentence.
```
desired or expected output
```tex
An example: \emph{Is this a question?}
Another sentence.
```

---

A similar example
```
This is barely (not?) important.
```
which is currently formatted to 
```
This is barely (not?
) important.
```
which is also a bit strange potentially.

**Comment by cmhughes** [comment]
Thanks for using the template.

You'll need to tweak the settings so that a '?' followed by  a '}' isn't a
sentence.

Or, otherwise, set the poly switch so that the final brace removes the line
break.

I can look at this later if helpful, or if the above gives you what you
need, let me know.

**Comment by cmhughes** [comment]
Maybe something like
```yaml
sentencesEndWith:
            questionMark: 0                 # 0/1
            other: (?: \? (?! \)))              # regex
```

**Comment by tdegeus** [comment]
Thanks. I was experimenting a bit with a simpler regex and a workaround in the text, so I put
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
    sentencesEndWith:
      basicFullStop: 0
      betterFullStop: 0
      exclamationMark: 0
      questionMark: 0
      other: '[\.?!%][\ \n]'
```
but this formats
```tex
An example: \emph{Is this a question?}%
Another sentence.
```
Into something completely unexpected for me:
```tex
An example: \emph{Is this a question?} Another sentence.
%
```
what is going on here?

**Comment by cmhughes** [comment]
OneSentencePerLine puts all comments on next line. One sentence per line.

**Comment by cmhughes** [comment]
Starting with 
```tex
An example: \emph{Is this a question?}
Another sentence.

This is barely (not?) important.
```
and using the settings
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
    sentencesEndWith:
        questionMark: 0         # 0/1
        other: |-
          (?x)
          \?                    # ?
          (?!                   # not *followed by*
            (?:                 #
              \)                # )
              |                 #
              \}                # }
            )                   #
          )                     #
```
gives 
```tex
An example: \emph{Is this a question?} Another sentence.

This is barely (not?) important.
```
I hope this is as you would like.

**Comment by tdegeus** [comment]
> OneSentencePerLine puts all comments on next line. One sentence per line.

I see. However, it seems that this cannot be modified.
```yaml
  textWrapOptions:
    comments:
      wrap: 0
```
does not change anything to the behaviour.
