### ISSUE TITLE
headers should not be broken by oneSentencePerLine

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#408]
Please provide the following when posting an issue:

original .tex code
```tex
\section{A? B?}

\section{C? D?}
```

yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

lookForAlignDelims:
  align:
    alignDoubleBackSlash: 0
  split:
    alignDoubleBackSlash: 0

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
indentRules:
  item: '    '
```

actual/given output
```tex
\section{A?
  B?
 }

\section{C?
  D?
 }
```

desired or expected output
```tex
\section{A? B?}

\section{C? D?}
```
