### ISSUE TITLE
helping oneSentencePerLine manually

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#409]
Please provide the following when posting an issue:

original .tex code
```
\emph{First sentence?} Second (third?) sentence? \emph{Third sentence?} Fourth sentence?
```

yaml settings
```
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
```

actual/given output
```
\emph{First sentence?}
Second (third?
) sentence? \emph{Third sentence?}Fourth sentence?
```

desired or expected output
```
\emph{First sentence?} 
Second (third?) sentence? 
\emph{Third sentence?} 
Fourth sentence?
```

anything else

As observed, the output of this example is quite a mess. The second sentence is broken where is grammatically should not have been, whereas the third and fourth sentences are not broken and even merged.

There is the solution of https://github.com/cmhughes/latexindent.pl/issues/406 to have 
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
    sentencesEndWith:
        questionMark: 0         # 0/1
        other: |-
          (?x)
          \?                    # ?
          (?!                   # not *followed by*
            (?:                 #
              \)                # )
              |                 #
              \}                # }
            )                   #
          )                     #
```
which formats the original example somewhat better
```tex
\emph{First sentence?}
Second (third?) sentence?
\emph{Third sentence?}Fourth sentence?
```
but still not what I desire above. 

Then I thought. Well ok, there is some difficulty, let's manually help `latexindent`. But there is no such way without switching off formatting in the entire block. What would be ideal that in certain edge cases one could
```
\emph{First sentence?}
Second (third?) sentence?
\emph{Third sentence?} % noqa: oneSentencePerLine
Fourth sentence?
```
(or so)

**Comment by cmhughes** [comment]
Thanks for using the issue template :)

solution
-
Using the settings
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    sentencesBeginWith:            
        other: |-
          (?x)
          \\emph\{[A-Z]
    sentencesEndWith:
        questionMark: 0         # 0/1
        other: |-
          (?x)
          (?<!                  # not *preceeded by*
            (?:                 #
              [A-Z]             #
            )                   #
          )
          \?                    # ?
          (?!                   # NOT *followed by*          ---|
            (?:                 #                               |
              \)                # )                             |
              |                 #                               |
              \}                # }                             |
            )                   #                               |
            \h*                 # possible horizontal space     |
            [a-z]               # a-z                        ---
          )                     #
          [})]?                 # possible } or )
```
gives
```tex
\emph{First sentence?}
Second (third?) sentence?
\emph{Third sentence?}
Fourth sentence?
```
I've incorporated the settings from https://github.com/cmhughes/latexindent.pl/issues/408 and https://github.com/cmhughes/latexindent.pl/issues/406 as I'm assuming they're related... delete if not.

explanation
-

Let's start with the easiest part:
```yaml
    sentencesBeginWith:            
        other: |-
          (?x)
          \\emph\{[A-Z]
```
This says that sentences can _begin_ with `\emph{` and then a capital letter. Adjust as necessary.

The harder part is:
```yaml
    sentencesEndWith:
        questionMark: 0         # 0/1
        other: |-
          (?x)
          (?<!                  # not *preceeded by*
            (?:                 #
              [A-Z]             #
            )                   #
          )
          \?                    # ?
          (?!                   # NOT *followed by*          ---|
            (?:                 #                               |
              \)                # )                             |
              |                 #                               |
              \}                # }                             |
            )                   #                               |
            \h*                 # possible horizontal space     |
            [a-z]               # a-z                        ---
          )                     #
          [})]?                 # possible } or )
```
We first of all need to turn off the 'basic' question mark.

Then we need to ensure that:
* `?` can _not_ be followed by `} [a-z]` or `) [a-z]` so that, for example the `?` in `(third?) sentence` is _not_ the end of a sentence
* if the first condition is not true, then `?` can be followed by either `}` or `)`

I hope this helps, let me know if not.
