### ISSUE TITLE
No space before interpunction

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#414]
I want to separate the content of my footnote on a separate line. This works well with 
```yaml
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 1
```
However, it does introduce an additional unwanted whitespace when interpunction follows, see below.

I understand that this is a bit of a mixed desire from a style point of view. 

# original .tex code
```tex
This is a\footnote{
    My footnote
}
sentence.

This is a sentence\footnote{
    My footnote
}.
```

# yaml settings
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
  mandatoryArguments:
    footnote:
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 1
```

# actual/given output
```tex
This is a\footnote{
    My footnote
}
sentence.

This is a sentence\footnote{
    My footnote
}
.
```

# desired output, option 1
```tex
This is a\footnote{
    My footnote
}
sentence.

This is a sentence\footnote{
    My footnote
}.
```

# desired output, option 2
```tex
This is a\footnote{
    My footnote
}
sentence.

This is a sentence\footnote{
    My footnote
}%
.
```

# desired output, option 3
```tex
This is a\footnote{
    My footnote
} sentence.

This is a sentence\footnote{
    My footnote
}.
```

# anything else

Following https://github.com/cmhughes/latexindent.pl/issues/403

**Comment by cmhughes** [comment]
Thanks for this, I'll hopefully get to these soon.

**Comment by cmhughes** [comment]
option 1
-
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
  mandatoryArguments:
    footnote:
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 1

replacements:
  -
    when: after
    substitution: |-
        s/(\})\s*(\.)/$1$2/sg
```
gives
```tex
This is a\footnote{
    My footnote
}
sentence.

This is a sentence\footnote{
    My footnote
}.
```

option 2
-
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
  mandatoryArguments:
    footnote:
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 2        %<!---------------
```
gives
```tex
This is a\footnote{
    My footnote
}%
sentence.

This is a sentence\footnote{
    My footnote
}%
.
```

option 3
-
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
  mandatoryArguments:
    footnote:
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 0   %<!----------
```
which gives
```tex
This is a\footnote{
    My footnote
} sentence.

This is a sentence\footnote{
    My footnote
}.
```
