### ISSUE TITLE
bug: wrong indentation selected

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#416]
# original .tex code
```tex
\begin{figure}[htp]
    \centering
    \includegraphics[width=\linewidth]{figures/stopping_well}
    \caption{
        Foo.
        Consequently, $\partial_r(E + V) |_{w^* / 2} = 0$.
    }
    \label{fig:kappa}
\end{figure}
```

# yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1
```

# actual output
```tex
\begin{figure}[htp]
    \centering
    \includegraphics[width=\linewidth]{figures/stopping_well}
    \caption{
    Foo.
    Consequently, $\partial_r(E + V) |_{w^* / 2} = 0$.
    }
    \label{fig:kappa}
\end{figure}
```

# desired output
```tex
\begin{figure}[htp]
    \centering
    \includegraphics[width=\linewidth]{figures/stopping_well}
    \caption{
        Foo.
        Consequently, $\partial_r(E + V) |_{w^* / 2} = 0$.
    }
    \label{fig:kappa}
\end{figure}
```

# anything else
The issue is related to the inline equation. Removing it corrects the indentation.

**Comment by cmhughes** [comment]
You need to tell `latexindent.pl` that the `|` character can appear between arguments.

Using
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

fineTuning:
    arguments:
      between: _|\^|\*|\|
```
then you receive
```tex
\begin{figure}[htp]
    \centering
    \includegraphics[width=\linewidth]{figures/stopping_well}
    \caption{
        Foo.
        Consequently, $\partial_r(E + V) |_{w^* / 2} = 0$.
    }
    \label{fig:kappa}
\end{figure}
```
