### ISSUE TITLE
bug: trailing whitespaces added

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#417]
# original .tex code
```tex
Foo bar etc.

\paragraph{My header}

Other text.
```

clarification:

```tex
Foo bar etc.%---
%---
\paragraph{My header}%---
%---
Other text.%---
```

# yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
```

# actual output
```tex
Foo bar etc. 

\paragraph{My header} 

Other text.
```

clarification (notice the extra spaces):

```tex
Foo bar etc. %---
%---
\paragraph{My header} %---
%---
Other text.%---
```

# desired output
```tex
Foo bar etc.

\paragraph{My header}

Other text.
```
