### ISSUE TITLE
feature request: `noqa: option` to ignore a specific option of a specific line

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#418]
I would like to be able to manually switch-off a specific option (or a group of options) for a specific line (without tying that to the line number). 
For example:

# original .tex code
```tex
Foo bar.

\begin{figure}[htp]
    \subfloat{\label{fig:foo:a}} % noqa: modifyLineBreaks
    \subfloat{\label{fig:foo:b}} % noqa: modifyLineBreaks
    \centering
    \includegraphics[width=\linewidth]{figures/foo}
    \caption{Foo bar.}
\end{figure}
```

# yaml settings
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  commands:
    label:
      CommandStartsOnOwnLine: 1
```

# actual output
```tex
Foo bar.

\begin{figure}[htp]
    \subfloat{
        \label{fig:foo:a}} % noqa: modifyLineBreaks
    \subfloat{
        \label{fig:foo:b}} % noqa: modifyLineBreaks
    \centering
    \includegraphics[width=\linewidth]{figures/foo}
    \caption{Foo bar.}
\end{figure}
```

# desired output
```tex
Foo bar.

\begin{figure}[htp]
    \subfloat{\label{fig:foo:a}} % noqa: modifyLineBreaks
    \subfloat{\label{fig:foo:b}} % noqa: modifyLineBreaks
    \centering
    \includegraphics[width=\linewidth]{figures/foo}
    \caption{Foo bar.}
\end{figure}
```

# anything else

Follows discussion in https://github.com/cmhughes/latexindent.pl/issues/409

Different than https://github.com/cmhughes/latexindent.pl/issues/347 : the current feature request asks to still do formatting but just without a specific feature switched-off. Instead, https://github.com/cmhughes/latexindent.pl/issues/347 features existing options to do no formatting at all on specific lines.

**Comment by cmhughes** [comment]
I present two options, both give your desired output.

option 1
-
Use `noIndentBlock` as in https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html?highlight=href#lst-href3

```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  commands:
    label:
      CommandStartsOnOwnLine: 1

noIndentBlock:
   subfloat:
     begin: \\subfloat\h*\{\h*\\label\{
     body: [^}]*?
     end: \}\h*\}
```

option 2
-
Using the replacement switch as in https://latexindentpl.readthedocs.io/en/latest/sec-replacements.html
```yaml
onlyOneBackUp: 1
defaultIndent: '    '
removeTrailingWhitespace: 1

modifyLineBreaks:
  commands:
    label:
      CommandStartsOnOwnLine: 1

replacements:
  -
    when: after
    substitution: |-
        s/(\\subfloat\{)\s*(\\label)/$1$2/sg
```
