### ISSUE TITLE
break text at double backslash or `\newline`

### ISSUE THREAD

**Issue by carlosala** [cmhughes/latexindent.pl#424]
Please provide the following when posting an issue:

original .tex code
--
```tex
This\\
are\\
line\\
breaks
```

yaml settings
--
```yaml
defaultIndent: "  "
dos2unixlinebreaks: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 120
onlyOneBackUp: 1
```

actual/given output
--
```
This\\ are\\ line\\ breaks
```

desired or expected output
--
I'd like to cut the lines at `\\` or `\newline`.

anything else
--
I'm taliking about regular text, just inside document.
Thanks for the support!

**Comment by carlosala** [comment]
@cmhughes thanks for the response! This don't work for me because this is simply telling to the script that the block ended, and I just want to start a new one right after. Then:
```tex
                      |
I am writing here \\ I exceeded here the columns
and still continue to write here but after the \\ anything is checked
```

**Comment by carlosala** [comment]
So that would make the trick if I'm able to restart a new block after that.

**Comment by cmhughes** [comment]
I don't understand.... Did my settings work for the example you posted?

**Comment by carlosala** [comment]
@cmhughes Your settings work in the sense they break the block (so it stops wrapping right before `\\` or `\newline`. What I'd like to do is to start a new wrapping block right after `\\`. With your settings after `\\` (well, technically right before) it stops wrapping.
Please tell me if I'm not clear, sorry for that 😅

**Comment by cmhughes** [comment]
In which case, perhaps you want blocksFollow?

**Comment by carlosala** [comment]
Let's make a minimal example:
I have now `columns: 8`. The `|` is the 8th column.
```tex
        |
A\\ B C D\\ E F G H I J
```
I want this to be formatted as
```tex
        |
A\\
B C D\\
E F G H I
J
```
The problem is that, with blocksEndBefore, when it ends a block, it doesn't start a new one until a blank line is found I'd say.

**Comment by cmhughes** [comment]
Using the following gives your desired output :)
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 8
        blocksFollow:
           other: \\\]|\\item(?:\h|\[)|\\\\|\\newline 
```

**Comment by cmhughes** [comment]
Ok, I think I understand what you want now. 

Your request isn't really about text wrapping. I was initially confused by this.

You want a line break after each `\\` so we use the replacement switch.

starting .tex
-
```tex
A\\ B C D\\ E F G H I J
```
latexindent.yaml
-
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 10
        blocksFollow:
           other: \\\]|\\item(?:\h|\[)|\\\\|\\newline 

replacements:
  -
    amalgamate: 0
  -
    when: before
    substitution: |-
        s/(\\\\)\s*/$1\n/sg
```
call to latexindent
-
`latexindent.pl -l -rv -m myfile.tex`

output
-
```tex
A\\
B C D\\
E F G H I
J
```
