### ISSUE TITLE
bug: comment recursively added

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#425]
Please provide the following when posting an issue:

original .tex code
```tex
This is a\footnote{
    My footnote
}
sentence.

This is a sentence\footnote{
    My footnote
}.
```

yaml settings
```yaml
defaultIndent: '    '

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    multipleSpacesToSingle: 1
  mandatoryArguments:
    footnote:
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
      RCuBFinishesWithLineBreak: 2
```

actual/given output

Running once (output as expected):
```tex
This is a\footnote{
    My footnote
}%
sentence.

This is a sentence\footnote{
    My footnote
}%
.
```

Running twice (comments recursively added):
```tex
This is a\footnote{
    My footnote
}%
sentence.
%

This is a sentence\footnote{
    My footnote
}%
.
%
```

Running three times (comments recursively added):
```tex
This is a\footnote{
    My footnote
}%
sentence.
%
%

This is a sentence\footnote{
    My footnote
}%
.
%
%
```

desired or expected output
```
```tex
This is a\footnote{
    My footnote
}%
sentence.

This is a sentence\footnote{
    My footnote
}%
.
```

anything else
--
Following https://github.com/cmhughes/latexindent.pl/issues/414
