### ISSUE TITLE
Support for algorithm packages, such as algorithmic and algpseudocodex

### ISSUE THREAD

**Issue by Saltsmart** [cmhughes/latexindent.pl#427]
Please provide the following when posting an issue:

original .tex code
--
Here is a 3-layer "for loop" code with package `algpseudocodex`:
```latex
\begin{algorithm}[ht]
    \caption{some caption.}
    \begin{algorithmic}[1]
        \FOR{for 1}
        \FOR{for 2}
        \FOR{for 3}
        \STATE{some statement.}
        \ENDFOR
        \ENDFOR
        \ENDFOR
    \end{algorithmic}
\end{algorithm}
```

yaml settings
--
Since I don't have a `indentConfig.yaml`, I added these code directly into the `specialBeginEnd` group in `defaultSettings.yaml`:

```yaml
    ifStatement:
        begin:
         - \\If
         - \\IF
        middle:
         - \\Else
         - \\ELSE
         - \\ElsIf
        end:
         - \\EndIf
         - \\ENDIF
        lookForThis: 1
    whileStatement:
        begin:
         - \\While
         - \\WHILE
        end:
         - \\EndWhile
         - \\ENDWHILE
        lookForThis: 1
    forStatement:
        begin:
         - \\For
         - \\FOR
        end:
         - \\EndFor
         - \\ENDFOR
        lookForThis: 1
```

actual/given output
--
*Just the same as original code*:
```latex
\begin{algorithm}[ht]
    \caption{some caption.}
    \begin{algorithmic}[1]
        \FOR{for 1}
        \FOR{for 2}
        \FOR{for 3}
        \STATE{some statement.}
        \ENDFOR
        \ENDFOR
        \ENDFOR
    \end{algorithmic}
\end{algorithm}
```

desired or expected output
--
```latex
\begin{algorithm}[ht]
    \caption{some caption.}
    \begin{algorithmic}[1]
        \FOR{for 1}
            \FOR{for 2}
                \FOR{for 3}
                    \STATE{some statement.}
                \ENDFOR
            \ENDFOR
        \ENDFOR
    \end{algorithmic}
\end{algorithm}
```

anything else
--
Here is the `indent.log`:
```
INFO:  latexindent.exe version 3.20.1, 2023-01-07, a script to indent .tex files
       latexindent.exe lives here: D:/texlive/2022/bin/win32/
       Sun Mar  5 14:51:36 2023
       Filename: e:/MasterThesis/__latexindent_temp_algo.tex
INFO:  Processing switches:
       -y|--yaml: YAML settings specified via command line
       -c|--cruft: cruft directory
INFO:  Directory for backup files and e:/MasterThesis//indent.log:
       e:/MasterThesis/
INFO:  YAML settings read: defaultSettings.yaml
       Reading defaultSettings.yaml from D:/texlive/2022/bin/win32/defaultSettings.yaml
       Reading defaultSettings.yaml (2nd attempt) from D:/texlive/2022/bin/win32/../../texmf-dist/scripts/latexindent/defaultSettings.yaml
       and then, if necessary, D:/texlive/2022/bin/win32/LatexIndent/defaultSettings.yaml
INFO:  YAML reading settings
       Home directory is C:\Users\Administrator
       latexindent.pl didn't find indentconfig.yaml or .indentconfig.yaml
       see all possible locations: https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#indentconfig-options)
INFO:  YAML settings read: -y switch
       YAML setting: defaultIndent:'    '
       single-quoted string found in -y switch: '    ', substitute to
       Updating mainSettings with defaultIndent:
INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Not outputting to file; see -w and -o switches for more options.
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl
```

**Comment by cmhughes** [comment]
The crucial thing you need is
```yaml
    specialBeforeCommand: 1
````
see https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-specialbeforecommand-yaml

Using the following 

latexindent.yaml
-
```yaml
defaultIndent: " "

specialBeginEnd:
    forStatement:
        begin: \\FOR\{[^}]+?\}
        end: \\ENDFOR
    specialBeforeCommand: 1
```
and calling 
```
latexindent.pl -l myfile.tex
```
gives
```tex
\begin{algorithm}[ht]
 \caption{some caption.}
 \begin{algorithmic}[1]
  \FOR{for 1}
   \FOR{for 2}
    \FOR{for 3}
     \STATE{some statement.}
    \ENDFOR
   \ENDFOR
  \ENDFOR
 \end{algorithmic}
\end{algorithm}
```
I recommend against changing `defaultSettings.yaml` and instead using a local settings file as in https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#localsettings-yaml-and-friends

**Comment by Saltsmart** [comment]
It has been figure out. Here's the yaml for indenting the algorithms:
```yaml
specialBeginEnd:
    ForStatement:
        begin: \\For\{[^}]+?\}
        end: \\EndFor
    FORStatement:
        begin: \\FOR\{[^}]+?\}
        end: \\ENDFOR
    WhileStatement:
        begin: \\While\{[^}]+?\}
        end: \\EndWhile
    WHILEStatement:
        begin: \\WHILE\{[^}]+?\}
        end: \\ENDWHILE
    ForAllStatement:
        begin: \\ForAll\{[^}]+?\}
        end: \\EndFor
    LoopStatement:
        begin: \\Loop
        end: \\EndLoop
    RepeatStatement:
        begin: \\Repeat
        end: \\Until\{[^}]+?\}
    ProcedureStatement:
        begin: \\Procedure\{[^}]+?\}\{[^}]+?\}
        end: \\EndProcedure
    FunctionStatement:
        begin: \\Function\{[^}]+?\}\{[^}]+?\}
        end: \\EndFunction
    IfStatement:
        begin: \\If\{[^}]+?\}
        middle:
         - \\Else
         - \\ElsIf\{[^}]+?\}
        end: \\EndIf
    IFStatement:
        begin: \\IF\{[^}]+?\}
        middle:
         - \\ELSE
         - \\ELSIF\{[^}]+?\}
        end: \\ENDIF
    specialBeforeCommand: 1
```
And here is my test.tex.
It's my pleasure if you could make it as a test use case:
```tex
\begin{algorithm}[ht]
    \caption{some caption.}
    \begin{algorithmic}[1]
        \Require{aaa}
        \Ensure{bbb}
        % for-loop
        \For{$n = 1, \dots, 10$}
        \State body
        \EndFor
        % nesting for-loop
        \FOR{for 1}
        \FOR{for 2}
        \FOR{for 3}
        \STATE{some statement.}
        \ENDFOR
        \ENDFOR
        \ENDFOR
        % while-loop in if-statement
        \If{$quality\ge 9$}
        \State $a\gets perfect$
        \ElsIf{$quality\ge 7$}
        \State $a\gets good$
        \ElsIf{$quality\ge 5$}
        \State $a\gets medium$
        \ElsIf{$quality\ge 3$}
        \State $a\gets bad$
        \Else
        \While{$i\le n$}
        \State $sum\gets sum+i$
        \State $i\gets i+1$
        \EndWhile
        \EndIf
        % nesting blocks
        \ForAll{$n \in \{1, \dots, 10\}$}
        \State body
        \Loop
        \State body
        \EndLoop
        \State $sum\gets 0$
        \State $i\gets 1$
        \Repeat
        \State $sum\gets sum+i$
        \State $i\gets i+1$
        \Until{$i>n$}
        \EndFor
        % fuction block
        \Function{Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
        \State $r\gets a\bmod b$
        \While{$r\not=0$}\Comment{We have the answer if r is 0}
        \State $a\gets b$
        \State $b\gets r$
        \State $r\gets a\bmod b$
        \EndWhile
        \State \textbf{return} $b$\Comment{The gcd is b}
        \EndFunction
    \end{algorithmic}
\end{algorithm}
```
After formatting:
```tex
\begin{algorithm}[ht]
    \caption{some caption.}
    \begin{algorithmic}[1]
        \Require{aaa}
        \Ensure{bbb}
        % for-loop
        \For{$n = 1, \dots, 10$}
            \State body
        \EndFor
        % nesting for-loop
        \FOR{for 1}
            \FOR{for 2}
                \FOR{for 3}
                    \STATE{some statement.}
                \ENDFOR
            \ENDFOR
        \ENDFOR
        % while-loop in if-statement
        \If{$quality\ge 9$}
            \State $a\gets perfect$
        \ElsIf{$quality\ge 7$}
            \State $a\gets good$
        \ElsIf{$quality\ge 5$}
            \State $a\gets medium$
        \ElsIf{$quality\ge 3$}
            \State $a\gets bad$
        \Else
            \While{$i\le n$}
                \State $sum\gets sum+i$
                \State $i\gets i+1$
            \EndWhile
        \EndIf
        % nesting blocks
        \ForAll{$n \in \{1, \dots, 10\}$}
            \State body
            \Loop
                \State body
            \EndLoop
            \State $sum\gets 0$
            \State $i\gets 1$
            \Repeat
                \State $sum\gets sum+i$
                \State $i\gets i+1$
            \Until{$i>n$}
        \EndFor
        % fuction block
        \Function{Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
            \State $r\gets a\bmod b$
            \While{$r\not=0$}\Comment{We have the answer if r is 0}
                \State $a\gets b$
                \State $b\gets r$
                \State $r\gets a\bmod b$
            \EndWhile
            \State \textbf{return} $b$\Comment{The gcd is b}
        \EndFunction
    \end{algorithmic}
\end{algorithm}
```
