### ISSUE TITLE
Ignore or properly format specified lines from the `noIndentBlock` setting

### ISSUE THREAD

**Issue by Andrew15-5** [cmhughes/latexindent.pl#429]
original .tex code
--

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
  % fmt: off
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
  % fmt: on
\end{enumerate}
```

The indentation for the format comments can be manually set to an appropriate level (like in the example) or can be whatever. This depends on whether the formatter can format/ignore this lines or not.

yaml settings
--

```yaml
defaultIndent: "  "
modifyLineBreaks:
  textWrapOptions:
    blocksBeginWith:
      other: '\w'
    columns: 81
    when: after
noIndentBlock:
  custom:
    begin: '%\hfmt:\hoff'
    end: '%\hfmt:\hon'
```

actual/given output
--

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
        % fmt: off
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
  % fmt: on
\end{enumerate}
```

desired or expected output
--

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
  % fmt: off
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
  % fmt: on
\end{enumerate}
```

The indentation of the format comments must stay the same as in the source code or formatted to the appropriate level (whichever is possible).

anything else
--

This is the continuation of the discussion in #428.

**Comment by cmhughes** [comment]
Can you try
```
begin: '\h*%\hfmt:\hoff
```

**Comment by Andrew15-5** [comment]
I think this is correct (it also includes 2 spaces) but not what I need:

```latex

\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
          % fmt: off
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
  % fmt: on
\end{enumerate}
```

P.S. You forgot to add last single quote (and add syntax highlighting for better readability).

**Comment by cmhughes** [comment]
How about
```
begin: \R\h*%\hfmt:\hoff
```

**Comment by Andrew15-5** [comment]
Great, now it works with manually set indentation (can be different for `off`/`on` lines) or basically the indentation of the comments is ignored.

Now for the tricky part. Can latexindent.pl automatically choose a **correct** and the **same indentation level** for both comment lines? This way, you will not waste your time on making sure you wrote the comment lines following the 2 guidelines. Extra automation (formatting) is always nice.

**Comment by cmhughes** [comment]
Starting with
```tex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
          % fmt: off
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
        тест
  % fmt: on
\end{enumerate}
```
and using
```yaml
defaultIndent: "  "
noIndentBlock:
  custom:
    begin: '\R\h*%\hfmt:\hoff'
    end: '%\hfmt:\hon'

replacements:
  -
    when: after
    substitution: |-
      s/(\h*)               # leading horizontal space on PREVIOUS line
        (\H+?)              # NOT horizontal space
        \R                  # line break
        \h*                 # leading horizontal space on COMMENT line
        \%/$1$2\n$1%/xsmg   # h-space, previous line, h-space, comment
```
and running
```
latexindent.pl -l -r myfile.tex
```
gives
```tex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
        % fmt: off
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
        тест
        % fmt: on
\end{enumerate}
```

**Comment by Andrew15-5** [comment]
Wha, why it doesn't work if I'm including `paths:` in the same config file? If I have the `paths` then everything is formatted, but if I don't have `paths` then of course config doesn't work and nothing is formatted... That is nothing except the comment lines. So I either use `replacements` or everything else but not both. How come?

```yaml
defaultIndent: "  "
noIndentBlock:
  custom:
    begin: '\R\h*%\hfmt:\hoff'
    end: '%\hfmt:\hon'
replacements:
  -
    when: after
    substitution: |-
      s/(\h*)               # leading horizontal space on PREVIOUS line
        (\H+?)              # NOT horizontal space
        \R                  # line break
        \h*                 # leading horizontal space on COMMENT line
        \%/$1$2\n$1%/xsmg   # h-space, previous line, h-space, comment
paths:
  - "/home/user/.config/latexindent/latexindent.yaml"
```
