### ISSUE TITLE
verbatimEnvironments can't take more than one Regex

### ISSUE THREAD

**Issue by MoritzBeroRoos** [cmhughes/latexindent.pl#435]
Hi, 
i am trying to use latexindent with pythontex which is why i am trying to treat all Environments starting with 'py' or with 'jl' as verbatim.
My testing latex is:
```
\begin{document}

a
\begin{latexcode}
import pygments
print(r'\begin{center}')
print(r'\textit{A message 2 from Python!}')
print(r'\end{center}')
\end{latexcode}
\end{document}
```
My defaultSettings.yaml contains:

```
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1
    nameAsRegex:
      name: '\w+code\*?'
      lookForThis: 1
    nameAsRegex:
      name: 'py\w*'
      lookForThis: 1
    nameAsRegex:
      name: 'jl\w*'
      lookForThis: 1
```
But it looks as if latexindent will only treat the last regex-entry in verbatimEnvironments as verbatim.
In the above config my code will be indented. If i swap the entrys for py and jl then my code is not indented. 
Aditionally the lookForThis argument doesnt seem to influence this behaviour (if jl is the last entry it will indent my above code, no matter what lookForThis is set to)
Edit:
using `name: '(py\w*)|(jl\w*)'` does *very* weird things to my code
