### ISSUE TITLE
verbatimEnvironments doesnt use more than one Regex

### ISSUE THREAD

**Issue by MoritzBeroRoos** [cmhughes/latexindent.pl#436]
Please provide the following when posting an issue:

original .tex code
--
```
\documentclass[12pt,ngerman]{scrartcl}
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}
a
\begin{pyde}
import pygments
print(r'\begin{center}')
print(r'\textit{A message 2 from Python!}')
print(r'\end{center}')
\end{pyde}
\end{document}
```

yaml settings
--
```
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1
    nameAsRegex:
      name: 'py\w*'
      lookForThis: 1
    nameAsRegex:
      name: 'jl\w*'
      lookForThis: 1
```

actual/given output
--
```
\documentclass[12pt,ngerman]{scrartcl}
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}
a
\begin{pyde}
	import pygments
	print(r'\begin{center}')
		print(r'\textit{A message 2 from Python!}')
		print(r'\end{center}')
\end{pyde}
\end{document}
```

desired or expected output
--
```
\documentclass[12pt,ngerman]{scrartcl}
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}
a
\begin{pyde}
import pygments
print(r'\begin{center}')
print(r'\textit{A message 2 from Python!}')
print(r'\end{center}')
\end{pyde}
\end{document}
```

anything else
--
Swapping the two regex in the defaultSettings would (correctly) not indent a jlde environment and (incorrectly) indet a pyde environment. This makes me believe only the last regex in the defaultSettings is used.

putting lookForThis: 0 for the 'jl\w*' does not change the output.

Using only one regex like suggested: '(?:py|jl)\w*' does give the desired output.

**Comment by EllynZaeske4** [comment]
Based on the information provided, it seems like the issue is related to the use of multiple regex patterns in the YAML settings for the verbatim environment. Specifically, the last regex pattern seems to be overriding the previous ones, resulting in the undesired output.

One possible solution is to use a single regex pattern that matches both 'pyde' and 'jlde' environments, like this:

yaml
Copy code
verbatimEnvironments:
  - name: '(py|jl)de'
    lookForThis: true
    style:
      # Your desired style here
This way, both 'pyde' and 'jlde' environments will be formatted according to the specified style.

It's also worth noting that the given output seems to have extra indentation in the Python code block, which could be a separate issue.

**Comment by cmhughes** [comment]
You've duplicated the key `nameAsRegex`.

**Comment by cmhughes** [comment]
Try naming it something else.

**Comment by MoritzBeroRoos** [comment]
Thanks that works. I didn't realize these were dict keys. Just for completeness, the following does work:

```
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1
    pythontexpy:
      name: 'py\w*'
      lookForThis: 1
    pythontexjl:
      name: 'jl\w*'
      lookForThis: 1
```
As for extra indentation, i am not sure what is going on there
