### ISSUE TITLE
Interval mistaken for optional arguments?

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#445]
original .tex code
--
```latex
\[
  x \in
  \begin{cases}
    [0, 1] & \text{ with probability } \tfrac{1}{2} \\
    [2, 3] & \text{ with probability } \tfrac{1}{2}.
  \end{cases}
\]
```

yaml settings
--
```yaml
modifyLineBreaks:
    environments:
        DBSStartsOnOwnLine: 0
        DBSFinishesWithLineBreak: 1
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 2  # add % after \begin{env} to preserve page reference
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```

actual/given output
--
```latex
\[
  x \in
  \begin{cases}[0, 1] & \text{ with probability } \tfrac{1}{2}  \\
             [2, 3] & \text{ with probability } \tfrac{1}{2}.
  \end{cases}
\]
```

desired or expected output
--
```latex
\[
  x \in
  \begin{cases}%
    [0, 1] & \text{ with probability } \tfrac{1}{2} \\
    [2, 3] & \text{ with probability } \tfrac{1}{2}.
  \end{cases}
\]
```
(note the `%` after `\begin{cases}`).

I'm guessing the interval `[0, 1]` is being mistaken for optional arguments to the `cases` environment?!

**Comment by cmhughes** [comment]
Thanks for this.

Yes, I agree, this isn't expected behaviour.

For my reference, the following is minimal:

original text
-
```tex
\[
  x \in
  \begin{cases}
    [0, 1] & 3 \\
    [2, 3] & 4 
  \end{cases}
\]
```

settings
-
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2
```
output
-
```tex
\[
	x \in
	\begin{cases}[0, 1] & 3 \\
             [2, 3] & 4
	\end{cases}
\]
```
expected
-
```tex
\[
	x \in
	\begin{cases}
		[0, 1] & 3 \\
		[2, 3] & 4
	\end{cases}
\]
```
notes to self
-
poly-switch having a value `>0` shouldn't change the line break (...?)

**Comment by cmhughes** [comment]
Apologies for the delay.

I present a few options for you, each of which give your desired output, I hope this is helpful.
```tex
\[
	x \in
	\begin{cases}
		[0, 1] & \text{ with probability } \tfrac{1}{2}  \\
		[2, 3] & \text{ with probability } \tfrac{1}{2}.
	\end{cases}
\]
```

option 1
-
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2
    optionalArguments:
        LSqBStartsOnOwnLine: 1
```

option 2
-
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2
    optionalArguments:
        cases:
           LSqBStartsOnOwnLine: 1
```

option 3
-
If you'd prefer _not_ to think of `cases` as an environment, then you can tweak the `fineTuning` as in the below, and then look define `cases` as a `specialBeginEnd`.

```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2

fineTuning:
    environments:
      name: (?!cases)[a-zA-Z@\*0-9_\\]+

specialBeginEnd:
    cases:
        begin: \\begin\{cases\}
        end: \\end\{cases\}
    specialBeforeCommand: 1
```
