### ISSUE TITLE
noindent for single line patterns

### ISSUE THREAD

**Issue by Rdeisenroth** [cmhughes/latexindent.pl#448]
I am trying to get latexindent to accept this kind of indentation where i use a comment in order to mark a section or chapter end.

original .tex code
--
```latex
\chapter{Quaternionen} % S.176
	\todo{Quaternionen}
	\section{Vergleich mit anderen Darstellungsarten} % S.179
		\todo{Quaternionen}
	% end
% end

\chapter{Zusammenhang zwischen Rotationsmatrix, Drehvektor und Drehwinkel} % S.179
	\todo{Rotationsmatrix, Drehvektor und Drehwinkel}

	\section{Umwandlung von Drehvektor und Drehwinkel zu Rotationsmatrix} % S.179
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
	% end

	\section{Umwandlung von Rotationsmatrix zu Drehvektor und Drehwinkel} % S.179, S.180, S.181
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
	% end
% end
```

yaml settings
--
```yaml
defaultIndent: "\t"
indentRules:
  chapter: "\t"
  section: "\t"
  item: "\t"

# set noAdditionalIndent globally for codeblocks
noAdditionalIndentGlobal:
  environments: 0
  commands: 1
  optionalArguments: 0
  mandatoryArguments: 0
  ifElseFi: 0
  items: 0
  keyEqualsValuesBracesBrackets: 1
  namedGroupingBracesBrackets: 1
  UnNamedGroupingBracesBrackets: 1
  specialBeginEnd: 0
  afterHeading: 0
  filecontents: 0

indentAfterHeadings:
  part:
    indentAfterThisHeading: 1
    level: 1
  chapter:
    indentAfterThisHeading: 1
    level: 2
  section:
    indentAfterThisHeading: 1
    level: 3
  subsection:
    indentAfterThisHeading: 1
    level: 4
  subsection*:
    indentAfterThisHeading: 1
    level: 4
  subsubsection:
    indentAfterThisHeading: 1
    level: 5
  paragraph:
    indentAfterThisHeading: 1
    level: 6
  subparagraph:
    indentAfterThisHeading: 1
    level: 7
```

actual/given output
--
```latex
\chapter{Quaternionen} % S.176
	\todo{Quaternionen}
	\section{Vergleich mit anderen Darstellungsarten} % S.179
		\todo{Quaternionen}
		% end
		% end

\chapter{Zusammenhang zwischen Rotationsmatrix, Drehvektor und Drehwinkel} % S.179
	\todo{Rotationsmatrix, Drehvektor und Drehwinkel}

	\section{Umwandlung von Drehvektor und Drehwinkel zu Rotationsmatrix} % S.179
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
		% end

	\section{Umwandlung von Rotationsmatrix zu Drehvektor und Drehwinkel} % S.179, S.180, S.181
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
		% end
		% end
```

desired or expected output
--
```latex
\chapter{Quaternionen} % S.176
	\todo{Quaternionen}
	\section{Vergleich mit anderen Darstellungsarten} % S.179
		\todo{Quaternionen}
	% end
% end

\chapter{Zusammenhang zwischen Rotationsmatrix, Drehvektor und Drehwinkel} % S.179
	\todo{Rotationsmatrix, Drehvektor und Drehwinkel}

	\section{Umwandlung von Drehvektor und Drehwinkel zu Rotationsmatrix} % S.179
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
	% end

	\section{Umwandlung von Rotationsmatrix zu Drehvektor und Drehwinkel} % S.179, S.180, S.181
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
	% end
% end
```

anything else
--
 I tried to define a custom noIndentBlock:
```yaml
noIndentBlock:
  custom:
    name: '\R\h*%\h*end\h*'
    lookForThis: 1
```
and seperately a `specialBeginEnd`:
```latex
specialBeginEnd:
  customSection:
    begin: '\\section\*?'
    end: '%\h*end\h*'
    lookForThis: 1
  specialBeforeCommand: 0
  ```
which unfortunately gives the same result.

If there is some way to turn off indentation for a pattern like this it would be enough for my usecase. However ideally it would auto-indent the comments.
Apologies if i am overlooking something.

**Comment by cmhughes** [comment]
Thanks for this, I hope to get to it soon.

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/a7c87234807331ea445d1d17ef5e9bf561810c6d I've updated the `fineTuning` routine so that you can specify

```yaml
defaultIndent: "\t"

specialBeginEnd:
  customSection:
    begin: \\(?:section|chapter)
    end: \%\h+end
  specialBeforeCommand: 1

fineTuning:
    trailingComments:
      notPreceededBy: (?<!\\)
      afterComment: (?!(?:\hend)).*?    # <!----- NEW BIT
```
and then you receive
```tex
\chapter{Quaternionen} % S.176
	\todo{Quaternionen}
	\section{Vergleich mit anderen Darstellungsarten} % S.179
		\todo{Quaternionen}
	% end
% end

\chapter{Zusammenhang zwischen Rotationsmatrix, Drehvektor und Drehwinkel} % S.179
	\todo{Rotationsmatrix, Drehvektor und Drehwinkel}

	\section{Umwandlung von Drehvektor und Drehwinkel zu Rotationsmatrix} % S.179
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
	% end

	\section{Umwandlung von Rotationsmatrix zu Drehvektor und Drehwinkel} % S.179, S.180, S.181
		\todo{Rotationsmatrix, Drehvektor und Drehwinkel}
	% end
% end
```
I'll get this released soon; feel free to pull from `develop` in the mean time.

Thanks again!
