### ISSUE TITLE
prevent indenting display math with preceding punctuation

### ISSUE THREAD

**Issue by pabloavi** [cmhughes/latexindent.pl#454]
original .tex code
```tex
With the equation
\[
  3x = 7
.\]
```

yaml settings
```yaml
defaultIndent: '  '
modifyLineBreaks:
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
```

actual/given output
```tex
With the equation
\[
  3x = 7
  .\]
```

desired or expected output
--
```tex
With the equation
\[
  3x = 7
.\]
```

As can be seen, the display math end is getting indented. In the docs I've not seen any option not to add extra-indent if the display math end is preceded also by a comma or a dot.  I would like this behaviour to happen to display math, as well as begin/end environment blocks. Is there any way to do it? Any option I should check? Thanks in advance.

**Comment by cmhughes** [comment]
Thanks for this :)

This is expected behaviour, as all of
```tex
  3x = 7
  .
```
is part of the body of displayMath.

If you'd like to change this, you can try

```yaml
specialBeginEnd:
    displayMath:
        begin: (?<!\\)\\\[            # \[ but *not* \\[
        end: \.\\\]
```

**Comment by pabloavi** [comment]
It is working as expected, thanks! And can this be done with all begin/end blocks? That is (where equation could be any other environment), so that in this case the original and expected outputs would be the same:
```tex
With the equation
\begin{equation}
  3x = 7
.\end{equation}
```

I've seen that there is the option of using `specialBeginEnd` with a specific environment (`myenv` in docs), but not how to apply it to any.

**Comment by cmhughes** [comment]
Perhaps you can use the following:
```yaml
defaultIndent: ' '

fineTuning:
    environments:
      name: a

specialBeginEnd:
    environments:
        begin: \\begin\{[a-zA-Z@\*0-9_\\]+\}
        end: \.\\end\{
    specialBeforeCommand: 1
```
