### ISSUE TITLE
Why am I unable to retain line breaks for \begin{equation*} and \end{equation*}?

### ISSUE THREAD

**Issue by RobinTruax** [cmhughes/latexindent.pl#461]
Original `tex` code
--
```
A
\begin{equation*}
    B
\end{equation*}
C.
```

`yaml` settings
--
```
modifyLineBreaks: 
  oneSentencePerLine: 
    manipulateSentences: 1
    removalSentenceLineBreaks: 1
    textWrapSentences: 0
  environments: 
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    DBSFinishesWithLineBreak: 1
```

Actual/given output `tex`
--
```
A \begin{equation*} B \end{equation*} C.
```

Desired or expected output `tex`
--
```
A
\begin{equation*}
    B
\end{equation*}
C.
```

I would not like `latexindent` to collapse these environments. My other environments (.e.g theorem, definition, lemma, etc.) are not collapsed.

**Comment by cmhughes** [comment]
Thanks for this.

equation* is specified in the defaultSettings.yaml, the intention is for it to be a helpful demonstration, but maybe it causes confusion...?

So, you need
```yaml
environments:                           
        equation*:                          
            BeginStartsOnOwnLine: 1
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 1
```
