### ISSUE TITLE
oneSentencePerLine wrecks itemize

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#463]
Please provide the following when posting an issue:

original .tex code
--
```latex
We compare
\begin{itemize}
  \item R2
  \item TR-R2 (maybe?)
  \item TRDH
\end{itemize}
```

yaml settings
--
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
```

actual/given output
--
```latex
We compare \begin{itemize} \item R2 \item TR-R2 (maybe?
        )
  \item TRDH
\end{itemize}
```

desired or expected output
--
Not sure, but I am not expecting the `itemize` environment to be merged with the first line and two `\item`s to end up on the same line. I understand that the `?` is taken as the end of a sentence, and that a line break is added. Maybe I would expect something like
```latex
We compare
\begin{itemize}
  \item R2
  \item TR-R2 (maybe?
  )
  \item TRDH
\end{itemize}
```

anything else
--
With all default settings, the output is
```latex
We compare
\begin{itemize}
        \item R2
        \item TR-R2 (maybe?)
        \item TRDH
\end{itemize}
```
and so I don't expect `oneSentencePerLine` to wreck something that wasn't wrecked before. What is happening here?

**Comment by cmhughes** [comment]
Thanks for this.

They key thing is to think about what a sentence is. Your settings say that a sentence can start with an uppercase letter, and can finish with a question mark.

There is not currently a way to say 'sentence does not contain' but it's on the list at https://github.com/cmhughes/latexindent.pl/issues/419 which I'm hoping to get to soon. 

In the meantime you can either tweak the sentence routine or otherwise set some poly switches as in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-multiple-sentences4-mod3

Does this help?

**Comment by dpo** [comment]
> They key thing is to think about what a sentence is. Your settings say that a sentence can start with an uppercase letter, and can finish with a question mark.

Well, they say more than that, right? A sentence can also start with a left paren followed by a capital letter, and can end with a full stop/question mark/exclamation mark, followed by either a right paren or a space.

**Comment by cmhughes** [comment]
Here are some settings for you to consider/explore:

attempt 1
-
using the settings
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
    items:
        ItemStartsOnOwnLine: 1
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```
gives
```tex
We compare
\begin{itemize}
	\item R2
	\item TR-R2 (maybe?
	      )
	\item TRDH
\end{itemize}
```
which isn't quite as we would like. So, to attempt 2.

attempt 2
-
We customise `sentencesEndWith` field (see https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#onesentenceperline-sentencesendwith) as follows
```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            questionMark: 0                 # 0/1
            other: |-
              (?x)
              (?:          #
                 \?\)?     # ?) OR ?
              )
    items:
        ItemStartsOnOwnLine: 1
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```
We have turned _off_ the basic question mark and used a more sophisticated version
```yaml        
       other: |-
              (?x)
              (?:          #
                 \?\)?     # ?) OR ?
              )
```
Let's go through this:
* `(?x)` says that the regex can have space within it, and that the space will be ignored
* `(?: ` opens a _non-capturing_ set of parenthesis
* `\?\)?` means 'a ? possibly followed by a )'
* `)` closes the non-capturing set of parenthesis
