### ISSUE TITLE
BodyStartsOnOwnLine: 2 and optional position arguments adds a second %

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#464]
Please provide the following when posting an issue:

original .tex code
--
```latex
\begin{algorithm}[h]%
        Bla.
\end{algorithm}
```

yaml settings
--
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2  # add % after \begin{env} to preserve page reference
```

actual/given output
--
```latex
\begin{algorithm}[h]%%
        Bla.
\end{algorithm}
```
(Note the extra `%`.)

desired or expected output
--
```latex
\begin{algorithm}[h]%
        Bla.
\end{algorithm}
```
(NB: only one `%`.)

anything else
--
Starting with
```latex
\begin{algorithm}%
  Bla.
\end{algorithm}
```
no second `%` gets added. There seems to be an interaction with the optional `[h]` argument.

**Comment by cmhughes** [comment]
Thanks for this, and apologies for delay (various internet/operating system issues).

solution
-
You can use the following settings
```yaml
modifyLineBreaks:
    environments:
        BodyStartsOnOwnLine: 2  # add % after \begin{env} to preserve page reference

replacements:
  -
    when: after
    substitution: |-
      s/%%/%/sg
```
and call `latexindent` using the `-r` switch, such as
```
latexindent.pl -l -m -r myfile.tex
```

explanation
-
Referencing https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#poly-switches-for-other-code-blocks we see that for environments `BodyStartsOnOwnLine` refers to the content immediately after the `begin` statement. During the poly-switch adjustment `latexindent`

1. first of all adds the comment and the line break
2. then checks for arguments, and if it finds any, checks the values of `LSqBStartsOnOwnLine` (optional arguments) and `LCuBStartsOnOwnLine` (mandatory arguments) and then makes necessary adjustments; in your example, because you haven't specified that either type of argument should start on their own line, `latexindent` removes the linebreak added in step 1

At the end of the indentation algorithm, `latexindent` checks for comments that are not at the end of their line, and then moves them. In your case, this results in two comments.

So, finally in the settings above, we instruct `latexindent` to replace two comment symbols with a single comment symbol. You might like to use
```yaml
replacements:
  -
    when: after
    substitution: |-
      s/%{2,}/%/sg
```
which would replace _two or more comment symbols_ with a single comment symbol.

I hope this helps!
