### ISSUE TITLE
Issue with align wraping and `\partial`

### ISSUE THREAD

**Issue by aghriss** [cmhughes/latexindent.pl#471]
There is some weird behavior when using `\partial` (I lost some brain cells trying to figure out the issue).

```tex
\begin{align*}
\frac{\partial f(x)}{\partial x_m} 
& = \sum_{i,j}^{n} w_ij {\frac{\partial{}\Ea{(f_i-f_j)^2}}{\partial{} x_m}} \\
& = \alpha
\end{align*}
```
```yaml
noAdditionalIndent:
  aligned: 1
lookForAlignDelims:
  aligned: 1
  alignFinalDoubleBackSlash: 1
modifyLineBreaks:
  preserveBlankLines: 1 # 0/1
  condenseMultipleBlankLinesInto: 1 # 0/1
  textWrapOptions:
    multipleSpacesToSingle: 1
    removeBlockLineBreaks: 1
    columns: 84
    when: after # before/after
    comments:
      wrap: 0 # 0/1
      inheritLeadingSpace: 0 # 0/1
    blocksFollow:
      headings: 1 # 0/1
      commentOnPreviousLine: 1 # 0/1
      par: 1 # 0/1
      blankLine: 1 # 0/1
      verbatim: 1 # 0/1
      filecontents: 1 # 0/1
      # other: 1
      other: \\\]|\\item(?:\h|\[) # regex
    blocksBeginWith:
      A-Z: 1 # 0/1
      a-z: 1 # 0/1
      0-9: 1 # 0/1
      other: 0 # regex
    blocksEndBefore:
      commentOnOwnLine: 1 # 0/1
      verbatim: 1 # 0/1
      filecontents: 1 # 0/1
      # other: 0
      # other: \\begin\{|\\\[|\\end\{    # regex
    huge: overflow # forbid mid-word line breaks
    separator: ""
```
Output 
```tex
\begin{align*} 
\frac{\partial f(x)}{\partial x_m} & = \sum_{i,j}^{n} w_ij {\frac{\partial{}\Ea{(f_i-f_j)^2}{\partial{} x_m}} \\ & = \alpha
\end{align*}
```
When I change `partial` to `delta` 
```tex
\begin{align*}
	\frac{\delta f(x)}{\delta x_m}
	 & = \sum_{i,j}^{n} w_ij {\frac{\delta{}\Ea{(f_i-f_j)^2}}{\delta{} x_m}} \\
	 & = \alpha
\end{align*}
```

```bash 
latexindent --version
> 3.22.2, 2023-07-14
```
