### ISSUE TITLE
Custom `specialBeginEnd` bracket pair breaks indentation of commands

### ISSUE THREAD

**Issue by arodomanov** [cmhughes/latexindent.pl#480]
Following my [previous example](https://github.com/cmhughes/latexindent.pl/issues/477), I was trying to make `latexindent` indent the text inside any square brackets. However, in doing so, I noticed some strange behavior which is probably a bug.

Specifically, I have a very simple command with one (optional) argument in the brackets and one (mandatory) argument in the braces (please see `source.tex` below). I'm then running `latexindent` with the `latexindent.yaml` settings file (see below). The expectation is that nothing should change in the output compared to the original file. However, for some reason, `latexindent` wants to unindent the "Do something" argument in the braces producing the output shown in the `source-mod.tex` file.

Original .tex code (`source.tex`)
--
```latex
\todo[inline]{
  Do something.
}
```

yaml settings (`latexindent.yaml`)
--
```yaml
defaultIndent: "  "

specialBeginEnd:
  specialBeforeCommand: 1

  brackets:
    begin: (?<!\\)\[ # but not display math (\[)
    end: (?<!\\)\] # but not display math (\])
    lookForThis: 1
```

The command used to run `latexindent`
--
```shell
latexindent -l latexindent.yaml -o=+-mod.tex source.tex
```

Actual output (`source-mod.tex`)
--
```latex
\todo[inline]{
Do something.
}
```

Desired or expected output (same as `source.tex`)
--
```latex
\todo[inline]{
  Do something.
}
```

Version of `latexindent`
--
```shell
3.23.2, 2023-09-23
```

Additional remarks
--
I've experimented a bit and found out that everything works as expected if either
* I remove the `brackets` `specialBeginEnd` entry from the settings file, or
* I set `specialBeforeCommand` to `0` (instead of `1`).

**Comment by cmhughes** [comment]
I don't understand why you need a y settings for your example, as latexindent will produce the desired output by default.

Do you have an actual use case?

**Comment by arodomanov** [comment]
Yes, of course, I don't need the special settings file to achieve the desired output for the example I presented.

What I actually want is to automatically indent the contents inside each pair of brackets in a mathematical expression. For example, consider the latex code from my previous issue (where I replaced parentheses with brackets):
```latex
$
  a
  +
  [
    b + c
  ]
  =
  d
$
and
$
  e + f = g
$
```

I'd like this code to stay exactly the same after formatting which is why I want to use the special `latexindent.yaml` settings file presented above. But, as I already wrote in the first message, this breaks the indentation of certain commands.

**Comment by cmhughes** [comment]
Thanks, that's helpful.

solution
-
```yaml
defaultIndent: "  "

specialBeginEnd:
  specialBeforeCommand: 1
  brackets:
    begin: (?<![a-zA-Z\\])\[
    end: (?<!\\)\] 
    lookForThis: 1
```
gives the output
```tex
$
  a
  +
  [
    b + c
  ]
  =
  d
$
and
$
  e + f = g
$

\todo[inline]{
  Do something.
}
```

explanation
-
The expression
```yaml
begin: (?<![a-zA-Z\\])\[
```
means _[ but not immediately preceded by a to z, A to Z, or a backslash_. This setting is means that commands, such as `\todo` in your example, are then found appropriately.
