### ISSUE TITLE
Bug: `indentAfterItems.itemize: 0` overwrites `modifyLineBreas.items.ItemStartsOnOwnLine: 4`

### ISSUE THREAD

**Issue by cgahr** [cmhughes/latexindent.pl#492]
I have to following tex:
```latex
\begin{itemize}
    \item A
    \begin{itemize}
        \item A.child

        \item A.child
    \end{itemize}

    \item B
    \begin{itemize}
        \item B.child

        \item B.child

        \item B.child

        \item B.child
    \end{itemize}
\end{itemize}
```
I want to format the tex file, as shown in the example:
- before each `item` a new line (but the first [if possible])
- the childs of `item` should not be indented.

I would expect that the following settings give me the desired result, however, they do not. Changing `indentAtfterItems.itemize` from `0` to `1`, gets me closer to the desired result but not quite: I get the newlines before each `item`, but their childs are indented.

yaml settings
--
```yaml
defaultIndent: "    "
indentAfterItems:
    itemize: 0
indentRules:
    item: "    "

modifyLineBreaks:
    items:
        ItemStartsOnOwnLine: 4
```
actual/given output
--
```latex
\begin{itemize}
    \item A
    \begin{itemize}
        \item A.child
        \item A.child
    \end{itemize}
    \item B
    \begin{itemize}
        \item B.child
        \item B.child
        \item B.child
        \item B.child
    \end{itemize}
\end{itemize}
```
*Please paste the output you receive here*

desired or expected output
--
```latex
\begin{itemize}
    \item A
    \begin{itemize}
        \item A.child

        \item A.child
    \end{itemize}

    \item B
    \begin{itemize}
        \item B.child

        \item B.child

        \item B.child
        \item B.child

    \end{itemize}
\end{itemize}
```
similar but different - config
--
```yaml
defaultIndent: "    "
indentAfterItems:
    itemize: 1
indentRules:
    item: "    "

modifyLineBreaks:
    items:
        ItemStartsOnOwnLine: 4
```
similar but different - output
--
```latex
\begin{itemize}

    \item A
        \begin{itemize}
    
            \item A.child
    
            \item A.child
        \end{itemize}

    \item B
        \begin{itemize}
    
            \item B.child
    
            \item B.child
    
            \item B.child
    
            \item B.child
        \end{itemize}
\end{itemize}
```

**Comment by cmhughes** [comment]
starting with
```tex
\begin{itemize}
    \item A
    \begin{itemize}
        \item A.child

        \item A.child
    \end{itemize}

    \item B
    \begin{itemize}
        \item B.child

        \item B.child

        \item B.child
        \item B.child

    \end{itemize}
\end{itemize}
```
and use the settings
```yaml
defaultIndent: "    "
indentRules:
    item: ""   # <!----------- NOTE

modifyLineBreaks:
    items:
        ItemStartsOnOwnLine: 3 # <!----------- NOTE
```
then I receive
```tex
\begin{itemize}
    \item A
    \begin{itemize}
        \item A.child

        \item A.child
    \end{itemize}

    \item B
    \begin{itemize}
        \item B.child

        \item B.child

        \item B.child
        \item B.child

    \end{itemize}
\end{itemize}
```
which is your desired output.

See https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#poly-switches for further reference.
