### ISSUE TITLE
different behavior for stdin and filename input

### ISSUE THREAD

**Issue by vindex10** [cmhughes/latexindent.pl#493]
original .tex code
--

```
\documentclass{article}   %% ... or norsk, nynorsk, USenglish
\usepackage[utf8]{inputenc}	    %% ... or latin1
\usepackage[T1]{url}\urlstyle{sf}
\begin{document}
Hello!
\end{document}
```

yaml settings
--

```
defaultIndent: "    "
fileExtensionPreference:
  '': 1
  .tex: 2
  .sty: 3
  .cls: 4
  .bib: 5
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1              # 0/1
    removeSentenceLineBreaks: 1         # 0/1
    multipleSpacesToSingle: 1           # 0/1
    textWrapSentences: 1                # 1 disables main textWrap
    sentenceIndent: ""
    sentencesFollow:
      par: 1                          # 0/1
      blankLine: 1                    # 0/1
      fullStop: 1                     # 0/1
      exclamationMark: 1              # 0/1
      questionMark: 1                 # 0/1
      rightBrace: 1                   # 0/1
      commentOnPreviousLine: 1        # 0/1
      other: 0                        # regex
    sentencesBeginWith:
      A-Z: 1                          # 0/1
      a-z: 0                          # 0/1
      other: 0                        # regex
    sentencesEndWith:
      basicFullStop: 0                # 0/1
      betterFullStop: 1               # 0/1
      exclamationMark: 1              # 0/1
      questionMark: 1                 # 0/1
      other: \,                        # regex
    sentencesDoNOTcontain:
      other: \\begin                 # regex
  textWrapOptions:
    columns: 80                # 1 disables main textWrap
    multipleSpacesToSingle: 1
  environment:
    BeginStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
  optionalArguments:
    CommaFinishesWithLineBreak: 1
    RSqBFinishesWithLineBreak: 1
  keyEqualsValuesBracesBrackets:
    KeyStartsOnOwnLine: 1
  items:
    ItemFinishesWithLineBreak: 1
  specialBeginEnd:
    SpecialBeginStartsOnOwnLine: 1
  verbatim:
    VerbatimBeginStartsOnOwnLine: 1
removeTrailingWhitespace:
  beforeProcessing: 1
  afterProcessing: 1
fineTuning:
  modifyLineBreaks:
      betterFullStop: |-
        (?:\.\s|,\s)
```

actual/given output
--

same as with either of these commands:

* `cat orig.tex | latexindent -o tmp.tex -l ./latexindent.yaml -m -`
* `latexindent -o tmp.tex -l ./latexindent.yaml -m - < orig.tex`
* `(latexindent -o tmp.tex -l ./latexindent.yaml -m <(tee)) < orig.tex` - for this to work I had to add "an empty extension preference"

```
\documentclass{article}   %% ... or norsk, nynorsk, USenglish
\usepackage[utf8]
{inputenc}	    %% ... or latin1
\usepackage[T1]
{url}\urlstyle{sf}
\begin{document}
Hello!
\end{document}
```

desired or expected output
--

same as with this command:
`latexindent -o tmp.tex -l ./latexindent.yaml -m orig.tex`

```
\documentclass{article}   %% ... or norsk, nynorsk, USenglish
\usepackage[utf8]{inputenc}	    %% ... or latin1
\usepackage[T1]{url}\urlstyle{sf}
\begin{document}
Hello!
\end{document}
```

Hi! Thank you for such a nice tool :) 

I noticed that there is a difference in outputs when the tool is using file input vs stdin.

**Comment by cmhughes** [comment]
Thanks for this, I hope to look at it soon.

Is your yaml minimal?

**Comment by cmhughes** [comment]
I've been able to verify this undesired behaviour. The following yaml file is minimal
```yaml
modifyLineBreaks:
  optionalArguments:
    RSqBFinishesWithLineBreak: 1
```
I need to look into this. It looks like `indentPreamble` is not being respected with STDIN
