### ISSUE TITLE
Unexpected indentation after square brackets used for open intervals

### ISSUE THREAD

**Issue by AntoineMissier** [cmhughes/latexindent.pl#507]
Please provide the following when posting an issue:

original .tex code
--
```tex
\begin{enumerate}
\item 
The function $u: x \mapsto 1-x + \ln (2x)$ is defined on $]0,+\infty[$ and we obtain 
its derivative $u'$ :
\[u'(x)=-1+\frac{2}{2x}=-1+\frac{1}{x}=\frac{1-x}{x}. \]

\item 
Here we calculate the limits at 0 and $+\infty$ :

\item 
We have $x >0$ on $]0,+\infty[$, thus $u'(x)$ has the same sign as $1-x$.

The maximum of $u$ is $u(1)=\ln2$.

\end{enumerate}
```

yaml settings
--
```yaml

indentAfterItems:
    itemize: 0
    enumerate: 0
    description: 0
    list: 0
specialBeginEnd:
    displayMath:
        begin: '\\\['
        end: '\\\]'
        lookForThis: 1
    inlineMath:
        begin: '(?<!\$)(?<!\\)\$(?!\$)'
        end: '(?<!\\)\$(?!\$)'
        lookForThis: 1
    displayMathTeX:
        begin: '\$\$'
        end: '\$\$'
        lookForThis: 1
    specialBeforeCommand: 0
```

actual/given output
--
```
\begin{enumerate}
	\item
	The function $u: x \mapsto 1-x + \ln (2x)$ is defined on $]0,+\infty[$ and we obtain
				its derivative $u'$ :
				\[u'(x)=-1+\frac{2}{2x}=-1+\frac{1}{x}=\frac{1-x}{x}. \]

				\item
				Here we calculate the limits at 0 and $+\infty$ :

				\item
				We have $x >0$ on $]0,+\infty[$, thus $u'(x)$ has the same sign as $1-x$.

	The maximum of $u$ is $u(1)=\ln2$.

\end{enumerate}
```

desired or expected output
--
```
\begin{enumerate}
	\item
	The function $u: x \mapsto 1-x + \ln (2x)$ is defined on $]0,+\infty[$ and we obtain
	its derivative $u'$ :
	\[u'(x)=-1+\frac{2}{2x}=-1+\frac{1}{x}=\frac{1-x}{x}. \]

	\item
	Here we calculate the limits at 0 and $+\infty$ :

	\item
	We have $x >0$ on $]0,+\infty[$, thus $u'(x)$ has the same sign as $1-x$.

	The maximum of $u$ is $u(1)=\ln2$.

\end{enumerate}
```

anything else
--
When I eliminate the open brackets in the first interval, the problem disappears. What should I change in the defaultSettings.yaml to manage these square brackets correctly ?

**Comment by cmhughes** [comment]
Thanks for this, I hope to get to it soon. Apologies for the delay.

**Comment by cmhughes** [comment]
I present two options:

option 1
-
```yaml
indentAfterItems:
    itemize: 0
    enumerate: 0
    description: 0
    list: 0
specialBeginEnd:
    specialBeforeCommand: 1
```

option 2
-
```yaml
indentAfterItems:
    itemize: 0
    enumerate: 0
    description: 0
    list: 0
fineTuning:
  commands:
    name: (?!infty)[+a-zA-Z@\*0-9_\:]+?
```

Both options give your desired output
```tex
\begin{enumerate}
	\item
	The function $u: x \mapsto 1-x + \ln (2x)$ is defined on $]0,+\infty[$ and we obtain
	its derivative $u'$ :
	\[u'(x)=-1+\frac{2}{2x}=-1+\frac{1}{x}=\frac{1-x}{x}. \]

	\item
	Here we calculate the limits at 0 and $+\infty$ :

	\item
	We have $x >0$ on $]0,+\infty[$, thus $u'(x)$ has the same sign as $1-x$.

	The maximum of $u$ is $u(1)=\ln2$.

\end{enumerate}
```

explanation
-
The issue arises because of `\infty[` which `latexindent.pl` sees as the start of a command. The above solutions both tell `latexindent.pl` that this is not the case.
