### ISSUE TITLE
Another unexpected indentation with square brackets used for open intervals

### ISSUE THREAD

**Issue by AntoineMissier** [cmhughes/latexindent.pl#511]
Please provide the following when posting an issue:

original .tex code
--
```tex
\documentclass[a4paper,11pt]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ibrackets}

\begin{document}

$f(x)= \dfrac{1}{(1-x)^2}$ on $]-\infty, 1[$.
$f$ is convex because
\[ f''(x) = \frac{6}{(1-x)^4} \geq 0. \]
And the tangent in 0 is such that
\[ y=f'(0)(x-0) + f(0) \text{ with } f'(0)=2 \text{ and } f(0)=1, \]
So we can say that, for all $x \in ]-\infty, 1[$,
$f(x) \geq 2x+1$.

\end{document}
```

yaml settings
--
```yaml 
fineTuning:
  commands:
    name: (?!infty)[+a-zA-Z@\*0-9_\:]+?
```
actual/given output
--
```tex
\begin{document}

$f(x)= \dfrac{1}{(1-x)^2}$ on $]-\infty, 1[$.
			$f$ is convex because
				\[ f''(x) = \frac{6}{(1-x)^4} \geq 0. \]
				And the tangent in 0 is such that
				\[ y=f'(0)(x-0) + f(0) \text{ with } f'(0)=2 \text{ and } f(0)=1, \]
				So we can say that, for all $x \in ]-\infty, 1[$,
$f(x) \geq 2x+1$.

\end{document}
```

desired or expected output
--
```
$f(x)= \dfrac{1}{(1-x)^2}$ on $]-\infty, 1[$.
$f$ is convex because
\[ f''(x) = \frac{6}{(1-x)^4} \geq 0. \]
And the tangent in 0 is such that
\[ y=f'(0)(x-0) + f(0) \text{ with } f'(0)=2 \text{ and } f(0)=1, \]
So we can say that, for all $x \in ]-\infty, 1[$,
$f(x) \geq 2x+1$.
```
anything else
--
How to completely deactivate any indentation after square brackets, but not with braces?

**Comment by cmhughes** [comment]
Many thanks. 

I present two options, both give your desired output:

option 1
-
```yaml
fineTuning:
  commands:
    name: (?!infty)[+a-zA-Z@\*0-9_\:]+?
  namedGroupingBracesBrackets:        # <!-- NEW
    name: [.a-zA-Z@\*><]+?            # <!-- NEW
```

options 2
-
```yaml
fineTuning:
  commands:
    name: (?!infty)[+a-zA-Z@\*0-9_\:]+?

specialBeginEnd:
  specialBeforeCommand: 1
```
