### ISSUE TITLE
`-r` switch does not respect `indentPreamble: 0`

### ISSUE THREAD

**Issue by torik42** [cmhughes/latexindent.pl#517]
original .tex code
--
```latex
\documentclass{article}

\usepackage{mathtools}
\DeclarePairedDelimiter{\norm}{\lVert}{\rVert}

\begin{document}

$\lVert A \rVert$

\end{document}
```

yaml settings
--
```yaml
indentPreamble: 0

replacements:
  -
    substitution: |-
      s/
        (?<!\\) \\l?Vert
        \s* (?P<content> .+? ) \s*
        (?<!\\) \\r?Vert
      /\\norm{$+{content}}/sgx
```

actual/given output
--
```latex
\documentclass{article}

\usepackage{mathtools}
\DeclarePairedDelimiter{\norm}{\norm{}{}}

\begin{document}

$\norm{A}$

\end{document}
```

desired or expected output
--
```latex
\documentclass{article}

\usepackage{mathtools}
\DeclarePairedDelimiter{\norm}{\lVert}{\rVert}

\begin{document}

$\norm{A}$

\end{document}
```

anything else
--

My expectation was that replacements would respect the `indentPreamble` key (also the modifylinebreaks switch respects it). One could have a separate setting to enable replacements in the preamble, if one wants them also there. Or a key to only use latexindent for the preamble. This would allow for different configurations for the preamble and the rest by running latexindent twice.

**Comment by cmhughes** [comment]
I have a few ideas on how to do this. Hoping to get to this over the weekend.

**Comment by cmhughes** [comment]
Here are a couple of options, both give your desired output.

option 1
-
Using the following
```yaml
replacements:
  -
    substitution: |-
      s/
        (.*?)(\\begin\{document.*)/
        my $preamble = $1;                    # store preamble
        my $body = $2;                        # store body
        $body =~ s|(?<!\\) \\l?Vert           # 
                   \s* (?P<content> .+? ) \s* # make substitutions
                   (?<!\\) \\r?Vert           # on BODY
                  |\\norm{$+{content}}|sgx;   # 
        $preamble.$body;/esgx                 # reassemble
```
and calling
```
latexindent.pl -l -r myfile.tex
```

option 2
-
Using 
```yaml
specialBeginEnd:
  preamble:
    begin: \\documentclass
    end: \\begin\{document\}
    lookForThis: verbatim

replacements:
  -
    substitution: |-
      s/
        (?<!\\) \\l?Vert           
                   \s* (?P<content> .+? ) \s* 
                   (?<!\\) \\r?Vert           
       /\\norm{$+{content}}/sgx   
```
stores the preamble as a verbatim block and using the `rv` switch as in
```
latexindent.pl -rv -l myfile.tex
```
