### ISSUE TITLE
Can't find string terminator '"' error - bug?

### ISSUE THREAD

**Issue by peske** [cmhughes/latexindent.pl#542]
Please sorry for not following the issue template, but it looks unrelated. First, the tex file(s) are way too long. Second, the error I'm getting does not refer to tex at all, but it looks more like some internal bug.

In short, when running the latest (v3.24) version as part of Gitlab CI/CD pipeline on a Gitlab runner (Ubuntu 24.04 server), I'm getting the following error:

Can't find string terminator '"' anywhere before EOF at /tmp/par-6769746c61622d72756e6e6572/cache-67f49a1963ebec69758cc8b180fc4bc1290fc8fa/inc/lib/LatexIndent/FileExtension.pm line 190.
Compilation failed in require at /tmp/par-6769746c61622d72756e6e6572/cache-67f49a1963ebec69758cc8b180fc4bc1290fc8fa/inc/lib/LatexIndent/Document.pm line 36.
BEGIN failed--compilation aborted at /tmp/par-6769746c61622d72756e6e6572/cache-67f49a1963ebec69758cc8b180fc4bc1290fc8fa/inc/lib/LatexIndent/Document.pm line 36.
Compilation failed in require at script/latexindent.pl line 28.
BEGIN failed--compilation aborted at script/latexindent.pl line 28.

However, when I roll back to latexindent v3.23.6, 2024-01-17 on the same machine (that comes by default with `sudo apt-get install texlive-full`), everything is OK, and the pipeline succeeds.

**Comment by cmhughes** [comment]
Please provide a minimal file and instructions so that I can experiment

**Comment by peske** [comment]
I would really like to help, but sharing the tex file is not possible for two reasons:

- First it's a huge file (in fact it's a main.tex file that includes dozens of huge tex files), resulting in ~100 pages long PDF, with several hundreds equations...
- More importantly, the content of the file is a secret that I'm not allowed to share.

However, I can share with you configs, if it may help. So `defaultSettings.json` files are identical for both mentioned versions, and unchanged after the installation. There is a local `.latexindent.yaml` file in the workspace directory, with the following content:

```yaml
defaultIndent: "    "

noAdditionalIndent:
  textbf: 1
  emph: 1

modifyLineBreaks:
  textWrapOptions:
    columns: 81
    when: after

replacements:
  -
    when: before
    substitution: |-
      s/%\h*chktex\h*35//sg
  -
    when: after
    substitution: |-
      s/(_\{(min|max)(_|\}).*$)/$1 % chktex 35/mg
```

The command is executed with the following flags:

```console
latexindent -kv --local=.latexindent.yaml,../.latexindent.yaml --modifylinebreaks --replacement --silent
```

I hope it helps.
