### ISSUE TITLE
Wrong indentation for equation in command with subscript in superscript

### ISSUE THREAD

**Issue by cgahr** [cmhughes/latexindent.pl#554]
original .tex code
--
```tex
% doesn't work
\textsf{
$\mathbb{R}^{N_\mathrm{state}}$.
}

% works
\textsf{
$R^{N_\mathrm{state}}$.
}
\textsf{
$\mathbb{R}^{N_s}$.
}

```

yaml settings
--
reproducible with default settings, I use
```yaml
defaultIndent: "    "
indentRules:
    item: ""

modifyLineBreaks:
    condenseMultipleBlankLinesInto: 1
    items:
        ItemStartsOnOwnLine: 4

lookForAlignDelims:
   tabular: 0

verbatimEnvironments:
   tabular: 1
```

actual/given output
--
```tex
% doesn't work
\textsf{
$\mathbb{R}^{N_\mathrm{state}}$.
}

% works
\textsf{
    $R^{N_\mathrm{state}}$.
}
\textsf{
    $\mathbb{R}^{N_s}$.
}
```

desired or expected output
--
```tex
% doesn't work
\textsf{
    $\mathbb{R}^{N_\mathrm{state}}$.
}

% works
\textsf{
    $R^{N_\mathrm{state}}$.
}
\textsf{
    $\mathbb{R}^{N_s}$.
}
```
