### ISSUE TITLE
Incorrect indentation in argument

### ISSUE THREAD

**Issue by Rdeisenroth** [cmhughes/latexindent.pl#555]
Please provide the following when posting an issue:

original .tex code
--
```latex
% Expl3
\msg_new:nnnn {org/pkg} {some~text} {
this~should~be~indented
}{This~{breaks}~the~indentation}
```

yaml settings
--
```yaml
fileExtensionPreference:
  .tex: 1
  .sty: 2
  .cls: 3
  .bib: 4
  .cfg: 5
  
defaultIndent: "\t"

noAdditionalIndentGlobal:
  environments: 0
  commands: 1
  optionalArguments: 0
  mandatoryArguments: 0
  ifElseFi: 0
  items: 0
  keyEqualsValuesBracesBrackets: 1
  namedGroupingBracesBrackets: 1
  UnNamedGroupingBracesBrackets: 1
  specialBeginEnd: 0
  afterHeading: 0
  filecontents: 0
```

actual/given output
--
```latex
% Expl3
\msg_new:nnnn {org/pkg} {some~text} {
this~should~be~indented
}{This~{breaks}~the~indentation}
```

desired or expected output
--
```latex
% Expl3
\msg_new:nnnn {org/pkg} {some~text} {
    this~should~be~indented
}{This~{breaks}~the~indentation}
```

anything else
--
the ~{} seems to break it
