### ISSUE TITLE
Labels in the same line as `\begin`

### ISSUE THREAD

**Issue by DanielDelimata** [cmhughes/latexindent.pl#556]
original .tex code
--
```
\documentclass[11pt]{article}
\usepackage{amsmath}

% Document
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
\begin{equation}\label{eq:1}E=mc^{2}\end{equation}
Quisque tincidunt mauris a sapien vestibulum hendrerit. Pellentesque in erat scelerisque, venenatis orci a, aliquam turpis.

Aliquam purus nisi, posuere vel molestie convallis, lobortis quis est.
\begin{equation}E=mc^{2}\end{equation}Phasellus pretium dignissim lorem ullamcorper blandit. Integer nec sollicitudin turpis.
Sed non ultricies nisl.
\begin{remark}[see some reference]\label{rm:1}Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
amet urna. In et felis ac risus luctus blandit.
\end{remark}
\begin{remark} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
amet urna. In et felis ac risus luctus blandit.
\end{remark}
\end{document}
```

yaml settings
--
```
defaultIndent: '    '

modifyLineBreaks:
    textWrapOptions:
        columns: 80
    when: after
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 1      # -1,0,1,2,3,4
        SpecialBodyStartsOnOwnLine: 1       # -1,0,1,2,3,4
        SpecialEndStartsOnOwnLine: 1        # -1,0,1,2,3,4
        SpecialEndFinishesWithLineBreak: 1  # -1,0,1,2,3,4
    environments:
        BeginStartsOnOwnLine: 1             # -1,0,1,2,3,4
        BodyStartsOnOwnLine: 1              # -1,0,1,2,3,4
        EndStartsOnOwnLine: 1               # -1,0,1,2,3,4
        EndFinishesWithLineBreak: 1         # -1,0,1,2,3,4


fineTuning:
    environments:
        begin: \\begin\{([a-zA-Z@\*0-9_\\]+)\}\s*\\label\{[^}]+?\}
        end: \\end\{\2\}
```

actual/given output
--
```
\documentclass[11pt]{article}
\usepackage{amsmath}

% Document
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
\begin{equation}\label{eq:1}
    E=mc^{2}
\end{equation}
Quisque tincidunt mauris a sapien vestibulum hendrerit. Pellentesque in erat scelerisque, venenatis orci a, aliquam turpis.

Aliquam purus nisi, posuere vel molestie convallis, lobortis quis est.
\begin{equation}E=mc^{2}\end{equation}Phasellus pretium dignissim lorem ullamcorper blandit. Integer nec sollicitudin turpis.
Sed non ultricies nisl.
\begin{remark}[see some reference]\label{rm:1}Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
amet urna. In et felis ac risus luctus blandit.
\end{remark}
\begin{remark} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
amet urna. In et felis ac risus luctus blandit.
\end{remark}
\end{document}
```

desired output
--
```
\documentclass[11pt]{article}
\usepackage{amsmath}

% Document
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
\begin{equation}\label{eq:1}
    E=mc^{2}
\end{equation}
Quisque tincidunt mauris a sapien vestibulum hendrerit. Pellentesque in erat
scelerisque, venenatis orci a, aliquam turpis.

Aliquam purus nisi, posuere vel molestie convallis, lobortis quis est.
\begin{equation}
    E=mc^{2}
\end{equation}
Phasellus pretium dignissim lorem ullamcorper blandit. Integer nec sollicitudin
turpis. Sed non ultricies nisl.
\begin{remark}[see some reference]\label{rm:1}
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
    rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
    volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
    amet urna. In et felis ac risus luctus blandit.
\end{remark}
\begin{remark}
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
    rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
    volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
    amet urna. In et felis ac risus luctus blandit.
\end{remark}
\end{document}
```

anything else
--
I would like to create modified fine-tuning regex to achieve the following things:
* labels should be in the same line as `\begin`
* indentation should be the same in case of label presence and absence
* correct wrapping inside and outside of environments

Unfortunately, I see some problems when trying to use additional capturing parentheses around label.

**Comment by cmhughes** [comment]
Apologies for the delay.

Is your example as minimal as it can be?

**Comment by DanielDelimata** [comment]
Hello,
No problem. Paragraphs could be shorter. First paragraph can be omitted. Sorry for inconvenience.

**Comment by cmhughes** [comment]
Many thanks. Is there any chance you could update your code?

**Comment by DanielDelimata** [comment]
Hello,
Yes of course. I have just updated it.

**Comment by cmhughes** [comment]
Thanks so much , that's really helpful. I'm hoping to get to this soon.

**Comment by cmhughes** [comment]
Apologies again for the delay.

solution
-
Using the following settings `mysettings.yaml`
```yaml
defaultIndent: '    '
modifyLineBreaks:
    textWrapOptions:
        columns: 80
        when: after
        blocksFollow:
          other: \\end\{equation\}|\\\]|\\item(?:\h|\[)       # regex
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 1      # -1,0,1,2,3,4
        SpecialBodyStartsOnOwnLine: 1       # -1,0,1,2,3,4
        SpecialEndStartsOnOwnLine: 1        # -1,0,1,2,3,4
        SpecialEndFinishesWithLineBreak: 1  # -1,0,1,2,3,4
    environments:
        BeginStartsOnOwnLine: 1             # -1,0,1,2,3,4
        BodyStartsOnOwnLine: 1              # -1,0,1,2,3,4
        EndStartsOnOwnLine: 1               # -1,0,1,2,3,4
        EndFinishesWithLineBreak: 1         # -1,0,1,2,3,4
    commands:
      label:
        CommandStartsOnOwnLine: -1
    mandatoryArguments:
      label:
        RCuBFinishesWithLineBreak: 1        # -1,0,1,2,3,4

replacements:
  - 
    substitution: |-
      s/(\\begin\{[^}]+?\})\s*(\\label)/$1$2/sg
    when: after
```
and called with
```
latexindent.pl -m -l mysettings.yaml -r myfile.tex
```
gives the output
```tex
\documentclass[11pt]{article}
\usepackage{amsmath}

% Document
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
\begin{equation}\label{eq:1}
    E=mc^{2}
\end{equation}
Quisque tincidunt mauris a sapien vestibulum hendrerit. Pellentesque in erat
scelerisque, venenatis orci a, aliquam turpis.

Aliquam purus nisi, posuere vel molestie convallis, lobortis quis est.
\begin{equation}
    E=mc^{2}
\end{equation}
Phasellus pretium dignissim lorem ullamcorper blandit. Integer nec sollicitudin
turpis. Sed non ultricies nisl.
\begin{remark}[see some reference]\label{rm:1}
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
    rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
    volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
    amet urna. In et felis ac risus luctus blandit.
\end{remark}
\begin{remark}
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mi urna,
    rhoncus nec leo a, vulputate ornare nisi. Nam varius, turpis ultrices
    volutpat scelerisque, ipsum lorem consequat mi, id rutrum urna metus sit
    amet urna. In et felis ac risus luctus blandit.
\end{remark}
\end{document}
```

I hope this is as you would like, let me know if not!
