### ISSUE TITLE
noIndentBlock behaviour inconsistent between .tex and .cls files

### ISSUE THREAD

**Issue by Ned-Stevenson** [cmhughes/latexindent.pl#562]
The behavior of the noIndentBlock changes depending on the file type of the file being formatted. If using a `.tex` file, the noIndentBlock doesn't seem to properly close, while it seems to behave as expected in a `.cls` file. The desired output can be achieved in this case by renaming the source code file being formatted from `project.tex` to `project.cls`.

original .tex code
--
```
% OxCSProject

% Originally by Keith A. Gillow (gillow@maths.ox.ac.uk), 1997
% Modified by Sam Evans (sam@samuelevansresearch.org), 2007
% Modified by John McManigle (john@oxfordechoes.com), 2015
% Adapted by Ned Stevenson (edward.stevenson@cs.ox.ac.uk), 2024
%
% This version Copyright (c) 2024 Ned Stevenson
%
% Broad permissions are granted to use, modify, and distribute this software
% as specified in the MIT License included in this distribution's LICENSE file.




% This document is intended as a template to help get started with using LaTeX for your project report. I was recommended a thesis template by my supervisor, and found it very helpful after some quite extensive modification
```

yaml settings
--
```
# This listing configures the behaviour of the formatter on line breaks and rearranging lines
# Refer to documentation for how to add to these settings to fit your needs
# https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#text-wrapping
modifyLineBreaks:
  textWrapOptions:
      # Up to 99 characters per line. Change this to fit your preference
      columns: 99
      # Text wrapping happens after indentation, meaning indentation is included in the column limit
      when: after
      comments:
        # Apply wrapping to comments too, splitting/combining across lines if needed
        wrap: 1

noIndentBlock:
  copyrightSlug:
    # TODO - Implement this. Should go from the start of the file to the first command
    begin: '%\hOxCSProject'
    end: '\v\v\v'
    lookForThis: 1
  headerComments:
    # A line that starts with %%% should not be rearranged
    begin: '%%%'
    end: '\v'
    lookForThis: 1
```
actual/given output
--
```
% OxCSProject

% Originally by Keith A. Gillow (gillow@maths.ox.ac.uk), 1997
% Modified by Sam Evans (sam@samuelevansresearch.org), 2007
% Modified by John McManigle (john@oxfordechoes.com), 2015
% Adapted by Ned Stevenson (edward.stevenson@cs.ox.ac.uk), 2024
%
% This version Copyright (c) 2024 Ned Stevenson
%
% Broad permissions are granted to use, modify, and distribute this software
% as specified in the MIT License included in this distribution's LICENSE file.




% This document is intended as a template to help get started with using LaTeX for your project report. I was recommended a thesis template by my supervisor, and found it very helpful after some quite extensive modification
```

desired or expected output
--
```
% OxCSProject

% Originally by Keith A. Gillow (gillow@maths.ox.ac.uk), 1997
% Modified by Sam Evans (sam@samuelevansresearch.org), 2007
% Modified by John McManigle (john@oxfordechoes.com), 2015
% Adapted by Ned Stevenson (edward.stevenson@cs.ox.ac.uk), 2024
%
% This version Copyright (c) 2024 Ned Stevenson
%
% Broad permissions are granted to use, modify, and distribute this software
% as specified in the MIT License included in this distribution's LICENSE file.




% This document is intended as a template to help get started with using LaTeX for your project
% report. I was recommended a thesis template by my supervisor, and found it very helpful after
% some quite extensive modification
```

anything else
--
latexindent being run as the formatter for the LaTeX Workshop VSCode extension on Windows 11.
latexindent version is `3.24.1`.
Additional arguments properly defined in extension settings to allow `-m` flag and appropriate configuration.
