### ISSUE TITLE
>= breaks parsing

### ISSUE THREAD

**Issue by NeilGirdhar** [cmhughes/latexindent.pl#565]
Please provide the following when posting an issue:

original .tex code
--
```tex
\tikzset{
/Flow diagram/.style={
% Node placement
auto,
node distance=14mm and 14mm,
on grid,
% Edge style
thick,
->,
>=Stealthy[round],
% Node border styles
rectangle/.style={shape=rectangle, draw, rounded corners, minimum size=8mm},
state/.style={shape=circle, draw, inner sep=0pt, minimum size=6.8mm},
no_border/.style={shape=rectangle, inner sep=1pt},
% Node fill styles
unobserved/.style={},
intervention/.style={dcolorb, very thick, fill=dcolorb!30},
observation/.style={dcoloro, very thick, fill=dcoloro!30},
%
annotation_brace/.style={-,decoration={brace,amplitude=7pt},decorate,thick,color=ann_col},
%
roundline/.style={rounded corners=4mm}
},
}
```

yaml settings
--
```yaml
onlyOneBackUp: 1
maxNumberOfBackUps: 1
logFilePreferences:
  showEveryYamlRead: 0

indentPreamble: 1
defaultIndent: "  "
```

actual/given output
--
(unchanged)

desired or expected output
--
```tex
\tikzset{
  /Flow diagram/.style={
    % Node placement
    auto,
    node distance=14mm and 14mm,
    on grid,
    % Edge style
    thick,
    ->,
    >=Stealthy[round],
    % Node border styles
    rectangle/.style={shape=rectangle, draw, rounded corners, minimum size=8mm},
    state/.style={shape=circle, draw, inner sep=0pt, minimum size=6.8mm},
    no_border/.style={shape=rectangle, inner sep=1pt},
    % Node fill styles
    unobserved/.style={},
    intervention/.style={dcolorb, very thick, fill=dcolorb!30},
    observation/.style={dcoloro, very thick, fill=dcoloro!30},
    %
    annotation_brace/.style={-,decoration={brace,amplitude=7pt},decorate,thick,color=ann_col},
    %
    roundline/.style={rounded corners=4mm}
  },
}
```

Does not get indented because `>=` breaks the parser.

**Comment by NeilGirdhar** [comment]
Similarly, this doesn't parse for some odd reason:
```tex
\tikzset{
/CMA tips/.style={
% blue: carries deduction and explanation signals.
% orange: carries selection-like signals.
% red: carries pooling-like signals.
% green: carries the GLN.
tip_explanation/.tip={Semicircle[dcolorb]},
tip_deduction/.tip={ProperCircle[dcolorb]},
tip_retro_deduction/.tip={ProperCircle[open, dcolorb]},
tip_screening/.tip={ReverseFlatInverted[dcolorb]},
tip_pooling/.tip={ProperSquare[dcoloro]},
tip_retro_pooling/.tip={ProperSquare[open, dcoloro]},
tip_control/.tip={Parenthesis[reversed, sep=1pt] tip_pooling},
tip_retro_control/.tip={Parenthesis[reversed, sep=1pt] tip_retro_pooling},
tip_reward/.tip={FlatInverted[dcoloro]},
tip_waking/.tip={Semicircle[dcoloro, reversed]},
tip_gln/.tip={Diamond[dcolorg]},
tip_variational/.tip={InvertedDiamond[dcolorr]},
% Cotangents:
tip_cotangent/.tip={Bar[sep=1pt]},
tip_co_explanation/.tip={tip_cotangent[dcolorb] tip_explanation},
},
}
```

**Comment by cmhughes** [comment]
Please use the issue template and I'll try to help

**Comment by NeilGirdhar** [comment]
Thank you.  I've edited the issue.

**Comment by cmhughes** [comment]
Using the following
```yaml
onlyOneBackUp: 1
maxNumberOfBackUps: 1
logFilePreferences:
  showEveryYamlRead: 0

indentPreamble: 1
defaultIndent: "  "

fineTuning:
  namedGroupingBracesBrackets:
    name: [0-9\.a-zA-Z@\*><=]+?            #<!---- NEW BIG
```
gives your desired output.
