### ISSUE TITLE
oneSentencePerLine: put inline math on separate lines

### ISSUE THREAD

**Issue by clason** [cmhughes/latexindent.pl#567]
**Context:** I need to translate a bunch of lecture notes (and no, I'm not going to ChatGPT it ;)), which basically means a sentence-by-sentence rewrite of the text (only!). I would like to use `latexindent` to facilitate this, since the biggest time-cost is writing "around" inline math.

I have managed to write a `latexindent` config to split sentences (which took a surprising amount of config golfing!), but I'm struggling to separate the inline math. Take the following example:

```tex
Consider the following
\begin{theorem}
  Let $A$ be a wuffle. Then $A$ is a piffle if
  \begin{equation*}
    A + A = A
  \end{equation*}
\end{theorem}
```
I would like this to be formatted as
```tex
Consider the following
\begin{theorem}
  Let 
  $A$
  be a wuffle.
  Then
  $A$
  is a piffle if
  \begin{equation*}
    A + A = A
  \end{equation*}
\end{theorem}
```
(Indentation is not important.)

I tried the following config (sharing this because I found all these non-default settings necessary to support cases like end-of-sentence inline math or parenthesized sentences)
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    sentencesFollow:
      rightBrace: 0
      other: "\$\."
    sentencesBeginWith:
      a-z: 1
      other: "\("
    sentencesEndWith:
      other: "\.\)|\$\.|\n"
```
but this of course does not separate inline math. I tried adding `\$` to the three `other` fields, but this will introduce line breaks _after_ the opening `$`, not before:
```tex
Consider the following
\begin{theorem}
    Let $
        A$
    be a wuffle.
    Then $
        A$
    is a piffle if
    \begin{equation*}
        A + A = A
    \end{equation*}
\end{theorem}
```

Is there some way to make this work?

**Comment by clason** [comment]
Thank you! I'm sorry I missed this option in the documentation.

(This is a stretch goal, but would it be possible to keep closing `$.`, `$,`, and `$;` on the same line, i.e.,
```tex
This is an inline formula
$1+1=2$.
```
instead of 
```tex
This is an inline formula
$1+1=2$
.
```
?)

**Comment by cmhughes** [comment]
Try appending the following part of fine tuning
```

      (?:                                 #
        (?<!                              # not *preceded by*
          (?:                             #
            (?:[eE]\.[gG])                # e.g OR E.g OR e.G OR E.G
            |                             #
            (?:[iI]\.[eE])                # i.e OR I.e OR i.E OR I.E
            |                             #
            (?:etc)                       # etc
            |                             #
            (?:[wW]\.[rR]\.[tT])          # w.r.t OR W.r.t OR w.R.t OR w.r.T OR W.R.t OR W.r.T OR w.R.T OR W.R.T
          )                               #
        )                                 #
      )                                   # 
      \.

**Comment by clason** [comment]
Where would I put this exactly?

**Comment by cmhughes** [comment]
https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html

**Comment by clason** [comment]
I tried that, but it made no difference, sorry.

**Comment by cmhughes** [comment]
input.tex
-
```
Consider the following
\begin{theorem}
  Let $A$ be a wuffle. Then $A$ is a piffle if
  \begin{equation*}
    A + A = A
  \end{equation*}
  This is an inline formula
$1+1=2$.
\end{theorem}
```

latexindent.yaml
-
```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1              # 0/1
    removeSentenceLineBreaks: 0         # 0/1
  specialBeginEnd:
    inlineMath:
      SpecialBeginStartsOnOwnLine: 1      # -1,0,1,2,3,4
      SpecialEndFinishesWithLineBreak: 1  # -1,0,1,2,3,4

replacements:
  - 
    when: after
    substitution: |-
      s/\$\h*\R\h*\./\$\./sg
```
call
-
```
latexindent.pl -l -r -m myfile.tex
```
output
-
```tex
Consider the following
\begin{theorem}
	Let
	$A$
	be a wuffle.
	Then
	$A$
	is a piffle if
	\begin{equation*}
		A + A = A
	\end{equation*}
	This is an inline formula
	$1+1=2$.
\end{theorem}
```
