### ISSUE TITLE
Can't locate object method "new" via package "Unicode::GCString" 

### ISSUE THREAD

**Issue by trarer** [cmhughes/latexindent.pl#569]
Please provide the following when posting an issue:

original .tex code
--
*Please paste your .tex code here. Please note in answering your issue, I may add the code you provide to the test-cases directory. Please detail explicitly if you would prefer me not to do so.*.

yaml settings
--
*Please paste your YAML settings (if any) here*

actual/given output
--
*Please paste the output you receive here*

desired or expected output
--
*Please paste your desired/expected output here; that is, what do you want the output to look like*

anything else
--
*Please put any comments or anything else here :)*

**Comment by cmhughes** [comment]
I'm unable to replicate this. Your yaml is not formatted correctly.

Using
```yaml
lookForAlignDelims:
  tabular:
    delims: 1
    multiColumnGrouping: 1
  tabularx:
    delims: 1
    multiColumnGrouping: 1
```
and the call
```
latexindent.pl  -l  --GCString myfile.tex
```
I don't get the output that you've posted. Please complete the issue template. you might also post your log file.
