### ISSUE TITLE
Blank lines before and after environments or sections

### ISSUE THREAD

**Issue by aronovgj** [cmhughes/latexindent.pl#57]
The new version is awesome. The only thing I currently miss is these options (maybe I just can not find it):

I prefer to have my code formatted like this:

```
some text

\[
    something
\]

some other text
```

as well as 

```
some text

\begin{env1}
    \begin{env2}
        something
    \end{env2}
\end{env1}

some other text
```

as well as 

```
\section{something}

    some text

    \subsection{some other thing}
    
        some other text

\section{yet another thing}
```

Note the empty lines before and after an environment or section.

Thanks for your work.

**Comment by cmhughes** [comment]
Thanks very much for your message :)

Could I clarify: do you mean a situation in which, when the m switch is
active, a blank line is added before/after the beginning/end of a thing?

**Comment by aronovgj** [comment]
Yes, that is another way to put it :)

**Comment by cmhughes** [comment]
Thanks for following up.

So, to clarify, let's say that you started with the following:

```text \[ x^2 \] text

text \begin{one}one text\end{one} text
```

You'd like to be able to specify the `polyswitches` in such a way that the output would be:

```
text 

\[ 
x^2 
\] 

text

text 

\begin{one}
  one text
\end{one} 

text
```

On it's own, I think that this could be do-able (although you know that blank lines can affect vertical spacing, right?). I'd guess that it would be introducing a new value for each `polyswitch`, say 3, so that it represented adding a blank line before/after the end of each thing?

The issue would be with the nesting -- you could specify the YAML on a per-name basis: this means that, in your example, you could specify settings for `env1` and for `env2` but I can't think of a way to automate the decision around nesting.

Let me know what you think!

Let me know what you think.

**Comment by aronovgj** [comment]
> So, to clarify, let's say that you started with the following:

> `text \begin{one}one text\end{one} text`


Accordung to your output I'd start out with something like:
`text \[x^2\] text` 

`text \begin{one}one text\end{one} text`

But yes, that looks correct.

> On it's own, I think that this could be do-able (although you know that blank lines can affect vertical spacing, right?)

Yes, I am aware. I usually use the same document class so that is ok. If I get problems with this in another class I just can disable it. 

>The issue would be with the nesting -- you could specify the YAML on a per-name basis: this means that, in your example, you could specify settings for env1 and for env2 but I can't think of a way to automate the decision around nesting.

For things like `\[x^2\]` nesting would be useless anyway because you can't do something like `\[\[x^2\]\]`. It would just be for the `\begin{env} \end{env}` environments. So I don't see why you would want to do that on a per-name basis, except I overlooked a major issue.
I thought of just counting the `\begin`s and `\end`s. You'd have a counter for the environments and if you have more than one `\begin` that was not closed by an `\end` with the same environment name then you don't add a blank line before and after this environment. Else you do add blank lines before and after. 

Example:
You start with counter = 0. On every `\begin` you increase your counter, on every `\end` you decrease it. If counter is > 0 you do nothing, if counter = 0 you add blank lines before and after the env
```
%counter=0
\begin %counter=1 
\end   %counter=0 -> add blank lines before and after env
\begin %counter=1 
\begin %counter=2 
\end   %counter=1 -> do nothing
\begin %counter=2
\end   %counter=1 -> do nothing
\end   %counter=0 -> add blank lines before and after env
```

Result:
```
%counter=0
\begin 
\end   


\begin
\begin
\end  
\begin 
\end   
\end 
```

Now you just remove double blank lines which latexindent already does. Or you can do it in one step by checking whether there is already a blank line or not when you add it.

**Comment by cmhughes** [comment]
Thanks for the follow-up.

> It would just be for the \begin{env} \end{env} environments. 

This is a bit of an issue, as one of the things that I'm keen to keep from v3.0 onwards is that there are analogous switches for each type of code block.

> I thought of just counting the \begins and \ends. You'd have a counter for the environments and if you have more than one \begin that was not closed by an \end with the same environment name then you don't add a blank line before and after this environment. 

This is also problematic, as the script works by matching code blocks, not particular statements. 

I can see a situation in which code like the following is produced:
```
text 

\begin{one}
  one text
\end{one} 

text
```

It would also mean that, for example,
```
text\begin{one}one text\begin{two}two text\end{two}\end{one}text
```
could be transformed into
```
text 

\begin{one}
  one text

  \begin{two}
  two text
\end{two}
\end{one} 

text
```
As I said above, imagining that the YAML switches set for the `two` environment were specified differently, it would be possible to have, for example,

```
text 

\begin{one}
  one text
  \begin{two}
  two text
\end{two}
\end{one} 

text
```

I'd envisage that this would mean a new value for *all* polyswitches -- it would probably be a value of 3, as -1, 0, 1, 2 are already taken. It would mean something like 'add a new line' mode. How does this sound?

**Comment by aronovgj** [comment]
Not sure if it was intended. the output should be:
```
text 

\begin{one}
  one text
  \begin{two}
    two text
  \end{two}
\end{one} 

text
```

and not 

```
text 

\begin{one}
  one text
  \begin{two}
  two text
\end{two}
\end{one} 

text
```

Otherwise that sounds good. Thank you.

**Comment by cmhughes** [comment]
Yes, indeed your corrected output is correct :)

I'll label this as an enhancement; as you can see, there are a few other enhancements ahead of this one, but yours is on the list :)

**Comment by cmhughes** [comment]
Now that 75.2 is resolved (https://github.com/cmhughes/latexindent.pl/issues/75) I'm hopeful that this feature will be the next one to be developed. Watch this space for updates!

**Comment by cmhughes** [comment]
Development of this feature is happening on https://github.com/cmhughes/latexindent.pl/tree/feature/blank-line-poly-switch. 

So far, I have a version that works as expected for `environments`. For example, starting with
```
before text \begin{myenv} body text \end{myenv} after text

before text \begin{myenv} body text \end{myenv}%

before text \begin{myenv} body text \end{myenv}  %
```
and the settings
```
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 3
        BodyStartsOnOwnLine: 3
        EndStartsOnOwnLine: 3
        EndFinishesWithLineBreak: 3
```
then the following output can be achieved:
```
before text

\begin{myenv}

	body text

\end{myenv} 

after text

before text

\begin{myenv}

	body text

\end{myenv}

%

before text

\begin{myenv}

	body text

\end{myenv}  

%
```
Note that blank lines have been added.

It remains to test the other code blocks, which will be my next latexindent-related task.

**Comment by cmhughes** [comment]
As a further example, starting with
```
text\begin{one}one text\begin{two}two text\end{two}\end{one}text
```
and the YAML file:
```
modifyLineBreaks:
    environments:
        one:
            BeginStartsOnOwnLine: 3
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 3
        two:
            BeginStartsOnOwnLine: 1
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 1
```
then the following output is achieved
```
text

\begin{one}
	one text
	\begin{two}
		two text
	\end{two}
\end{one}

text
```

**Comment by cmhughes** [comment]
@aronovgj you'll see that I've pushed a fair few test cases that demonstrate this new feature. 

If you start with the following `.tex` file:

```
\begin{myenv}
  \part{main title} part body\chapter{\emph{emphasise}title text} body text body text \section{section text} section body \section{section text} section body \subsection{sub title}subsection body subsection body\subsubsection{subsub section title}subsubsubsubsubsubsub\chapter{second chapter} chapter body chapter body\part{another part} more parts!\chapter{more chapter! :)}some mathematics: \[x^2\]\subsection{and some section}to wrap things up
\end{myenv}
```

and the following `YAML`:
```
indentAfterHeadings:
    part:
       indentAfterThisHeading: 1
       level: 1
    chapter: 
       indentAfterThisHeading: 1
       level: 2
    section:
       indentAfterThisHeading: 1
       level: 3
    subsection:
       indentAfterThisHeading: 1
       level: 4
    subsection*:
       indentAfterThisHeading: 1
       level: 4
    subsubsection:
       indentAfterThisHeading: 1
       level: 5
    paragraph:
       indentAfterThisHeading: 1
       level: 6
    subparagraph:
       indentAfterThisHeading: 1
       level: 7
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    commands:
        CommandStartsOnOwnLine: 1
        emph:
            CommandStartsOnOwnLine: 0
        part:
            CommandStartsOnOwnLine: 3
        chapter:
            CommandStartsOnOwnLine: 3
        section:
            CommandStartsOnOwnLine: 3
        subsection:
            CommandStartsOnOwnLine: 3
        subsubsection:
            CommandStartsOnOwnLine: 3
    mandatoryArguments:
        RCuBFinishesWithLineBreak: 1
        emph:
            RCuBFinishesWithLineBreak: 0
        part:
            RCuBFinishesWithLineBreak: 3
        chapter:
            RCuBFinishesWithLineBreak: 3
        section:
            RCuBFinishesWithLineBreak: 3
        subsection:
            RCuBFinishesWithLineBreak: 3
        subsubsection:
            RCuBFinishesWithLineBreak: 3
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 3
        SpecialBodyStartsOnOwnLine: 3
        SpecialEndStartsOnOwnLine: 3
        SpecialEndFinishesWithLineBreak: 3
```

then you should receive the following output
```
\begin{myenv}
	\part{main title} 

		part body

		\chapter{\emph{emphasise}title text} 

		 body text body text

		 \section{section text} 

		  section body

		 \section{section text} 

		  section body

		  \subsection{sub title}

			  subsection body subsection body

			  \subsubsection{subsub section title}

				  subsubsubsubsubsubsub

		\chapter{second chapter} 

		 chapter body chapter body

	\part{another part} 

		more parts!

		\chapter{more chapter! :)}

		 some mathematics:

		 \[

			 x^2

		 \]

		 \subsection{and some section}

			 to wrap things up
\end{myenv}
```

Is this as you would like? If you'd like to do some of your own testing, do feel free! You'll need to clone the following fork: https://github.com/cmhughes/latexindent.pl/tree/feature/blank-line-poly-switch

If I don't hear from you, I'll assume that this is as you would like, get it documented, and ready for release :)

**Comment by aronovgj** [comment]
I modified my `defaultSettings.yaml`. So I am not sure if I missed something but I got this when trying to format a document.

```Use of uninitialized value $LatexIndent::Indent::masterSettings{"maximumIndentation"} in pattern match (m//) at C:/Program Files/MiKTeX 2.9/scripts/latexindent/LatexIndent/Indent.pm line 236.```

**Comment by aronovgj** [comment]
So it seems to do all I want it to do except for adding a line break before and after `section`, `subsection` and so on. Not sure how I would have to modify it for that.
setting `RCuBFinishesWithLineBreak` to 1 for example creates a line break after each `}` as far as I understand. But I want to limit it only to the sections.

This is my complete `defaultSettings.yaml`:

```
# defaultSettings.yaml for latexindent.pl, version 3.1, 2017-05-27
#                      a script that aims to
#                      beautify .tex, .sty, .cls files
#
# (or latexindent.exe if you're on Windows)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# See http://www.gnu.org/licenses/.
# 
# Chris Hughes, 2017
# 
# For all communication, please visit: https://github.com/cmhughes/latexindent.pl


# You're welcome to change anything you like in here, but 
# it would probably be better to have your own user settings 
# files somewhere else- remember that this file may be overwritten
# anytime that you update your distribution. Please see the manual
# for details of how to setup your own settings files.
#
# Please read the manual first to understand what each switch does.

# latexindent can be called without a file extension, 
# e.g, simply
#       latexindent myfile
# in which case the choice of file extension is chosen
# according to the choices made in fileExtensionPreference
# Other file extensions can be added.
fileExtensionPreference:
    .tex: 1
    .sty: 2
    .cls: 3
    .bib: 4

# default file extension of backup file (if original is overwritten with -w switch)
# for example, if your .tex file is called
#       myfile.tex
# and you specify the backupExtension as BACKUP.bak then your 
# backup file will be
#       myfileBACKUP.bak
backupExtension: .bak

# only one backup per file; if onlyOneBackUp is 0 then the
# number on the extension increments by 1 each time
# (this is in place as a safety measure) myfile.bak0, myfile.bak1, myfile.bak2
#
# if you set onlyOnebackUp to 1, then the backup file will
# be overwritten each time (not recommended until you trust the script)
onlyOneBackUp: 0

# some users may only want a set number of backup files, 
# say at most 3; in which case, they can change this switch.
# If maxNumberOfBackUps is set to 0 (or less) then infinitely 
# many backups are possible, unless onlyOneBackUp is switched on
maxNumberOfBackUps: 4

# some users may wish to cycle through back up files, for example, 
# with maxNumberOfBackUps: 4, they may wish to delete the oldest
# back up file, and keep only the most recent.
#
#    copy myfile.bak1 to myfile.bak0
#    copy myfile.bak2 to myfile.bak1
#    copy myfile.bak3 to myfile.bak2
#    copy myfile.bak4 to myfile.bak3
#
# the back up will be written to myfile.bak4
cycleThroughBackUps: 1

# preferences for information displayed in the log file
logFilePreferences:
    showEveryYamlRead: 1
    showAmalgamatedSettings: 0
    endLogFileWith: '--------------' 
    showGitHubInfoFooter: 1

#  verbatim environments- environments specified 
#  in this hash table will not be changed at all!
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1

#  verbatim commands such as \verb! body !, \lstinline$something else$
verbatimCommands:
    verb: 1
    lstinline: 1

#  no indent blocks (not necessarily verbatim 
#  environments) which are marked as %\begin{noindent}
#  or anything else that the user puts in this hash
#  table
noIndentBlock:
    noindent: 1
    cmhtest: 1

# remove trailing whitespace from all lines 
removeTrailingWhitespace:
    beforeProcessing: 0
    afterProcessing: 1

# \begin{document} and \end{document} are treated differently
# by latexindent within filecontents environments
fileContentsEnvironments:
    filecontents: 1
    filecontents*: 1

# indent preamble
indentPreamble: 0

# assume no preamble in cls, sty, by default
lookForPreamble:
    .tex: 1
    .sty: 0
    .cls: 0
    .bib: 0

# some preambles can contain \begin and \end statements
# that are not in their 'standard environment block', for example,
# consider the following key = values:
#    preheadhook={\begin{mdframed}[style=myframedstyle]},
#    postfoothook=\end{mdframed},
preambleCommandsBeforeEnvironments: 0

# Default value of indentation
defaultIndent: "\t"

# environments that have tab delimiters, add more 
# as needed
lookForAlignDelims:
   tabular: 
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 2
      multiColumnGrouping: 0
      alignRowsWithoutMaxDelims: 1
   tabularx:
      delims: 1
   longtable: 1
   tabu: 1
   array: 1
   matrix: 1
   bmatrix: 1
   Bmatrix: 1
   pmatrix: 1
   vmatrix: 1
   Vmatrix: 1
   align: 1
   align*: 1
   alignat: 1
   alignat*: 1
   aligned: 1
   cases: 1
   dcases: 1
   listabla: 1

# if you want the script to look for \item commands 
# and format it, as follows (for example),
#       \begin{itemize}
#           \item content here
#                 next line is indented
#                 next line is indented
#           \item another item
#       \end{itemize}
# then populate indentAfterItems. See also itemNames
indentAfterItems:
    itemize: 0
    enumerate: 0
    list: 1

# if you want to use other names for your items (such as, for example, part)
# then populate them here- note that you can trick latexindent.pl
# into indenting all kinds of commands (within environments specified in 
# indentAfterItems) using this technique.
itemNames:
    item: 1
    myitem: 1

# specialBeginEnd is mainly mathmode focus, although
# there's no restrictions
specialBeginEnd:
    displayMath:
        begin: '\\\['
        end: '\\\]'
        lookForThis: 1
    inlineMath:
        begin: '(?<!\$)(?<!\\)\$(?!\$)'
        end: '(?<!\\)\$(?!\$)'
        lookForThis: 0
    displayMathTeX:
        begin: '\$\$'
        end: '\$\$'
        lookForThis: 0

# if you want to add indentation after
# a heading, such as \part, \chapter, etc
# then populate it in here - you can add 
# an indent rule to indentRules if you would 
# like something other than defaultIndent
#
# you can also change the level if you like, 
# or add your own title command
indentAfterHeadings:
    part:
       indentAfterThisHeading: 0
       level: 1
    chapter: 
       indentAfterThisHeading: 0
       level: 2
    section:
       indentAfterThisHeading: 1
       level: 3
    subsection:
       indentAfterThisHeading: 1
       level: 4
    subsection*:
       indentAfterThisHeading: 1
       level: 4
    subsubsection:
       indentAfterThisHeading: 1
       level: 5
    paragraph:
       indentAfterThisHeading: 1
       level: 6
    subparagraph:
       indentAfterThisHeading: 1
       level: 7

# if you don't want to have additional indentation 
# in an environment put it in this hash table; note that
# environments in this hash table will inherit 
# the *current* level of indentation they just won't
# get any *additional*.
noAdditionalIndent:
    myexample: 1
    mydefinition: 1
    problem: 1
    exercises: 1
    mysolution: 1
    foreach: 0
    widepage: 1
    comment: 1
    \[: 0
    \]: 0
    document: 1
    frame: 0

# if you have indent rules for particular environments
# or commands, put them in here; for example, you might just want 
# to use a space " " or maybe a double tab "\t\t"
indentRules:
   myenvironment: "\t\t"
   anotherenvironment: "\t\t\t\t"
   chapter: "\t"
   section: "\t"
   subsection: "\t"
   subsubsection: "\t"
   item: "\t"

# set noAdditionalIndent globally for codeblocks
noAdditionalIndentGlobal:
    environments: 0
    commands: 1
    optionalArguments: 0
    mandatoryArguments: 0
    ifElseFi: 0
    items: 0
    keyEqualsValuesBracesBrackets: 0
    namedGroupingBracesBrackets: 0
    UnNamedGroupingBracesBrackets: 0
    specialBeginEnd: 0
    afterHeading: 0
    filecontents: 0

# set indentRules globally for codeblocks; these need 
# to be horizontal spaces, if they are to be used
indentRulesGlobal:
    environments: 0
    commands: 0
    optionalArguments: 0
    mandatoryArguments: 0
    ifElseFi: 0
    items: 0
    keyEqualsValuesBracesBrackets: 0
    namedGroupingBracesBrackets: 0
    UnNamedGroupingBracesBrackets: 0
    specialBeginEnd: 0
    afterHeading: 0
    filecontents: 0

# command code block details
commandCodeBlocks:
    roundParenthesesAllowed: 1
    stringsAllowedBetweenArguments:
        node: 1
        at: 1
        to: 1
        decoration: 1
        ++: 1
        --: 1

# modifyLineBreaks will only be searched if the -m 
# switch is active
#    BeginStartsOnOwnLine: 1
#       if a begin statement is not already on its own line,
#       then, with -m active, it will be moved to its own line.
#
#       when set to 1, e.g 
#               some text some text \begin{myenvironment}
#           will be changed to
#               some text some text 
#               \begin{myenvironment}
#       when set to -1, e.g 
#               some text some text 
#               \begin{myenvironment}
#           will be changed to
#               some text some text \begin{myenvironment}
#       when set to 0, the switch is ignored
#
#    BodyStartsOnOwnLine: 1
#       if body does not already start on its own line, then with 
#       -m active, it will be moved to its own line.
#
#       when set to 1, e.g 
#               \begin{myenv}body text body text
#           will be changed to
#               \begin{myenv}
#                   body text body text
#       when set to -1, e.g 
#               \begin{myenv}
#                   body text body text
#           will be changed to
#               \begin{myenv}body text body text
#       when set to 0, the switch is ignored
#
#    EndStartsOnOwnLine: 1
#       if an end statement is not already on its own line,
#       then, with -m active, it will be moved to its own line.
#
#       when set to 1, e.g 
#               some text some text \end{myenvironment}
#           will be changed to
#               some text some text 
#               \end{myenvironment}
#       when set to -1, e.g 
#               some text some text 
#               \end{myenvironment}
#           will be changed to
#               some text some text \end{myenvironment}
#       when set to 0, the switch is ignored
#
#    EndFinishesWithLineBreak: 1
#       this switch adjusts line breaks immmediately 
#       after an end statement (with -m active)
#       
#       when set to 1, e.g 
#               \end{myenvironment}some text some text 
#           will be changed to
#                   \end{myenvironment}
#                   some text some text 
#       when set to -1, e.g 
#               \end{myenvironment}
#               some text some text 
#           will be changed to
#                   \end{myenvironment}some text some text 
#       when set to 0, the switch is ignored
#
# Naturally, you can specify settings for individual environments,
# commands, headings, etc, populate as you wish.
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    textWrapOptions:
        columns: 0
        separator: ""
    removeParagraphLineBreaks:
        all: 0
        alignAtAmpersandTakesPriority: 1
        environments: 
            quotation: 0
        ifElseFi: 0
        optionalArguments: 0
        mandatoryArguments: 0
        items: 1
        specialBeginEnd: 0
        afterHeading: 0
        filecontents: 0
        masterDocument: 0
        paragraphsStopAt:
            environments: 1
            commands: 0
            ifElseFi: 0
            items: 0
            specialBeginEnd: 0
            heading: 0
            filecontents: 0
            comments: 0
    environments:
        BeginStartsOnOwnLine: 3
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 2
        equation*:
            BeginStartsOnOwnLine: 1
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 1
    ifElseFi:
        IfStartsOnOwnLine: 0
        BodyStartsOnOwnLine: 0
        ElseStartsOnOwnLine: 0
        ElseFinishesWithLineBreak: 0
        FiStartsOnOwnLine: 0
        FiFinishesWithLineBreak: 0
        ifnum:
            IfStartsOnOwnLine: 0
            BodyStartsOnOwnLine: 0
            ElseStartsOnOwnLine: 0
            ElseFinishesWithLineBreak: 0
            FiStartsOnOwnLine: 0
            FiFinishesWithLineBreak: 0
    commands:
        CommandStartsOnOwnLine: 0
        emph:
            CommandStartsOnOwnLine: 0
        part:
            CommandStartsOnOwnLine: 3
        chapter:
            CommandStartsOnOwnLine: 3
        section:
            CommandStartsOnOwnLine: 3
        subsection:
            CommandStartsOnOwnLine: 3
        subsubsection:
            CommandStartsOnOwnLine: 3
        CommandNameFinishesWithLineBreak: 0
    optionalArguments:
        LSqBStartsOnOwnLine: 0
        OptArgBodyStartsOnOwnLine: 0
        RSqBStartsOnOwnLine: 0
        RSqBFinishesWithLineBreak: 0
    mandatoryArguments:
        LCuBStartsOnOwnLine: 0
        MandArgBodyStartsOnOwnLine: 0
        RCuBStartsOnOwnLine: 0
        RCuBFinishesWithLineBreak: 0
        emph:
            RCuBFinishesWithLineBreak: 0
        part:
            RCuBFinishesWithLineBreak: 3
        chapter:
            RCuBFinishesWithLineBreak: 3
        section:
            RCuBFinishesWithLineBreak: 3
        subsection:
            RCuBFinishesWithLineBreak: 3
        subsubsection:
            RCuBFinishesWithLineBreak: 3
    keyEqualsValuesBracesBrackets:
        KeyStartsOnOwnLine: 0
        EqualsStartsOnOwnLine: 0
        EqualsFinishesWithLineBreak: 0
    items:
        ItemStartsOnOwnLine: 0
        ItemFinishesWithLineBreak: 0
    namedGroupingBracesBrackets:
        NameStartsOnOwnLine: 0
        NameFinishesWithLineBreak: 0
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 3
        SpecialBodyStartsOnOwnLine: 3
        SpecialEndStartsOnOwnLine: 3
        SpecialEndFinishesWithLineBreak: 3
```
