### ISSUE TITLE
False positive match of brackets in `specialBeginEnd`

### ISSUE THREAD

**Issue by arodomanov** [cmhughes/latexindent.pl#572]
Description
--
This is somewhat a continuation of #480. I'm trying to treat brackets `[...]` as delimeters whose contents needs to be indented (e.g., in math expressions as in `example2_ok.tex` at the very bottom). To achieve this, I declare a new `specialBeginEnd` pair called `brackets`. Naturally, I don't want to accidentally match (part of) the display math delimiters `\[...\]` and optional arguments to commands and environments. Therefore, I define the `begin` regex for `brackets` to match `[` but only if it's not preceded by the backslash `\`, or the closing brace `}`, or a letter (unfortunately, I can't use a more complicated variable-length negative look-behind since Perl doesn't seem to allow it).

At the same time, I'd like the body of each environment to appear on a new line, so I activate the `BodyStartsOnOwnLine: 1` line-break switch for `environments`.

The problem I encounter is that `brackets` keeps matching optional arguments for environments (see `example4_fail.tex` below) even though I was specifically trying to avoid it.

Original .tex code (`example4_fail.tex`)
--
```latex
\begin{theorem}[Title]
  Text.
\end{theorem}

```

yaml settings (`latexindent.yaml`)
--
```yaml
defaultIndent: "  "

specialBeginEnd:
  specialBeforeCommand: 1

  brackets:
    # Match `[...]` but not display math `\[...\]`, and not optional arguments
    # to a command (e.g., `\todo[inline]`), and not optional arguments to an
    # environment (e.g., \begin{theorem}[Title]).
    begin: (?<![a-zA-Z\\\}])\[
    end: \]
    lookForThis: 1

modifyLineBreaks:
  environments:
    BodyStartsOnOwnLine: 1

```

The command used to run `latexindent`
--
```shell
latexindent -l latexindent.yaml -m -o=+_mod.tex example4_fail.tex
```

Actual/given output (`example4_fail_mod.tex`)
--
```latex
\begin{theorem}
  [Title]
  Text.
\end{theorem}

```

Desired or expected output
--
Exactly the same as `example4_fail.tex` (no modifications need to be made).

Anything else
--
The following three examples work as expected (the shell command is the same with `example4_fail.tex` replaced by another source file).

#### Original .tex code (`example1_ok.tex`)
```latex
\[
  a + b = c
\]

```

#### Actual/desired output (`example1_ok_mod.tex`)
Same as `example1_ok.tex`.

#### Original .tex code (`example2_ok.tex`)
```latex
\[
  a
  +
  [
  b + c
  ]
  =
  d
\]

```

#### Actual/desired output (`example2_ok_mod.tex`)
```latex
\[
  a
  +
  [
    b + c
  ]
  =
  d
\]

```

#### Original .tex code (`example3_ok.tex`)
```latex
\begin{theorem}Text.
\end{theorem}

```

#### Actual/desired output (`example3_ok_mod.tex`)
```latex
\begin{theorem}
  Text.
\end{theorem}

```

**Comment by cmhughes** [comment]
Thanks for this.

We can use the `replacements` switch to help with this:

```
defaultIndent: "  "

specialBeginEnd:
  specialBeforeCommand: 1

  brackets:
    # Match `[...]` but not display math `\[...\]`, and not optional arguments
    # to a command (e.g., `\todo[inline]`), and not optional arguments to an
    # environment (e.g., \begin{theorem}[Title]).
    begin: (?<![a-zA-Z\\\}])\[
    end: \]
    lookForThis: 1

modifyLineBreaks:
  environments:
    BodyStartsOnOwnLine: 1

# <!----------------
# NEW BIT FOLLOWS
# <!----------------
replacements:
  - 
    when: after
    substitution: |-
      s/(\\begin\{theorem\})\s*(\[)/$1$2/sg
```
and call using
```
latexindent.pl -m -r -l myfile.tex
```
which gives your expected output
```tex
\begin{theorem}[Title]
  Text.
\end{theorem}
```
I hope this helps, let me know if not.

**Comment by arodomanov** [comment]
Thanks for the prompt response!

The workaround you suggested seems to work for my goals after I modified the regex to respect any environment (instead of just `theorem`):
```yaml
replacements:
  -
    when: after
    substitution: |-
      s/(\\begin\{[a-zA-Z]+\})\s*(\[)/$1$2/sg
```

However, I was wondering if the behavior I described above is expected at all. Why does my original regex for `brackets` keep matching `[Title]` in `\begin{theorem}[Title]` although I forbid to have `}` right before `[`? If that's a bug, it might pop up again in some other situations...
