### ISSUE TITLE
Feature request: allowLineBreaks: 0/1

### ISSUE THREAD

**Issue by fermifunktion** [cmhughes/latexindent.pl#574]
It would be nice to have a switch like ```allowLineBreaks: 0/1``` instead or along the ```-m``` flag to allow for modifications of line breaks from within the configuration file (adding the ```-m``` flag to calls of formatters from within other programs, e.g., nvim, is sometimes not so easy).

**Comment by cmhughes** [comment]
Noted, this sounds reasonable.

**Comment by cmhughes** [comment]
Possible yaml interface
```yaml
switchesViaYaml:
    mSwitch: 0/1
    rSwitch: 0/1
   ... 
```
