### ISSUE TITLE
Problem with oneSentencePerLine and periods in command arguments

### ISSUE THREAD

**Issue by JAC28** [cmhughes/latexindent.pl#575]
Please provide the following when posting an issue:

original .tex code

```latex
This is a sample with inline math as $A=P_{crit.}$ but latexindent is breaking it.
A somehow messed-up Bibtex-Key is found as~\cite{Bibtex..2025}.
```

yaml settings

```yaml
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 0
```

actual/given output

```latex
This is a sample with inline math as $A=P_{crit.
    }$ but latexindent is breaking it.
A somehow messed-up Bibtex-Key is found as~\cite{Bibtex.
    .2025}.
```

desired or expected output

```latex
This is a sample with inline math as $A=P_{crit.}$ but latexindent is breaking it.
A somehow messed-up Bibtex-Key is found as~\cite{Bibtex..2025}.
```

anything else
--
Maybe I am overlooking something obvious but I am unable to stop this great tool from breaking my commands. Thank you for any advice to solve this issue.
