### ISSUE TITLE
default lookForAlignDelims configuration

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#583]
As detailed in https://tex.stackexchange.com/questions/739679/latexindent-define-a-default-lookforaligndelims-configuration, it would be good to be able to set default values for the values within `lookForAlignDelims`.

Perhaps something like:
```yaml
fineTuning:
  lookForAlignDelimsDefaults:
    delims: 1
    alignDoubleBackSlash: 1
    spacesBeforeDoubleBackSlash: 1
    multiColumnGrouping: 0
    alignRowsWithoutMaxDelims: 1
    spacesBeforeAmpersand: 1
    spacesAfterAmpersand: 1
    justification: left
    alignFinalDoubleBackSlash: 0
    dontMeasure: 0
    delimiterRegEx: (?<!\\)(&)
    delimiterJustification: left
    lookForChildCodeBlocks: 1
    alignContentAfterDoubleBackSlash: 0
    spacesAfterDoubleBackSlash: 1
```
Note, this would mean that `GetYamlSettings.yaml` would have to read these defaults.
