### ISSUE TITLE
`modifyLineBreaks` not working as expected

### ISSUE THREAD

**Issue by niekdomi** [cmhughes/latexindent.pl#584]
First of all, thanks for this great tool.

Im using the `-m -l` flags to execute latexindent. 

I have the following issues:

- `preserveBlankLines: 0` this should not modify afaik the linebreaks since its set to 0 (but it does)
- `columns: 20` has no effect at all?
- `multipleSpacesToSingle: 1` not always working (see the following example)

Here's the content of the `.latexindent.yaml`
```yaml
defaultIndent: "\t"

noAdditionalIndent:
  multicols:
    body: 1

modifyLineBreaks:
  preserveBlankLines: 0
  oneSentencePerLine:
    manipulateSentences: 1
  textWrapOptions:
    columns: 20
    multipleSpacesToSingle: 1
```

here's the simple `tex` file:

```tex
\documentclass[12pt]{article}
\begin{document}

\section{Introduction}
This is an example LaTeX document showing basic formatting and features.
Here is a double  space:

\begin{itemize}
	\item Mathematical equations
	\item Scientific documents
	\item Professional typesetting
\end{itemize}

\end{document}
```

As you can see betwee _double  space_ there are two spaces. I realized that if the sentence doesn't finish with a `.` it somehow can't remove the white space. (there were also other cases afaik).

Then the _This is an example LaTeX document showing basic formatting and features._ is longer than 20 characters which means, it should be wrapped. But the defined column width has no effect.

Afaik the 0 value means that it doesn't change the line breaks although the `-m` flag is set? In my file on the other hand it removes multiple blank lines.

Thanks for looking into this.
