### ISSUE TITLE
`modifyLineBreaks` not working as expected

### ISSUE THREAD

**Issue by niekdomi** [cmhughes/latexindent.pl#585]
original .tex code
--
```tex
\documentclass[12pt]{article}
\begin{document}


\section{Introduction}
This is an example LaTeX document showing basic formatting and features. Here is a double  space:

\begin{itemize}
	\item Mathematical equations
	\item Scientific documents
	\item Professional typesetting
\end{itemize}

\end{document}
```

yaml settings
--
```yaml
defaultIndent: "\t"

noAdditionalIndent:
  multicols:
    body: 1

modifyLineBreaks:
  preserveBlankLines: 0
  oneSentencePerLine:
    manipulateSentences: 1
  textWrapOptions:
    columns: 40
    multipleSpacesToSingle: 1
```

actual/given output
--
```tex
\documentclass[12pt]{article}
\begin{document}

\section{Introduction}
This is an example LaTeX document showing basic formatting and features.
Here is a double  space:

\begin{itemize}
	\item Mathematical equations
	\item Scientific documents
	\item Professional typesetting
\end{itemize}

\end{document}
```

desired or expected output
--
```tex
\documentclass[12pt]{article}
\begin{document}


\section{Introduction}
This is an example LaTeX document
showing basic formatting and features.
Here is a double space:

\begin{itemize}
	\item Mathematical equations
	\item Scientific documents
	\item Professional typesetting
\end{itemize}

\end{document}

```

anything else
--
As you can see between _double  space_ there are two spaces. I realized that if the sentence doesn't finish with a `.` it somehow can't remove the white space. (there were also other cases afaik).

Then the _This is an example LaTeX document showing basic formatting and features._ is longer than 40 characters which means, it should be wrapped. But the defined column width has no effect.

Afaik set `preserveBlankLines` to 0 value means that it doesn't change the line breaks although the `-m` flag is set? In my file on the other hand it removes multiple blank lines.

Thanks for looking into this.

**Comment by cmhughes** [comment]
Thanks for using the template :)

It looks like you''d like to combine text wrapping and one sentence per line.

solution
-
```yaml
modifyLineBreaks:
  preserveBlankLines: 0
  oneSentencePerLine:
    manipulateSentences: 1
    textWrapSentences: 1   #<---- NEW
    sentencesEndWith:      #<---- NEW
      other: |-            
        (?x)
        :
  textWrapOptions:
    columns: 40
    multipleSpacesToSingle: 1
```
gives your desired output
```tex
\documentclass[12pt]{article}
\begin{document}

\section{Introduction}
This is an example LaTeX document
showing basic formatting and features.
Here is a double space:

\begin{itemize}
	\item Mathematical equations
	\item Scientific documents
	\item Professional typesetting
\end{itemize}

\end{document}
```

explanation
-
* We need to detail that the `oneSentencePerLine` routine should wrap sentences, as in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-sentence-wrap1-yaml. 
* We also need to detail that sentences *end* with `:` which we do as in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#onesentenceperline-sentencesendwith
