### ISSUE TITLE
Question about indentation inside braces

### ISSUE THREAD

**Issue by niekdomi** [cmhughes/latexindent.pl#587]
example file
--
```tex
\documentclass[10pt, a4paper]{article}
\usepackage{amsmath}

\begin{document}
\section{first section}
\[ f(x) = \sqrt{e^x} = \left(e^{x}\right)^{\dfrac{1}{2}} = e^{\dfrac{1}{2}x} \]

{ \small
\begin{align*}
	f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
\end{align*}
}

\( x_0 \)

{ \small
		\begin{align*}
			f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
		\end{align*}
	}

hello world

	{ \small
		\begin{align*}
			f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
		\end{align*}
	}

\subsection{subsection}
{ \small
	\begin{align*}
		f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
	\end{align*}
}

\section{Other section}
 { \small
  \begin{align*}
	  f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
  \end{align*}
 }
\end{document}

```

yaml settings
--
```yml
defaultIndent: "\t"

removeTrailingWhitespace:
  beforeProcessing: 0
  afterProcessing: 1

indentAfterItems:
  itemize: 1
  itemize*: 1
  enumerate: 1
  enumerate*: 1
  description: 1
  description*: 1
  list: 1

noAdditionalIndent:
  multicols:
    body: 1

modifyLineBreaks:
  textWrapOptions:
    columns: 80
    # columns: -1
    blocksFollow:
      other: \\item|\\newline|\\begin\{quote\}|\\end\{figure\}
      commentOnPreviousLine: 0
    blocksBeginWith:
      other: .*
    blocksEndBefore:
      other: \\newline|\\begin|\\end|\\vspace|\\\\|\\pagenumbering|\\pagestyle|\\tableofcontents|\\clearpage|\\bigskip|\\smallskip|\\medskip|\\usepackage|\\setlength|\\definecolor|\\\[|\\\(

replacements:
  # Replace $$...$$ with \[...\]
  - substitution: 's/\$\$(.*?)\$\$/\\[$1\\]/sg'
    when: before

  # Replace $...$ with \(...\)
  - substitution: 's/\$(.*?)\$/\\($1\\)/sg'
    when: before

  # Standardize spacing within \( ... \)
  - substitution: 's/\\\(\s*(.*?)\s*\\\)/\\( $1 \\)/sg'
    when: before

  # Standardize spacing within \[ ... \]
  - substitution: 's/\\\[\s*(.*?)\s*\\\]/\\[ $1 \\]/sg'
    when: before
```

actual/given output
--
```tex
\documentclass[10pt, a4paper]{article}
\usepackage{amsmath}

\begin{document}
\section{first section}
\[ f(x) = \sqrt{e^x} = \left(e^{x}\right)^{\dfrac{1}{2}} = e^{\dfrac{1}{2}x} \]

{ \small
\begin{align*}
	f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
\end{align*}
}

\( x_0 \)

{ \small
		\begin{align*}
			f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
		\end{align*}
	}

hello world

	{ \small
		\begin{align*}
			f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
		\end{align*}
	}

\subsection{subsection}
{ \small
	\begin{align*}
		f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
	\end{align*}
}

\section{Other section}
 { \small
  \begin{align*}
	  f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
  \end{align*}
 }
\end{document}

```

desired or expected output
--
```tex
\documentclass[10pt, a4paper]{article}
\usepackage{amsmath}

\begin{document}
\section{first section}
\[ f(x) = \sqrt{e^x} = \left(e^{x}\right)^{\dfrac{1}{2}} = e^{\dfrac{1}{2}x} \]

{ \small
\begin{align*}
	f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
\end{align*}
}

\( x_0 \)

{ \small
\begin{align*}
	f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
\end{align*}
}

hello world

{ \small
\begin{align*}
	f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
\end{align*}
}

\subsection{subsection}
{ \small
\begin{align*}
	f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
\end{align*}
}

\section{Other section}
 { \small
  \begin{align*}
	  f(x) & = e^{\dfrac{1}{2} x} &  & \Rightarrow f(0) = e^0 = 1 \\
  \end{align*}
 }
\end{document}

```

anything else
--
Hey,

I played around with some line wrapping options and I experienced that after a `\[ \]` there is no indentation inside the `{}`, after a `subsection` there is one tab indentation and after a `section` there is 1/2 tab indentation.

Is there an option to make this consistent e.g. never indent the code inside `{}` like after the `\[ \]`?

Thanks for looking into this.

EDIT: some additional examples

**Comment by cmhughes** [comment]
Can you make sure this is as minimal and clear as possible please? One specific example at a time.

**Comment by cmhughes** [comment]
Thanks for this.

Using the following gives your desired output
```yaml
defaultIndent: "\t"

noAdditionalIndent:
  always-un-named:
    body: 1
    mandatoryArguments: 1
    optionalArguments: 1
```

This is sort of mentioned in https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#unnamedgroupingbracesbrackets but I don't think it has enough details. 

I'll update the documentation to cover this, so please leave this issue open :)

**Comment by cmhughes** [comment]
The following gives your desired output:
```yaml
defaultIndent: "\t"

noAdditionalIndentGlobal:
  mandatoryArguments: 1
  namedGroupingBracesBrackets: 1

indentRules:
  section: ''
```
