### ISSUE TITLE
Splitting long lines insde item when texttt is present

### ISSUE THREAD

**Issue by Tokariew** [cmhughes/latexindent.pl#588]
Please provide the following when posting an issue:

original .tex code
```
\documentclass{article}

\begin{document}
    \begin{itemize}
        \item If you find that latexindent.pl does not perform satisfactorily on such environments then you can set the relevant key to 0, for example 
        \item \texttt{Note that you can use a mixture of t advanced form:} other text which is weirdo
    \end{itemize}
\end{document}
```

Please paste your YAML settings (if any) here

```
indentPreamble: 1
defaultIndent: "    "

indentAfterItems:
    itemize: 1
    itemize*: 1
    enumerate: 1
    enumerate*: 1
    description: 1
    description*: 1
#
modifyLineBreaks:
    textWrapOptions:
        columns: 80
        multipleSpacesToSingle: 1
        huge: overflow
        when: after
```

actual/given output
```
\documentclass{article}

\begin{document}
\begin{itemize}
    \item If you find that latexindent.pl does not perform satisfactorily on
          such environments then you can set the relevant key to 0, for example
    \item \texttt{Note that you can use a mixture of t advanced form:} other text which is weirdo
\end{itemize}
\end{document}
```
desired or expected output
```
\documentclass{article}

\begin{document}
\begin{itemize}
    \item If you find that latexindent.pl does not perform satisfactorily on
          such environments then you can set the relevant key to 0, for example
    \item \texttt{Note that you can use a mixture of t advanced form:} other
          text which is weirdo
\end{itemize}
\end{document}
```

anything else
--
I can't get latexindent to split/join lines in itemize if there is texttt inside it when modifyLineBreaks is enabled
