### ISSUE TITLE
Latex spacing command "\!" registered as end of sentence, breaks subsequent spacing

### ISSUE THREAD

**Issue by keikun555** [cmhughes/latexindent.pl#589]
original .tex code
```tex
For example, ${^\bullet\!}\varphi_1={^\bullet\!}[0<x]={^\bullet\!}\0({^\bullet\!}\!<)X$.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

yaml settings
```yaml
defaultIndent: '  '
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    sentenceIndent: " "
    sentencesEndWith:
      other: "\;"
  textWrapOptions:
    columns: 80
    when: before
```

actual/given output
```tex
For example, ${^\bullet\!
}\varphi_1={^\bullet\!}[0<x]={^\bullet\!}\0({^\bullet\!}\!<)X$.

  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
   tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
  At vero eos et accusam et justo duo dolores et ea rebum.
  Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
   amet.
```

desired or expected output
```latex
For example,
 ${^\bullet\!}\varphi_1={^\bullet\!}[0<x]={^\bullet\!}\!({^\bullet\!}\!<)X$.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
 tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
At vero eos et accusam et justo duo dolores et ea rebum.
Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
 amet.
```

anything else
* when I replace the "\\!" with "\\," I get the intended spacing, which is why I think the "\\!" is the culprit

**Comment by keikun555** [comment]
I see the `oneSentencePerLine:sentencesEndWith:exclamationMark:1` option, though it seems to also not work.
Maybe it's not about the end of the sentence?
Updated latexindent.yaml
```yaml
defaultIndent: '  '
modifyLineBreaks:
  textWrapOptions:
    columns: 80
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    sentenceIndent: " "
    sentencesEndWith:
      other: "\;"
  textWrapOptions:
    columns: 80
    when: before
  sentencesFollow:
    exclamationMark: 0
  sentencesEndWith:
    exclamationMark: 0
```

With the same effect above

**Comment by keikun555** [comment]
As a workaround, I was able to get the desired output by disabling exclamation mark and adding a custom regex for "sentencesEndWith"

```yaml
defaultIndent: '  '
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    textWrapSentences: 1
    sentenceIndent: " "
    sentencesEndWith:
      other: "[^\\]!"
  textWrapOptions:
    columns: 80
    when: before
```
