### ISSUE TITLE
Batch of files handled differently than single file inputs

### ISSUE THREAD

**Issue by mhaider-tum** [cmhughes/latexindent.pl#591]
### Description
It seems that `latexindent.pl` handles a batch of multiple files differently than a single file input. It seems that the first file of the batch is treated similarly to the single file input, while from the second file onwards, there is a different behavior. I have noticed this behavior in `align` and/or `align*` environments, concerning the alignment of final double backslashes (`alignFinalDoubleBackSlash: 1`). This is particularly awkward if one runs a latexindent.pl pre-commit hook with `pre-commit run --all-files`, while at the same time formatting the code using latexindent on save (single file). This will result in different outputs.

### Scenario and Problem

Consider two LaTeX files `file1.tex` and `file2.tex`, both containing `align` or `align*` environments from `amsmath`. When each file is formatted by latexindent individually, i.e.

```bash
latexindent.pl -local --overwrite --silent --cruft=format file1.tex
latexindent.pl -local --overwrite --silent --cruft=format file2.tex
```

both files seem to be formatted correctly. However, if one inputs both files simultaneously as an argument to `latexindent.pl`, the second (and also $n$-th) file is treated differently.

```bash
latexindent.pl -local --overwrite --silent --cruft=format file1.tex file2.tex
```

In this case, the second file, `file2.tex`, will have an additional space character added before the final double backslash in the `align` or `align*` environment, respectively. Vice versa, if the sequence of the two files is altered,

```bash
latexindent.pl -local --overwrite --silent --cruft=format file2.tex file1.tex
```

the first file, `file1.tex` (second argument), will have the additional space added before the final double backslash in the `align` or `align*` environment. 

If one, e.g., runs `pre-commit run --all-files`, a list of files will be parsed to `latexindent.pl`, resulting in a different format than a single run of `latexindent.pl` on any individual file, which is an undesired behavior. In this context, please also see Issue #332, where the capability of handling a batch of files was added.

### Code, settings and environment

In the following, I provide a minimum (non-)working example to reproduce the error. The two files `file1.tex` and `file2.tex` have the following contents:

#### file1.tex

```latex
\documentclass{article}

\usepackage{amsmath}

\begin{document}

\begin{align*}
  \vec{Y}_\mathrm{n}= & \begin{bmatrix}
                          \phantom{\cdots} & \vdots  & \vdots  &        &         & \vdots  &        \\
                          \cdots           & g_{11}  & -g_{11} & \cdots & g_{12}  & -g_{12} & \cdots \\
                          \cdots           & -g_{11} & g_{11}  & \cdots & -g_{12} & g_{12}  & \cdots \\
                                           & \vdots  & \vdots  &        & \vdots  & \vdots  &        \\
                          \cdots           & g_{21}  & -g_{21} & \cdots & g_{22}  & -g_{22} & \cdots \\
                          \cdots           & -g_{21} & g_{21}  & \cdots & -g_{22} & g_{22}  & \cdots \\
                                           & \vdots  & \vdots  &        & \vdots  & \vdots  &
                        \end{bmatrix}\begin{matrix}
                                       \vphantom{\vdots} \\
                                       \alpha            \\
                                       \beta             \\
                                       \vphantom{\vdots} \\
                                       \gamma            \\
                                       \delta            \\
                                       \vphantom{\vdots}
                                     \end{matrix}\,\,\, .                                                                                                                                                                                                                                                                                                                                                                                                                                     \\
                      & \quad\begin{matrix}
                               \hphantom{\cdots} & \hphantom{{-}}\alpha\hphantom{_{12}} & \hphantom{{-}}\beta\hphantom{_{12}} & \hphantom{\cdots} & \hphantom{{-}}\gamma\hphantom{_{12}} & \hphantom{{-}}\delta\hphantom{_{12}} & \hphantom{\cdots}
                             \end{matrix}
\end{align*}

\end{document}
```

#### file2.tex

```latex
\documentclass{article}

\usepackage{amsmath}

\begin{document}

\begin{align}
  \vec{Y_\nu}= & \begin{bmatrix}
                          & \vdots &        &        & \vdots &        \\
                   \cdots & g_m    & \cdots & \cdots & -g_m   & \cdots \\
                          & \vdots &        &        & \vdots &        \\
                   \cdots & -g_m   & \cdots & \cdots & g_m    & \cdots \\
                          & \vdots &        &        & \vdots &        \\
                 \end{bmatrix}\begin{matrix}
                                \vphantom{\vdots} \\
                                \alpha            \\
                                \vphantom{\vdots} \\
                                \beta             \\
                                \vphantom{\vdots}
                              \end{matrix}\,\,\, .                                                                                                                                                                 \\
               & \quad\begin{matrix}
                        \hphantom{\cdots} & \hphantom{{-}}\gamma\hphantom{_m} & \hphantom{\cdots} & \hphantom{\cdots} & \hphantom{{-}}\delta & \hphantom{\cdots}
                      \end{matrix}\nonumber
\end{align}

\end{document}
```

#### .latexindent.yaml

```yaml
# configuration file for automatic LaTeX code formatting

# ----------------------------------------------------------------------------
# .:: 5.1 Backup and log file preferences
# ----------------------------------------------------------------------------
backupExtension: .bak
onlyOneBackUp: 1
logFilePreferences:
  showEveryYamlRead: 1
  showAmalgamatedSettings: 1

# ----------------------------------------------------------------------------
# .:: 5.4 Indentation and horizontal space
# ----------------------------------------------------------------------------
defaultIndent: '  '
removeTrailingWhitespace:
  beforeProcessing: 1
  afterProcessing: 1

# ----------------------------------------------------------------------------
# .:: 5.5 Aligning at delimiters
# ----------------------------------------------------------------------------
lookForAlignDelims:
  align:
    multiColumnGrouping: 1
    alignRowsWithoutMaxDelims: 1
    alignFinalDoubleBackSlash: 1
  align*:
    multiColumnGrouping: 1
    alignRowsWithoutMaxDelims: 1
    alignFinalDoubleBackSlash: 1

```

#### Environment

I am running `latexindent.pl` v3.24.5 under Windows 11 using [Strawberry Perl](https://strawberryperl.com/) v5.40.2. Additionally, Unix line endings `LF` are enforced for the output of the Perl IO system by setting the environment variable `PERLIO=:UNIX:perlio`.

### Difference between desired output and actual output

The desired output is the format given after running `latexindent.pl` on a single file input for both input files `file1.tex` and `file2.tex`, respectively. The actual wrong output is compared to the desired output, where the wrong output for `file1.tex` is given by having `file1.tex` as the second file argument of `latexindent`, and vice versa for `file2.tex`. The comparison results in the following `diff` for `file1.tex`. In this case the first argument `file2.tex` is fine.

```diff
diff --git a/file1.tex b/file1.tex
index 3107787..17f52aa 100644
--- a/file1.tex
+++ b/file1.tex
@@ -21,7 +21,7 @@
                                        \gamma            \\
                                        \delta            \\
                                        \vphantom{\vdots}
-                                     \end{matrix}\,\,\, .                                                                                                                                                                                                                                                                                                                                                                                                                                    \\
+                                     \end{matrix}\,\,\, .                                                                                                                                                                                                                                                                                                                                                                                                                                     \\
                       & \quad\begin{matrix}
                                \hphantom{\cdots} & \hphantom{{-}}\alpha\hphantom{_{12}} & \hphantom{{-}}\beta\hphantom{_{12}} & \hphantom{\cdots} & \hphantom{{-}}\gamma\hphantom{_{12}} & \hphantom{{-}}\delta\hphantom{_{12}} & \hphantom{\cdots}
                              \end{matrix}

```

When providing `file1.tex` as a first argument and `file2.tex` as the second, the following actual (undesired) output occurs, given in the following `diff` for `file2.tex`. In this case the first argument `file1.tex` is fine.

```diff
diff --git a/file2.tex b/file2.tex
index f735c52..c033e9a 100644
--- a/file2.tex
+++ b/file2.tex
@@ -17,7 +17,7 @@
                                 \vphantom{\vdots} \\
                                 \beta             \\
                                 \vphantom{\vdots}
-                              \end{matrix}\,\,\, .                                                                                                                                                                 \\
+                              \end{matrix}\,\,\, .                                                                                                                                                                  \\
                & \quad\begin{matrix}
                         \hphantom{\cdots} & \hphantom{{-}}\gamma\hphantom{_m} & \hphantom{\cdots} & \hphantom{\cdots} & \hphantom{{-}}\delta & \hphantom{\cdots}
                       \end{matrix}\nonumber

```
In both cases, an additional space character ` ` was added before the final double backslash `\\` in the `align` environment.
