### ISSUE TITLE
Question about `blocksEndBefore:`

### ISSUE THREAD

**Issue by domokopter** [cmhughes/latexindent.pl#592]
Those are actually 3 questions:

1. Can you open a discussion section for this repo, since issues like this shouldn't imho be opened as an issue.

3. I'm using
```yaml
  textWrapOptions:
    columns: 80
```

and since the wrapping is undesired in certain cases, I excluded them with:

```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    blocksFollow:
      other: \\item|(?<!\\)&|\\newline|\\begin\{quote\}|\\end\{figure\}
      commentOnPreviousLine: 0
    blocksBeginWith:
      other: .*
    blocksEndBefore:
      other: \\newline|\\begin|\\end|\\vspace|\\\\|\\pagenumbering|\\pagestyle|\\tableofcontents|\\clearpage|\\bigskip|\\smallskip|\\medskip|\\usepackage|\\setlength|\\definecolor|\\label|\\renewcommand
```

I don't know if this actually the idea to exclude so many cases, but it would be nice if we could configure this e.g., like the following to make it more readable:

```yaml
    blocksEndBefore:
      other: |
        \\newline
        \\begin
        \\end 
```

3. Since `\section*{}` does not prevent wrapping unlike `\section`, I added
```yaml
    blocksEndBefore:
      other: \\section*
```

Unfortunately, this also prevents the wrapping on the following line, so e.g., this sentence should look like this:
```tex
\section*{Example}
This is a long sentence without a meaningful blah blah This is a long sentence
without a meaningful blah blah
```

but with `other: \\section*` (since it prevents wrapping on the next line) will look like this:

```tex
\section*{Example}
This is a long sentence without a meaningful blah blah This is a long sentence without a meaningful blah blah
```

So my question is, can I somehow prevent that the text moves up to the `\section*{Example}` without disabling the wrapping on the next line?

4. Just wanted to say, that I really like this formatter :)
