### ISSUE TITLE
Separate settings for the math environments

### ISSUE THREAD

**Issue by seregaxvm** [cmhughes/latexindent.pl#80]
For the different types of math equations different indent stiles are useful. For text with small equations it's ok not to indent at all. For bigger equations it's better to start each brace with new line and indent them. It would be nice to have separate settings block just for the math environments to think about them separately and allow more control over their indent.

Consider this example of the moderately big equation:

```
\begin{multline}
	\cosh{(\alpha D)} =
	\frac{-(K^E - K^H) \cos{\varphi}}
	{2 Q^2 (K^H + K^E)^2 \sin^2{\varphi} + K^H K^E \cos^2{\varphi}}
        \pm
\\
        \pm
	\left[
		(K^E - K^H)^2 \cos^2{\varphi} +
		4 (Q^2 (K^H + K^E)^2 \sin^2{\varphi}+
		K^E K^H \cos^2{\varphi}) \times
	\right.
\\
        \left.
		\times (1 + Q^2 (K^E + K^H)^2 \sin^2{\varphi})
	\right]^{1/2}
	\left[
		2 Q^2 (K^H + K^E)^2 \sin^2{\varphi}+
		K^H K^E \cos^2{\varphi}
	\right]^{-1}
\end{multline}
```

**Comment by cmhughes** [comment]
Have you looked at 'indentRules'? :)

**Comment by seregaxvm** [comment]
Thanks, somehow I missed this part.
I still have problem with braces though. How to enable indent between them? I tried to add them to indentRules and to enable UnNamedGroupingBracesBrackets. It didn't help.

**Comment by cmhughes** [comment]
Could you provide a minimum file, together with what your desired output would be?

**Comment by seregaxvm** [comment]
Here is the example:
```
\documentclass[12pt,a4paper]{report}
\begin{document}
\begin{equation}
\left(
\left[
\left\{
\sqrt{
a+b
}
\right\}
\right]
\right)
\end{equation}
\end{document}
```

and I would like it to look like this:

```
\documentclass[12pt,a4paper]{report}
\begin{document}
\begin{equation}
	\left(
		\left[
			\left\{
				\sqrt{
					a+b
				}
			\right\}
		\right]
	\right)
\end{equation}
\end{document}
```

**Comment by cmhughes** [comment]
Thanks very much for the follow-up, it's very helpful!

If I use the following yaml file:

`seregaxvm.yaml`
-
```
commandCodeBlocks:
    roundParenthesesAllowed: 0
specialBeginEnd:
    leftRightRound:
        begin: '\\left\('
        end: '\\right\)'
        lookForThis: 1
    leftRightSquare:
        begin: '\\left\['
        end: '\\right\]'
        lookForThis: 1
    leftRightCurly:
        begin: '\\left\\\{'
        end: '\\right\\\}'
        lookForThis: 1
```
and run 
```
latexindent.pl myfile.tex -l=seregaxvm.yaml
```
then I receive the following output
```
\documentclass[12pt,a4paper]{report}
\begin{document}
\begin{equation}
	\left(
		\left[
			\left\{
				\sqrt{
					a+b
				}
			\right\}
			\right]
	\right)
\end{equation}
\end{document}
```
This is *nearly* correct, but the problem is that `latexindent.pl` is picking up `\left[...]` as a *command* and is not giving itself the option to find `\left[` as a `specialBeginEnd`. 

Given that this behaviour is undesired, I'm going to label this as a bug. I've got a few ideas on how to fix it -- leave it with me, and I'll return to this.

Thanks again for raising it.
