### ISSUE TITLE
One sentence per line?

### ISSUE THREAD

**Issue by mlep** [cmhughes/latexindent.pl#81]
I would like to know if latexindent can enforce a "one sentence per line" format.
I could not find this subject in the documentation (esp. in the section about the modifylinebreaks switch), and I am wondering if this is, indeed, possible.

**Comment by cmhughes** [comment]
Thanks for this; it's not currently possible, but perhaps it could be added to `textWrapOptions`, something like
```
textWrapOptions
     oneSentencePerLine: 
           sentencesBeginWith: 
                  a-z: 1
                  A-Z: 1
           sentencesEndWith: 
                  .: 1
```

Does this sound like the kind of thing? 

Just for clarification, could you provide some before and after output, for reference.

**Comment by mlep** [comment]
Thank you for prompt reply!

Here is an example:
Before

````This is the first````
````sentence. This is the second sentence. This is the````
````third sentence````.


After

````This is the first sentence.````
````This is the second sentence.````
````This is the third sentence.````

Note: this formatting is desirable when using a version control software.
A detailed explanation (and a perl script!) here: http://loopspace.mathforge.org/HowDidIDoThat/TeX/VCS/#section.3

**Comment by cmhughes** [comment]
This sounds doable, on the face of it.

@loopspace would you like to weigh in on this? 

Do either of you have any input on the interface to this and the options you'd like to see?

**Comment by loopspace** [comment]
Not sure what I can contribute, other than that I agree that this would be a good thing to have in this program (which I was unaware of until now, but which looks great).  If you implement it then it might even make my script obsolete (no bad thing).

I suspect that my script is implemented in a different way to yours, but if there's anything in there that's helpful then you're welcome to it.  If the licence is incompatible I'd be happy to fix that.  As for details, I don't think I've anything to add that isn't in that post linked above.

I tested my script by producing postscript documents and diffing them, so I don't have a readymade test suite, sorry.

**Comment by cmhughes** [comment]
@loopspace thanks for the follow-up. If either you or @mlep have any test cases (small, medium or large), it would be great to see them here, preferably both before and after results.

I'm happy to commit to trying to develop this, so I'll label this as an 'enhancement'. There's a few issues ahead of this, but I'll follow-up with progress. 

----

Some notes to myself:
- will need `Sentences.pm`, and update `Tokens.pm` and `Document.pm` accordingly;
- the regexp for sentences will need to end with either `?`, `!` or `.`
- should this be done on a per-thing basis? e.g for `environments`, etc, just as in the `removeParagraphLineBreaks`

**Comment by cmhughes** [comment]
I've started development of this feature, and its taking place on https://github.com/cmhughes/latexindent.pl/tree/feature/one-sentence-per-line

Feel free to clone it, if you'd like :) I've only done one commit so far, but it's hopefully started in the right direction.

**Comment by mlep** [comment]
@cmhughes  Thank you for starting the implementation of this feature! I have tried to use it, but it seems I cannot figure out the specific parameter to put on the command line.. Please, could you give me an example?

**Comment by cmhughes** [comment]
I consider it very much in development at the moment :) I hope to work on
it in mid/late December 2017, watch this space for an update!

**Comment by cmhughes** [comment]
I think there's a specific folder that tests the feature in the test-cases
directory; this should give some clues!

It's been a few months since I've worked on it, my apologies.

**Comment by mlep** [comment]
OK, I'll wait a bit. Thanks for your work.

**Comment by cmhughes** [comment]
I've been developing this feature on https://github.com/cmhughes/latexindent.pl/tree/feature/one-sentence-per-line. 

I think it's pretty much ready to be merged into develop, and will then be part of Version 3.4, which I hope to release early in 2018. Feel free to clone the above branch and experiment, if you'd like. I'll continue to update this issue with updates.

You can compile the documentation for yourself to produce the pdf, if you'd like, but here's a sneak peak in the mean time:

![screenshot from 2017-12-23 17-38-24](https://user-images.githubusercontent.com/2224480/34321493-315b6106-e808-11e7-9acb-b10355b7b940.png)

**Comment by cmhughes** [comment]
I consider this feature implemented and documented, and it is part of the `develop` branch. I hope to address a few more issues, and then should release `V3.4` (which will include this feature) early in 2018. 

Happy holidays!

**Comment by mlep** [comment]
Hi! Thanks for your work. It works great in most of cases!
I have tested some files and noted some glitches. Here they are (each example was one paragraph):
- "This is an example (i.e. a test)." is currently converted into "This is an example (i.\ne. a test)."
- "The unit is $\rm kg.m^{-2}.s^{-1}$." ==> "The unit is $\rm kg.\nm^{-2}.s^{-1}$.
- "Values goes from 0.02 to 0.74 Pa." ==> ""Values goes from 0.\n02 to 0.74 Pa."
- "Here some space needed \hspace{0.5cm}." ==> "Here some space needed \hspace{0.\n5cm}."
 - "The value is $\lambda=3.67$." ==> "- "The value is $lambda=3.\n67$."
- "The URL is \url{www.scilab.org}." ==> "The URL is \url{www.\nscilab.org}."

**Comment by cmhughes** [comment]
Many thanks for these :)

All of the examples you have provided are the *default* behaviour, and details of how to customise the yaml to fix these are given in the documentation. In particular, you can set up rules such as the following:
```
modifyLineBreaks:
    oneSentencePerLine:
        sentencesEndWith:
            fullStop: 0
            other: "(?:\.\)(?!\h*[a-z]))|(?<!(?:(?:e\.g)))\.(?!(?:[a-z]|[A-Z]|\-|\,|\}|[0-9]))"
```
If you save the above YAML as, for example, `mlep.yaml` and then run 
```
latexindent.pl -m -l=mlep.yaml mlep.tex
```

So, the big question for us to decide: should the default behaviour be changed?

**Comment by mlep** [comment]
Indeed, I tried the default configuration. 
I guess that new (inexperienced) users will see the current behavior as faulty. Considering the principle of least surprise, I would guess the proper processing of the above strings should be default.
Asking the question the other way around: why not to make it default?
Of course, I am not the one to make the decision.
Thanks again for implementing this feature. Very useful.

**Comment by cmhughes** [comment]
Many thanks for the follow up. I've been thinking about this a lot, and I
think you're right.

I'll adjust it to make the default option to mimick the configuration
detailed above. I hope to be able to tackle this by the end of the week;
I'll post back here with an update -- perhaps you could take it for another
spin at that point?

Thanks again!

**Comment by mlep** [comment]
I will continue to monitor the branch and test it after your update.

**Comment by cmhughes** [comment]
@mlep I've changed the default behaviour -- would you like to take it for another spin? :) Thanks for your help in shaping and testing this :)

**Comment by mlep** [comment]
After playing with the new version (branch develop, as today), the default behavior is definitely more convenient. I have found some issues that may be of interest.

- The sentence 
````
The names (Smith, Doe, etc.) are inherited.
````
is converted into
````
The names (Smith, Doe, etc.
) are inherited.
````
I guess the dot of the word "etc." should be considered an end of a sentence only when followed by a space.

- 
````
Two items are used:
\begin{itemize}
	\item Item 1.
	\item Item 2.
\end{itemize}
````
is converted into
````
Two items are used: \begin{itemize} \item Item 1.
	\item Item 2.
\end{itemize}
````
In my opinion, it should not be modified: the itemize environment should be kept as is. 

- 
````
The energy is defined as
\begin{equation}
	E=m c^2
\end{equation}
where m is the mass.
````
is converted into
````
The energy is defined as \begin{equation} E=m c^2 \end{equation} where m is the mass.
````
Similarly, the equation environment should be layed out independently of rest of the sentence.

- 
````
\begin{table}[htbp]
	\caption{\label{tab1} Here is the legend.}
	\begin{tabular}{cc}
		1 & 1 \\
	\end{tabular}
\end{table}

This is a sentence.

\begin{table}[htbp]
	\caption{\label{tab1} Here is the legend.}
	\begin{tabular}{cc}
		1 & 1 \\
	\end{tabular}
\end{table}
````
is converted into 
````
\begin{table}[htbp]
	\caption{\label{tab1}
		Here is the legend.} \begin{tabular}{cc} 1 & 1 \\ \end{tabular} \end{table} 

This is a sentence.

\begin{table}[htbp]
	\caption{\label{tab1} Here is the legend.}
	\begin{tabular}{cc}
		1 & 1 \\
	\end{tabular}
\end{table}
````
Note the change in layout of the first table environment (but the second is not affected).
Strangely, if "This is a sentence." or the "\label{tab1}" is removed, the layout is preserved.

**Comment by cmhughes** [comment]
Thanks a lot for your time in reviewing this, I appreciate it. 

Going through your points one by one:

- I agree with your point about `etc.` and this is addressed as of https://github.com/cmhughes/latexindent.pl/commit/75e449255afc6a38267d117e4165bbe00ea58cfd
- regarding the `\begin{itemize}` and `\begin{equation}` points, this is interesting, and something that I do discuss in the manual (you would have had to compile it to pdf yourself, and I don't expect you to go through it, as it is quite long!). I'd say that the script is operating as expected: the user specifies that they want one sentence per line, and this puts the sentence on a line. You can tweak this in a few different ways; you could change `removeSentenceLineBreaks` to be `0`. Alternatively (see https://github.com/cmhughes/latexindent.pl/commit/e9b2ccf9ab35f353621b806e331b678c583481fc#diff-6df24c7af648fd1ea176353d02ac2562), you could use the following additional yaml settings:
```
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
```
- your last point about the `tabular` is also implemented as of https://github.com/cmhughes/latexindent.pl/commit/75e449255afc6a38267d117e4165bbe00ea58cfd

How does this sound?

**Comment by mlep** [comment]
Dear @cmhughes, I can confirm the two issues you corrected are solved. Thank you for pointing out the settings regarding  the itemize and equation environments. More generally, thank you for your responsive support!

**Comment by cmhughes** [comment]
You're very welcome, thanks for your help in testing this. I'll credit you
in the documentation, and do stay in touch if you find problems with this
or anything else.

I hope to get V3.4 out within the next month or so; once it is released,
I'll close this issue.

**Comment by cmhughes** [comment]
Implemented in V3.4 (https://github.com/cmhughes/latexindent.pl/pull/96), thanks for the help with this! I'll get it uploaded to ctan today, and your tex distribution should pick up the update within a day or so.

**Comment by koppor** [comment]
I am experimenting with it. Settings:

```
\begin{figure}
   Simple Figure
  \caption{Simple Figure}
  \label{fig:simple}
\end{figure}
```

gets 

```
  Simple Figure \caption{Simple Figure} \label{fig:simple} \end{figure} 
```

Currently no idea, why the tool does not recognize environments anymore.

Further, it adds spaces at the end of line, which leads to "complaints" by git gui:

![grafik](https://user-images.githubusercontent.com/1366654/35275655-c4840186-0040-11e8-9f5c-858379adc9c2.png)

**Comment by koppor** [comment]
It should recognize `...`:

    In the bibliography, use \texttt{\textbackslash textsuperscript} for ``st'', ``nd'', ...:

gets

    In the bibliography, use \texttt{\textbackslash textsuperscript} for ``st'', ``nd'', .
    ..:

**Comment by cmhughes** [comment]
@koppor for your first issue, try using
```
removeSentenceLineBreaks: 0
```
For your second issue, try using, for example,
```
indentPreamble: 1
defaultIndent: '  '
preserveBlankLines: 1
condenseMultipleBlankLinesInto: 0
maxNumberOfBackUps: 9
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        removeSentenceLineBreaks: 0
        sentencesFollow:
            par: 1
            blankLine: 1
            fullStop: 1
            exclamationMark: 1
            questionMark: 1
            rightBrace: 1
            commentOnPreviousLine: 1
            other: 0
        sentencesBeginWith:
            A-Z: 1
            a-z: 0
            other: 0
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 0
            exclamationMark: 1
            questionMark: 1
            other: '(?:\.\)(?!\h*[a-z]))|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|\,|\.|[0-9]))'
```
Have you considered using `\ldots`? :)
